Repository elastic/security-docs, pull requests merged in 2020-10, with the labels that each got.

#275 [7.x] updates readme (#273)
  prebuilt-rules-scripts/readme.md
Labels: backport

#276 [7.10] updates readme (#273)
  prebuilt-rules-scripts/readme.md
Labels: backport

#277 [7.x] [Docs]Minor rule script edits (#274)
  prebuilt-rules-scripts/create_documentation.py
  prebuilt-rules-scripts/get-rule-diff.py
Labels: backport

#278 [7.10] [Docs]Minor rule script edits (#274)
  prebuilt-rules-scripts/create_documentation.py
  prebuilt-rules-scripts/get-rule-diff.py
Labels: backport

#283 [7.9] Add Analyze event documentation (#280)
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/images/analyze-event-view.png
  docs/detections/images/analyze-event.png
  docs/detections/images/event-names.png
  docs/detections/images/event-panel.png
Labels: backport

#281 [7.x] Add Analyze event documentation (#280)
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/images/analyze-event-view.png
  docs/detections/images/analyze-event.png
  docs/detections/images/event-names.png
  docs/detections/images/event-panel.png
Labels: backport

#285 [7.x] updated script to use rule_id and fixes 7.9.0 final file (#284)
  prebuilt-rules-scripts/create_documentation.py
  prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.9.0.json
  prebuilt-rules-scripts/get-rule-diff.py
  prebuilt-rules-scripts/orig-rules-json-files/7.10.0-prebuilt-rule.json
  prebuilt-rules-scripts/readme.md
Labels: backport

#286 [7.10] updated script to use rule_id and fixes 7.9.0 final file (#284)
  prebuilt-rules-scripts/create_documentation.py
  prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.9.0.json
  prebuilt-rules-scripts/get-rule-diff.py
  prebuilt-rules-scripts/orig-rules-json-files/7.10.0-prebuilt-rule.json
  prebuilt-rules-scripts/readme.md
Labels: backport

#288 [7.x] add deleted rules and use release number variables (#287)
  prebuilt-rules-scripts/create-json-from-docs.py
  prebuilt-rules-scripts/create_documentation.py
  prebuilt-rules-scripts/get-rule-diff.py
  prebuilt-rules-scripts/readme.md
  prebuilt-rules-scripts/update_current_text.py
Labels: backport

#289 [7.10] add deleted rules and use release number variables (#287)
  prebuilt-rules-scripts/create-json-from-docs.py
  prebuilt-rules-scripts/create_documentation.py
  prebuilt-rules-scripts/get-rule-diff.py
  prebuilt-rules-scripts/readme.md
  prebuilt-rules-scripts/update_current_text.py
Labels: backport

#296 [7.x] minor script corrections (#295)
  prebuilt-rules-scripts/create_documentation.py
  prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.9.1.json
  prebuilt-rules-scripts/get-rule-diff.py
  prebuilt-rules-scripts/readme.md
  prebuilt-rules-scripts/update_current_text.py
Labels: backport

#297 [7.10] minor script corrections (#295)
  prebuilt-rules-scripts/create_documentation.py
  prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.9.1.json
  prebuilt-rules-scripts/get-rule-diff.py
  prebuilt-rules-scripts/readme.md
  prebuilt-rules-scripts/update_current_text.py
Labels: backport

#298 [7.9] minor script corrections (#295)
  prebuilt-rules-scripts/create_documentation.py
  prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.9.1.json
  prebuilt-rules-scripts/get-rule-diff.py
  prebuilt-rules-scripts/readme.md
  prebuilt-rules-scripts/update_current_text.py
Labels: backport

#300 [7.x] adds list of rules with changed names (#299)
  prebuilt-rules-scripts/create_documentation.py
  prebuilt-rules-scripts/readme.md
Labels: backport

#301 [7.10] adds list of rules with changed names (#299)
  prebuilt-rules-scripts/create_documentation.py
  prebuilt-rules-scripts/readme.md
Labels: backport

#302 [7.9] adds list of rules with changed names (#299)
  prebuilt-rules-scripts/create_documentation.py
  prebuilt-rules-scripts/readme.md
Labels: backport

#304 [7.x] fixes asciidoc formatting (#303)
  prebuilt-rules-scripts/create_documentation.py
  prebuilt-rules-scripts/readme.md
Labels: backport

#305 [7.10] fixes asciidoc formatting (#303)
  prebuilt-rules-scripts/create_documentation.py
  prebuilt-rules-scripts/readme.md
Labels: backport

#306 [7.9] fixes asciidoc formatting (#303)
  prebuilt-rules-scripts/create_documentation.py
  prebuilt-rules-scripts/readme.md
Labels: backport

#307 [7.x] Small 7.10 updates to UI page. (#279)
  docs/getting-started/images/admin-ui.png
  docs/getting-started/security-ui.asciidoc
Labels: backport

#308 [7.10] Small 7.10 updates to UI page. (#279)
  docs/getting-started/images/admin-ui.png
  docs/getting-started/security-ui.asciidoc
Labels: backport

#319 [DOCS] Add machine learning jobs to Whats New
  docs/whats-new.asciidoc
Labels: TEAM:Docs, v7.10.0

#320 [7.x][DOCS] Add machine learning jobs to Whats New (#319)
  docs/whats-new.asciidoc
Labels: backport

#321 [7.10][DOCS] Add machine learning jobs to Whats New (#319)
  docs/whats-new.asciidoc
Labels: backport

#325 [DOCS] Changes the title of the ML related highlight section
  docs/whats-new.asciidoc
Labels: TEAM:Docs, v7.10.0, v7.11.0

#326 [7.x] [DOCS] Changes the title of the ML related highlight section. (#325)
  docs/whats-new.asciidoc
Labels: backport

#327 [7.10] [DOCS] Changes the title of the ML related highlight section. (#325)
  docs/whats-new.asciidoc
Labels: backport

#322 [DOCS] Admin and endpoint updates (7.10)
  docs/management/admin/admin-pg-ov.asciidoc
  docs/management/admin/images/admin-pg.png
  docs/management/admin/images/config-status.png
  docs/management/admin/images/filter-endpoints.png
  docs/management/admin/images/host-flyout.png
  docs/management/admin/images/remove-app.png
  docs/management/admin/images/trusted-apps-list.png
Labels: v7.10.0

#330 [7.10] [DOCS] Admin and endpoint updates (7.10) (#322)
  docs/management/admin/admin-pg-ov.asciidoc
  docs/management/admin/images/admin-pg.png
  docs/management/admin/images/config-status.png
  docs/management/admin/images/filter-endpoints.png
  docs/management/admin/images/host-flyout.png
  docs/management/admin/images/remove-app.png
  docs/management/admin/images/trusted-apps-list.png
Labels: backport

#329 [7.x] [DOCS] Admin and endpoint updates (7.10) (#322)
  docs/management/admin/admin-pg-ov.asciidoc
  docs/management/admin/images/admin-pg.png
  docs/management/admin/images/config-status.png
  docs/management/admin/images/filter-endpoints.png
  docs/management/admin/images/host-flyout.png
  docs/management/admin/images/remove-app.png
  docs/management/admin/images/trusted-apps-list.png
Labels: backport

#333 [7.10] [DOCS] Updates to install endpoint page (#331)
  docs/getting-started/install-endpoint.asciidoc
Labels: backport

#332 [7.x] [DOCS] Updates to install endpoint page (#331)
  docs/getting-started/install-endpoint.asciidoc
Labels: backport

#310 [Docs] Adds 7.10 Cases API updates
  docs/cases/api/cases-api/case-api-update-connector.asciidoc
  docs/cases/api/cases-api/cases-api-assign-connector.asciidoc
  docs/cases/api/cases-api/cases-api-create.asciidoc
  docs/cases/api/cases-api/cases-api-find-cases.asciidoc
  docs/cases/api/cases-api/cases-api-get-case-activity.asciidoc
  docs/cases/api/cases-api/cases-api-get-case.asciidoc
  docs/cases/api/cases-api/cases-api-get-connector.asciidoc
  docs/cases/api/cases-api/cases-api-update.asciidoc
Labels: v7.10.0

#341 [7.x] Getting Started updates - 7.10 (#340)
  docs/getting-started/advanced-setting.asciidoc
  docs/getting-started/index.asciidoc
Labels: backport

#342 [7.10] Getting Started updates - 7.10 (#340)
  docs/getting-started/advanced-setting.asciidoc
  docs/getting-started/index.asciidoc
Labels: backport
