Repository elastic/security-docs, pull requests merged in 2020-12, with the labels that each got.

#386 [7.10] Updating action image for 7.10.1. (#384)
  docs/detections/images/available-action-types.png
Labels: backport

#385 [7.x] Updating action image for 7.10.1. (#384)
  docs/detections/images/available-action-types.png
Labels: backport

#398 [7.10] Add known issue about value lists (#383)
  docs/release-notes.asciidoc
Labels: backport

#397 [7.x] Add known issue about value lists (#383)
  docs/release-notes.asciidoc
Labels: backport

#405 [7.10] Issue #410: Add 7.10.1 release notes (#402)
  docs/release-notes.asciidoc
Labels: backport

#404 [7.x] Issue #410: Add 7.10.1 release notes (#402)
  docs/release-notes.asciidoc
Labels: backport

#414 [7.10] Doc bug fixes for 7.10.1 (#411)
  docs/detections/building-block-rule.asciidoc
  docs/detections/detection-engine-intro.asciidoc
  docs/detections/detections-ui-exceptions.asciidoc
  docs/detections/images/add-exception-ui.png
  docs/detections/images/alert-indices-ui.png
  docs/detections/images/detections-ui.png
  docs/detections/images/exception-histogram.png
  docs/detections/images/more-action-button.png
  docs/detections/rules-ui-create.asciidoc
  docs/management/admin/admin-pg-ov.asciidoc
  docs/management/admin/images/admin-pg.png
Labels: backport

#413 [7.x] Doc bug fixes for 7.10.1 (#411)
  docs/detections/building-block-rule.asciidoc
  docs/detections/detection-engine-intro.asciidoc
  docs/detections/detections-ui-exceptions.asciidoc
  docs/detections/images/add-exception-ui.png
  docs/detections/images/alert-indices-ui.png
  docs/detections/images/detections-ui.png
  docs/detections/images/exception-histogram.png
  docs/detections/images/more-action-button.png
  docs/detections/rules-ui-create.asciidoc
  docs/management/admin/admin-pg-ov.asciidoc
  docs/management/admin/images/admin-pg.png
Labels: backport

#415 [7.x] Issue 391: Update installation screenshots (#399)
  docs/getting-started/images/install-endpoint/add-agent.png
  docs/getting-started/images/install-endpoint/add-elastic-endpoint-security.png
  docs/getting-started/images/install-endpoint/endpoint-configuration.png
  docs/getting-started/images/install-endpoint/security-integration.png
  docs/getting-started/install-endpoint.asciidoc
Labels: backport

#416 [7.10] Issue 391: Update installation screenshots (#399)
  docs/getting-started/images/install-endpoint/add-agent.png
  docs/getting-started/images/install-endpoint/add-elastic-endpoint-security.png
  docs/getting-started/images/install-endpoint/endpoint-configuration.png
  docs/getting-started/images/install-endpoint/security-integration.png
  docs/getting-started/install-endpoint.asciidoc
Labels: backport

#418 [7.10] Issue-395: Change Event Type for Timeline Schema (#400)
  docs/reference/timeline-schema.asciidoc
Labels: backport

#417 [7.x] Issue-395: Change Event Type for Timeline Schema (#400)
  docs/reference/timeline-schema.asciidoc
Labels: backport

#420 Fix broken Fleet links
  docs/es-overview.asciidoc
  docs/getting-started/advanced-setting.asciidoc
  docs/getting-started/install-endpoint.asciidoc
  docs/management/admin/admin-pg-ov.asciidoc
Labels: TEAM:Docs

#421 [7.x] Fix broken Fleet links (#420)
  docs/es-overview.asciidoc
  docs/getting-started/advanced-setting.asciidoc
  docs/getting-started/install-endpoint.asciidoc
  docs/management/admin/admin-pg-ov.asciidoc
Labels: TEAM:Docs, backport

#422 [7.11] Fix broken Fleet links (#420)
  docs/es-overview.asciidoc
  docs/getting-started/advanced-setting.asciidoc
  docs/getting-started/install-endpoint.asciidoc
  docs/management/admin/admin-pg-ov.asciidoc
Labels: TEAM:Docs, backport

#423 [7.10] Fix broken Fleet links (#420)
  docs/es-overview.asciidoc
  docs/getting-started/advanced-setting.asciidoc
  docs/getting-started/install-endpoint.asciidoc
  docs/management/admin/admin-pg-ov.asciidoc
Labels: TEAM:Docs, backport
