Repository elastic/security-docs, pull requests merged in 2020-11, with the labels that each got.

#270 [Docs]Adds 7.10 detection rule updates to API docs
  docs/detections/api/rules/rules-api-create.asciidoc
  docs/detections/api/rules/rules-api-update.asciidoc
Labels: v7.10.0

#354 [7.10] Fix Full Disk Access inaccuracies. (#335)
  docs/getting-started/images/install-endpoint/endpoints-enrolling.png
  docs/getting-started/images/system-extension-prompt.png
  docs/getting-started/ingest-data.asciidoc
  docs/getting-started/install-endpoint.asciidoc
  docs/getting-started/sensor-full-disk-access.asciidoc
Labels: backport

#353 [7.x] Fix Full Disk Access inaccuracies. (#335)
  docs/getting-started/images/install-endpoint/endpoints-enrolling.png
  docs/getting-started/images/system-extension-prompt.png
  docs/getting-started/ingest-data.asciidoc
  docs/getting-started/install-endpoint.asciidoc
  docs/getting-started/sensor-full-disk-access.asciidoc
Labels: backport

#356 [7.10] [Docs]Adds 7.10 detection rule updates to API docs (#270)
  docs/detections/api/rules/rules-api-create.asciidoc
  docs/detections/api/rules/rules-api-update.asciidoc
Labels: backport

#355 [7.x] [Docs]Adds 7.10 detection rule updates to API docs (#270)
  docs/detections/api/rules/rules-api-create.asciidoc
  docs/detections/api/rules/rules-api-update.asciidoc
Labels: backport

#359 [7.x] [DOCS] What's new in 7.10. (#352)
  docs/whats-new.asciidoc
Labels: backport

#360 [7.10] [DOCS] What's new in 7.10. (#352)
  docs/whats-new.asciidoc
Labels: backport

#357 [7.x] [DOCS] Create rule updates - 7.10 (#336)
  docs/detections/api/exceptions/api-create-exception-item.asciidoc
  docs/detections/detection-engine-intro.asciidoc
  docs/detections/detections-ui-exceptions.asciidoc
  docs/detections/images/create-new-rule.png
  docs/detections/images/eql-rule-query-example.png
  docs/detections/images/indicator-rule-example.png
  docs/detections/images/preview-rule.png
  docs/detections/images/threat-math-rule-query-example.png
  docs/detections/rules-ui-create.asciidoc
  docs/detections/rules-ui-manage.asciidoc
  docs/getting-started/advanced-setting.asciidoc
Labels: backport

#358 [7.10] [DOCS] Create rule updates - 7.10 (#336)
  docs/detections/api/exceptions/api-create-exception-item.asciidoc
  docs/detections/detection-engine-intro.asciidoc
  docs/detections/detections-ui-exceptions.asciidoc
  docs/detections/images/create-new-rule.png
  docs/detections/images/eql-rule-query-example.png
  docs/detections/images/indicator-rule-example.png
  docs/detections/images/preview-rule.png
  docs/detections/images/threat-math-rule-query-example.png
  docs/detections/rules-ui-create.asciidoc
  docs/detections/rules-ui-manage.asciidoc
  docs/getting-started/advanced-setting.asciidoc
Labels: backport

#363 [7.10] update to what's new (#361)
  docs/whats-new.asciidoc
Labels: backport

#362 [7.x] update to what's new (#361)
  docs/whats-new.asciidoc
Labels: backport

#365 [7.10] Visual event analyzer updates for 7.10 (#347)
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/detections-index.asciidoc
  docs/detections/images/analyze-event-view.png
  docs/detections/images/analyze-event.png
  docs/detections/images/event-details.png
  docs/detections/images/event-type.png
  docs/detections/images/full-screen-analyzer.png
  docs/detections/images/graphical-view.png
  docs/detections/images/kql-agent-type.png
  docs/detections/images/process-details.png
  docs/detections/images/process-list.png
  docs/detections/visual-event-analyzer.asciidoc
Labels: backport

#364 [7.x] Visual event analyzer updates for 7.10 (#347)
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/detections-index.asciidoc
  docs/detections/images/analyze-event-view.png
  docs/detections/images/analyze-event.png
  docs/detections/images/event-details.png
  docs/detections/images/event-type.png
  docs/detections/images/full-screen-analyzer.png
  docs/detections/images/graphical-view.png
  docs/detections/images/kql-agent-type.png
  docs/detections/images/process-details.png
  docs/detections/images/process-list.png
  docs/detections/visual-event-analyzer.asciidoc
Labels: backport

#367 [7.10] Adds 7.10 security release notes (#345)
  docs/getting-started/detections-req.asciidoc
  docs/images/detection-rule-failure.png
  docs/release-notes.asciidoc
Labels: backport

#366 [7.x] Adds 7.10 security release notes (#345)
  docs/getting-started/detections-req.asciidoc
  docs/images/detection-rule-failure.png
  docs/release-notes.asciidoc
Labels: backport

#371 [7.10] [7.10]: Add upgrade requirements to 7.10 release notes (#369)
  docs/release-notes.asciidoc
Labels: backport

#370 [7.x] [7.10]: Add upgrade requirements to 7.10 release notes (#369)
  docs/release-notes.asciidoc
Labels: backport

#374 [7.10] Add updated detect index permissions (#372)
  docs/getting-started/detections-req.asciidoc
  docs/getting-started/images/sec-admin-user.png
  docs/getting-started/images/sec-user.png
Labels: backport

#373 [7.x] Add updated detect index permissions (#372)
  docs/getting-started/detections-req.asciidoc
  docs/getting-started/images/sec-admin-user.png
  docs/getting-started/images/sec-user.png
Labels: backport

#375 Fix Fleet links and naming
  docs/es-overview.asciidoc
  docs/getting-started/advanced-setting.asciidoc
  docs/getting-started/install-endpoint.asciidoc
  docs/management/admin/admin-pg-ov.asciidoc
  docs/siem/overview.asciidoc
Labels: TEAM:Docs, documentation, v7.10.0, v7.11.0

#376 [7.x] Fix Fleet links and naming (#375)
  docs/es-overview.asciidoc
  docs/getting-started/advanced-setting.asciidoc
  docs/getting-started/install-endpoint.asciidoc
  docs/management/admin/admin-pg-ov.asciidoc
  docs/siem/overview.asciidoc
Labels: backport, documentation

#377 [7.10] Fix Fleet links and naming (#375)
  docs/es-overview.asciidoc
  docs/getting-started/advanced-setting.asciidoc
  docs/getting-started/install-endpoint.asciidoc
  docs/management/admin/admin-pg-ov.asciidoc
  docs/siem/overview.asciidoc
Labels: backport, documentation

#381 [7.10] Adding ECS note to docs. (#379)
  docs/es-overview.asciidoc
  docs/getting-started/sec-app-requirements.asciidoc
Labels: backport

#380 [7.x] Adding ECS note to docs. (#379)
  docs/es-overview.asciidoc
  docs/getting-started/sec-app-requirements.asciidoc
Labels: backport
