Repository elastic/security-docs, pull requests merged in 2020-09, with the labels that each got.

#217 [Docs]Post upgrade reindex requirement
  docs/index.asciidoc
  docs/post-upgrade-req.asciidoc
  docs/release-notes.asciidoc
  docs/template-script.asciidoc
Labels: 7.9

#219 [7.x] [Docs]Post upgrade reindex requirement (#217)
  docs/index.asciidoc
  docs/post-upgrade-req.asciidoc
  docs/release-notes.asciidoc
  docs/template-script.asciidoc
Labels: backport

#220 [7.9] [Docs]Post upgrade reindex requirement (#217)
  docs/index.asciidoc
  docs/post-upgrade-req.asciidoc
  docs/release-notes.asciidoc
  docs/template-script.asciidoc
Labels: backport

#221 [7.x] [Docs]Updates tuning prebuilt rules (#218)
  docs/detections/prebuilt-rules/images/process-exception.png
  docs/detections/prebuilt-rules/images/process-specific-exception.png
  docs/detections/prebuilt-rules/images/rule-details-page.png
  docs/detections/prebuilt-rules/tune-rule-signals.asciidoc
  docs/detections/rules-ui-manage.asciidoc
Labels: backport

#222 [7.9] [Docs]Updates tuning prebuilt rules (#218)
  docs/detections/prebuilt-rules/images/process-exception.png
  docs/detections/prebuilt-rules/images/process-specific-exception.png
  docs/detections/prebuilt-rules/images/rule-details-page.png
  docs/detections/prebuilt-rules/tune-rule-signals.asciidoc
  docs/detections/rules-ui-manage.asciidoc
Labels: backport

#223 [Docs]Adds index post upgrade requirement clarifications
  docs/post-upgrade-req.asciidoc
  docs/release-notes.asciidoc
  docs/template-script.asciidoc
Labels: 7.9

#224 [7.x] [Docs]Adds index post upgrade requirement clarifications (#223)
  docs/post-upgrade-req.asciidoc
  docs/release-notes.asciidoc
  docs/template-script.asciidoc
Labels: backport

#225 [7.9] [Docs]Adds index post upgrade requirement clarifications (#223)
  docs/post-upgrade-req.asciidoc
  docs/release-notes.asciidoc
  docs/template-script.asciidoc
Labels: backport

#228 [Docs]Fix signals index typo
  docs/detections/api/rules/rules-api-overview.asciidoc
Labels: 7.9

#229 [7.x] fix signals index name (#228)
  docs/detections/api/rules/rules-api-overview.asciidoc
Labels: backport

#230 [7.9] fix signals index name (#228)
  docs/detections/api/rules/rules-api-overview.asciidoc
Labels: backport

#231 [Docs]Adds 7.9.1 fixed bugs
  docs/release-notes.asciidoc
Labels: 7.9.1

#232 [7.x] [Docs]Adds 7.9.1 fixed bugs (#231)
  docs/release-notes.asciidoc
Labels: backport

#233 [7.9] [Docs]Adds 7.9.1 fixed bugs (#231)
  docs/release-notes.asciidoc
Labels: backport

#234 [Docs]fixes a couple of typos
  docs/detections/rules-ui-manage.asciidoc
  docs/getting-started/detections-req.asciidoc
Labels: 7.9

#235 [7.x] fixes a couple of typos (#234)
  docs/detections/rules-ui-manage.asciidoc
  docs/getting-started/detections-req.asciidoc
Labels: backport

#236 [7.9] fixes a couple of typos (#234)
  docs/detections/rules-ui-manage.asciidoc
  docs/getting-started/detections-req.asciidoc
Labels: backport

#237 [Docs]Adds list item value parsing
  docs/detections/api/lists/api-create-list-container.asciidoc
Labels: 7.9

#240 [7.x] [Docs]Adds list item value parsing (#237)
  docs/detections/api/lists/api-create-list-container.asciidoc
Labels: backport

#241 [7.9] [Docs]Adds list item value parsing (#237)
  docs/detections/api/lists/api-create-list-container.asciidoc
Labels: backport

#239 [7.9] Issue #226: Add Malware information to overview (#227)
  docs/detections/detection-engine-intro.asciidoc
  docs/es-overview.asciidoc
  docs/getting-started/images/install-endpoint/malware-protection.png
  docs/getting-started/install-endpoint.asciidoc
Labels: backport

#238 [7.x] Issue #226: Add Malware information to overview (#227)
  docs/detections/detection-engine-intro.asciidoc
  docs/es-overview.asciidoc
  docs/getting-started/images/install-endpoint/malware-protection.png
  docs/getting-started/install-endpoint.asciidoc
Labels: backport

#252 [7.9] Add default malware settings to install instruction (#243)
  docs/getting-started/images/install-endpoint/malware-protection.png
  docs/getting-started/install-endpoint.asciidoc
Labels: backport

#251 [7.x] Add default malware settings to install instruction (#243)
  docs/getting-started/images/install-endpoint/malware-protection.png
  docs/getting-started/install-endpoint.asciidoc
Labels: backport

#260 [7.9] Replace On-Prem with self-managed in Detections section (#255)
  docs/detections/detection-engine-intro.asciidoc
  docs/getting-started/detections-req.asciidoc
  docs/getting-started/sec-app-requirements.asciidoc
Labels: backport

#259 [7.x] Replace On-Prem with self-managed in Detections section (#255)
  docs/detections/detection-engine-intro.asciidoc
  docs/getting-started/detections-req.asciidoc
  docs/getting-started/sec-app-requirements.asciidoc
Labels: backport

#266 [7.x] [Docs]Adds prebuilt rule scripts (#265)
  prebuilt-rules-scripts/create-json-from-docs.py
  prebuilt-rules-scripts/create_documentation.py
  prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.8.0.json
  prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.9.0-new.json
  prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.9.0.json
  prebuilt-rules-scripts/get-rule-diff.py
  prebuilt-rules-scripts/orig-rules-json-files/7.6-prebuilt-rule.json
  prebuilt-rules-scripts/orig-rules-json-files/7.6.1-prebuilt-rule.json
  prebuilt-rules-scripts/orig-rules-json-files/7.6.2-prebuilt-rule.json
  prebuilt-rules-scripts/orig-rules-json-files/7.7.0-prebuilt-rule.json
  prebuilt-rules-scripts/orig-rules-json-files/7.8.0-prebuilt-rule.json
  prebuilt-rules-scripts/orig-rules-json-files/7.9.0-prebuilt-rule-new.json
  prebuilt-rules-scripts/orig-rules-json-files/7.9.0-prebuilt-rule.json
  prebuilt-rules-scripts/readme.md
  prebuilt-rules-scripts/update_current_text.py
Labels: backport

#268 [7.x] updates readme file (#267)
  prebuilt-rules-scripts/create_documentation.py
  prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.9.0-new.json
  prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.9.0.json
  prebuilt-rules-scripts/get-rule-diff.py
  prebuilt-rules-scripts/readme.md
Labels: backport
