Repository elastic/security-docs, pull requests merged in 2020-07, with the labels that each got.

#43 Change links to refactored Beats getting started docs
  docs/siem/installation.asciidoc
Labels: TEAM:Docs

#47 [7.x] Change links to refactored Beats getting started docs
  docs/siem/installation.asciidoc
Labels: TEAM:Docs, backport

#18 [Docs]Documents Timeline object schema
  docs/index.asciidoc
  docs/siem-apis.asciidoc
  docs/siem/detections/api/rules-api-export.asciidoc
  docs/siem/detections/machine-learning/machine-learning.asciidoc
  docs/siem/index.asciidoc
  docs/siem/reference/field-ref.asciidoc
  docs/siem/reference/images/timeline-object-ui.png
  docs/siem/reference/ref-index.asciidoc
  docs/siem/reference/ref-intro.asciidoc
  docs/siem/reference/timeline-schema.asciidoc
  docs/siem/timeline/api/timeline-api-export.asciidoc
  docs/siem/timeline/api/timeline-api-import.asciidoc
  docs/siem/timeline/api/timeline-api-index.asciidoc
  docs/siem/timeline/api/timeline-api-overview.asciidoc
Labels: 7.9

#49 [7.x] [Docs]Updates ToC API and Reference Sections (#18)
  docs/index.asciidoc
  docs/siem-apis.asciidoc
  docs/siem/detections/api/rules-api-export.asciidoc
  docs/siem/detections/machine-learning/machine-learning.asciidoc
  docs/siem/index.asciidoc
  docs/siem/reference/field-ref.asciidoc
  docs/siem/reference/images/timeline-object-ui.png
  docs/siem/reference/ref-index.asciidoc
  docs/siem/reference/ref-intro.asciidoc
  docs/siem/reference/timeline-schema.asciidoc
  docs/siem/timeline/api/timeline-api-export.asciidoc
  docs/siem/timeline/api/timeline-api-import.asciidoc
  docs/siem/timeline/api/timeline-api-index.asciidoc
  docs/siem/timeline/api/timeline-api-overview.asciidoc
Labels: backport

#50 [Docs]Adds timeline schema and API
  docs/siem/index.asciidoc
  docs/siem/reference/timeline-schema.asciidoc
  docs/siem/timeline/api/timeline-api-create.asciidoc
  docs/siem/timeline/api/timeline-api-import.asciidoc
  docs/siem/timeline/api/timeline-api-index.asciidoc
  docs/siem/timeline/api/timeline-api-overview.asciidoc
Labels: 7.9

#52 [7.x] [Docs]Adds timeline schema and API (#50)
  docs/siem/index.asciidoc
  docs/siem/reference/timeline-schema.asciidoc
  docs/siem/timeline/api/timeline-api-create.asciidoc
  docs/siem/timeline/api/timeline-api-import.asciidoc
  docs/siem/timeline/api/timeline-api-index.asciidoc
  docs/siem/timeline/api/timeline-api-overview.asciidoc
Labels: backport

#48 [DOCS] Updates location of machine learning source file
  docs/siem/detections/machine-learning/machine-learning.asciidoc
Labels: TEAM:Docs, v8.0.0

#55 [7.x][DOCS] Updates location of machine learning source file
  docs/siem/detections/machine-learning/machine-learning.asciidoc
Labels: backport

#70 [Docs]Updates detections API
  docs/siem/detections/api/rules-api-create.asciidoc
  docs/siem/detections/api/rules-api-update.asciidoc
  docs/siem/detections/api/signals-api-overview.asciidoc
Labels: 7.9

#74 [7.x] [Docs]Updates detections API (#70)
  docs/siem/detections/api/rules-api-create.asciidoc
  docs/siem/detections/api/rules-api-update.asciidoc
  docs/siem/detections/api/signals-api-overview.asciidoc
Labels: backport

#75 [7.9] [Docs]Updates detections API (#70)
  docs/siem/detections/api/rules-api-create.asciidoc
  docs/siem/detections/api/rules-api-update.asciidoc
  docs/siem/detections/api/signals-api-overview.asciidoc
Labels: backport

#64 [Docs][Cases]7.9 Cases updates
  docs/breaking-changes.asciidoc
  docs/index.asciidoc
  docs/siem/cases/api/actions-api/cases-actions-api-intro.asciidoc
  docs/siem/cases/api/cases-api/cases-api-create.asciidoc
  docs/siem/cases/cases-overview.asciidoc
  docs/siem/cases/cases-ui-integrations.asciidoc
  docs/siem/cases/images/cases-ui-connector.png
  docs/siem/cases/images/cases-ui-home.png
  docs/siem/cases/images/cases-ui-open.png
  docs/siem/cases/images/cases-ui-sn-connector.png
  docs/siem/detections/machine-learning/machine-learning.asciidoc
  docs/siem/images/cases-ui-home.png
Labels: 7.9

#82 [7.x] [Docs][Cases]7.9 Cases updates (#64)
  docs/breaking-changes.asciidoc
  docs/index.asciidoc
  docs/siem/cases/api/actions-api/cases-actions-api-intro.asciidoc
  docs/siem/cases/api/cases-api/cases-api-create.asciidoc
  docs/siem/cases/cases-overview.asciidoc
  docs/siem/cases/cases-ui-integrations.asciidoc
  docs/siem/cases/images/cases-ui-connector.png
  docs/siem/cases/images/cases-ui-home.png
  docs/siem/cases/images/cases-ui-open.png
  docs/siem/cases/images/cases-ui-sn-connector.png
  docs/siem/images/cases-ui-home.png
Labels: backport

#83 [7.9] [Docs][Cases]7.9 Cases updates (#64)
  docs/breaking-changes.asciidoc
  docs/index.asciidoc
  docs/siem/cases/api/actions-api/cases-actions-api-intro.asciidoc
  docs/siem/cases/api/cases-api/cases-api-create.asciidoc
  docs/siem/cases/cases-overview.asciidoc
  docs/siem/cases/cases-ui-integrations.asciidoc
  docs/siem/cases/images/cases-ui-connector.png
  docs/siem/cases/images/cases-ui-home.png
  docs/siem/cases/images/cases-ui-open.png
  docs/siem/cases/images/cases-ui-sn-connector.png
  docs/siem/detections/machine-learning/machine-learning.asciidoc
  docs/siem/images/cases-ui-home.png
Labels: backport
