Repository elastic/security-docs, pull requests merged in 2021-09, with the labels that each got.

#987 [DOCS] 7.14.1 Release Notes
  docs/release-notes.asciidoc
Labels: Team:Docs, release-notes, v7.14.1

#1008 [7.15] [DOCS] 7.14.1 Release Notes (#987)
  docs/release-notes.asciidoc
Labels: backport, v7.15.0

#1009 [7.14] [DOCS] 7.14.1 Release Notes (#987)
  docs/release-notes.asciidoc
Labels: backport, v7.14.0

#1026 [DOCS] Update home page screenshot
  docs/getting-started/images/add-data.png
Labels: Team:Docs, v7.15.0

#1031 [7.x] [DOCS] Update home page screenshot (#1026)
  docs/getting-started/images/add-data.png
Labels: Team:Docs, backport, v8.0.0

#1032 [7.15] [DOCS] Update home page screenshot (#1026)
  docs/getting-started/images/add-data.png
Labels: backport

#1027 [DOCS] Add troubleshooting landing page
  docs/index.asciidoc
  docs/release-notes.asciidoc
  docs/troubleshooting/detections/detection-rules.asciidoc
  docs/troubleshooting/troubleshooting-intro.asciidoc
Labels: v7.15.0

#1015 [DOCS] Changes to the Threat Intel tab on the Alert Details pane
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/images/document-summary-section.png
  docs/detections/images/reason-section.png
  docs/detections/images/threat-intel-fields.png
  docs/detections/images/view-alert-details.png
Labels: Team:Docs, Team:CTI, v7.15.0, readyforQA

#1037 [7.x] [DOCS] Changes to the Threat Intel tab on the Alert Details pane (#1015)
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/images/document-summary-section.png
  docs/detections/images/reason-section.png
  docs/detections/images/threat-intel-fields.png
  docs/detections/images/view-alert-details.png
Labels: Team:Docs, backport, v8.0.0, Team:CTI

#1038 [7.15] [DOCS] Changes to the Threat Intel tab on the Alert Details pane (#1015)
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/images/document-summary-section.png
  docs/detections/images/reason-section.png
  docs/detections/images/threat-intel-fields.png
  docs/detections/images/view-alert-details.png
Labels: Team:Docs, backport, Team:CTI, v7.15.0

#1034 [DOCS ] Separate release notes files
  docs/release-notes.asciidoc
  docs/release-notes/7.10.asciidoc
  docs/release-notes/7.11.asciidoc
  docs/release-notes/7.12.asciidoc
  docs/release-notes/7.13.asciidoc
  docs/release-notes/7.14.asciidoc
  docs/release-notes/7.15.asciidoc
  docs/release-notes/7.9.asciidoc
Labels: v7.15.0, v7.16.0, v7.14.2

#1041 [7.15][DOCS ] Separate release notes files (#1034)
  docs/release-notes.asciidoc
  docs/release-notes/7.10.asciidoc
  docs/release-notes/7.11.asciidoc
  docs/release-notes/7.12.asciidoc
  docs/release-notes/7.13.asciidoc
  docs/release-notes/7.14.asciidoc
  docs/release-notes/7.15.asciidoc
  docs/release-notes/7.9.asciidoc
Labels: backport

#1042 [7.14][DOCS ] Separate release notes files #1034
  docs/release-notes.asciidoc
  docs/release-notes/7.10.asciidoc
  docs/release-notes/7.11.asciidoc
  docs/release-notes/7.12.asciidoc
  docs/release-notes/7.13.asciidoc
  docs/release-notes/7.14.asciidoc
  docs/release-notes/7.9.asciidoc
Labels: backport

#1039 [7.x] [DOCS] Add troubleshooting landing page (#1027)
  docs/index.asciidoc
  docs/troubleshooting/detections/detection-rules.asciidoc
  docs/troubleshooting/troubleshooting-intro.asciidoc
Labels: backport

#1036 Replace gsuite link with Google Workspace
  docs/detections/rules-ui-create.asciidoc
Labels: Team:Docs

#1040 [7.15] [DOCS] Add troubleshooting landing page (#1027)
  docs/index.asciidoc
  docs/troubleshooting/detections/detection-rules.asciidoc
  docs/troubleshooting/troubleshooting-intro.asciidoc
Labels: backport

#1025 [DOCS] Add more context to indicator match rule restrictions
  docs/detections/detection-engine-intro.asciidoc
Labels: Team:Docs, Team:CTI, v7.15.0

#1044 [7.x] Replace gsuite link with Google Workspace (#1036)
  docs/detections/rules-ui-create.asciidoc
Labels: backport

#1046 [7.14] Replace gsuite link with Google Workspace (#1036)
  docs/detections/rules-ui-create.asciidoc
Labels: backport

#1045 [7.15] Replace gsuite link with Google Workspace (#1036)
  docs/detections/rules-ui-create.asciidoc
Labels: backport

#1048 [7.15] [DOCS] Add more context to indicator match rule restrictions (#1025)
  docs/detections/detection-engine-intro.asciidoc
Labels: Team:Docs, backport, Team:CTI, v7.15.0

#1047 [7.x] [DOCS] Add more context to indicator match rule restrictions (#1025)
  docs/detections/detection-engine-intro.asciidoc
Labels: Team:Docs, backport, v8.0.0, Team:CTI

#1058 [7.15] Adds new post-upgrade section (#1056)
  docs/index.asciidoc
  docs/post-upgrade/post-upgrade-intro.asciidoc
  docs/post-upgrade/post-upgrade-req.asciidoc
  docs/post-upgrade/template-script.asciidoc
Labels: backport

#1057 [7.x] Adds new post-upgrade section (#1056)
  docs/index.asciidoc
  docs/post-upgrade/post-upgrade-intro.asciidoc
  docs/post-upgrade/post-upgrade-req.asciidoc
  docs/post-upgrade/template-script.asciidoc
Labels: backport

#1010 [DOCS] Manage Endpoint - UX Updates
  docs/getting-started/security-ui.asciidoc
  docs/management/admin/admin-pg-ov.asciidoc
  docs/management/admin/event-filters.asciidoc
  docs/management/admin/host-isolation-ov.asciidoc
  docs/management/admin/images/activity-log.png
  docs/management/admin/images/config-status.png
  docs/management/admin/images/endpoints-pg.png
  docs/management/admin/images/event-filter.png
  docs/management/admin/images/event-filters-list.png
  docs/management/admin/images/host-flyout.png
  docs/management/admin/images/integration-pg.png
  docs/management/admin/images/isolated-host.png
  docs/management/admin/images/trusted-apps-list.png
  docs/management/admin/trusted-apps.asciidoc
Labels: Team:Docs, v7.15.0, QA:Validated

#1064 [7.15] [DOCS] Manage Endpoint - UX Updates (#1010)
  docs/getting-started/security-ui.asciidoc
  docs/management/admin/admin-pg-ov.asciidoc
  docs/management/admin/event-filters.asciidoc
  docs/management/admin/host-isolation-ov.asciidoc
  docs/management/admin/images/activity-log.png
  docs/management/admin/images/config-status.png
  docs/management/admin/images/endpoints-pg.png
  docs/management/admin/images/event-filter.png
  docs/management/admin/images/event-filters-list.png
  docs/management/admin/images/host-flyout.png
  docs/management/admin/images/integration-pg.png
  docs/management/admin/images/isolated-host.png
  docs/management/admin/images/trusted-apps-list.png
  docs/management/admin/trusted-apps.asciidoc
Labels: backport

#1063 [7.x] [DOCS] Manage Endpoint - UX Updates (#1010)
  docs/getting-started/security-ui.asciidoc
  docs/management/admin/admin-pg-ov.asciidoc
  docs/management/admin/event-filters.asciidoc
  docs/management/admin/host-isolation-ov.asciidoc
  docs/management/admin/images/activity-log.png
  docs/management/admin/images/config-status.png
  docs/management/admin/images/endpoints-pg.png
  docs/management/admin/images/event-filter.png
  docs/management/admin/images/event-filters-list.png
  docs/management/admin/images/host-flyout.png
  docs/management/admin/images/integration-pg.png
  docs/management/admin/images/isolated-host.png
  docs/management/admin/images/trusted-apps-list.png
  docs/management/admin/trusted-apps.asciidoc
Labels: backport

#1043 [DOCS] Troubleshooting guide for Endpoint list when Transform stops running
  docs/troubleshooting/images/endpoints-transform-failed.png
  docs/troubleshooting/images/transforms-start.png
  docs/troubleshooting/management/ts-management.asciidoc
  docs/troubleshooting/troubleshooting-intro.asciidoc
Labels: Team:Docs, v7.15.0, QA:Validated

#1066 [7.x] [DOCS] Troubleshooting guide for Endpoint list when Transform stops running (#1043)
  docs/troubleshooting/images/endpoints-transform-failed.png
  docs/troubleshooting/images/transforms-start.png
  docs/troubleshooting/management/ts-management.asciidoc
  docs/troubleshooting/troubleshooting-intro.asciidoc
Labels: backport

#1067 [7.15] [DOCS] Troubleshooting guide for Endpoint list when Transform stops running (#1043)
  docs/troubleshooting/images/endpoints-transform-failed.png
  docs/troubleshooting/images/transforms-start.png
  docs/troubleshooting/management/ts-management.asciidoc
  docs/troubleshooting/troubleshooting-intro.asciidoc
Labels: backport

#1060 [DOCS] Release notes [7.14.2]
  docs/release-notes/7.14.asciidoc
Labels: Team:Docs, release-notes, v7.14.2

#1068 [7.x] [DOCS] Release notes [7.14.2] (#1060)
  docs/release-notes/7.14.asciidoc
Labels: backport

#1069 [7.15] [DOCS] Release notes [7.14.2] (#1060)
  docs/release-notes/7.14.asciidoc
Labels: backport

#1065 [DOCS] Clarify wildcard functionality within exception & value lists
  docs/detections/detections-ui-exceptions.asciidoc
Labels: Team:Docs, v7.15.0

#1071 [7.15] Add admonitions about wildcards (#1065)
  docs/detections/detections-ui-exceptions.asciidoc
Labels: backport

#1070 [7.x] Add admonitions about wildcards (#1065)
  docs/detections/detections-ui-exceptions.asciidoc
Labels: backport

#1075 [7.x] [DOCS] Memory Manipulation and Behavior Protection - Policy (#994)
  docs/getting-started/images/install-endpoint/behavior-protection.png
  docs/getting-started/images/install-endpoint/memory-protection.png
  docs/getting-started/install-endpoint.asciidoc
Labels: backport

#1054 [DOCS] Document Linux OS support for host isolation
  docs/management/admin/host-isolation-ov.asciidoc
Labels: Team:Docs, v7.15.0, QA:Validated

#1078 [7.15] [DOCS] Document Linux OS support for host isolation (#1054)
  docs/management/admin/host-isolation-ov.asciidoc
Labels: backport

#1077 [7.x] [DOCS] Document Linux OS support for host isolation (#1054)
  docs/management/admin/host-isolation-ov.asciidoc
Labels: backport

#1061 [DOCS]Old row action showing under timeline for Elastic Security Solution doc
  docs/events/images/correlation-tab-eql-query.png
  docs/events/images/timeline-ui-renderer.png
  docs/events/images/timeline-ui-updated.png
  docs/getting-started/images/timeline-accessiblity-directional-arrows.gif
  docs/getting-started/images/timeline-accessiblity-event-renderer.gif
  docs/getting-started/images/timeline-accessiblity-event-renderers.gif
  docs/getting-started/images/timeline-accessiblity-keyboard-focus-hotkeys.gif
  docs/getting-started/images/timeline-accessiblity-keyboard-focus.gif
  docs/getting-started/images/timeline-accessiblity-page-up-n-down.gif
  docs/getting-started/images/timeline-accessiblity-shift-keyboard-focus.gif
  docs/getting-started/images/timeline-accessiblity-shifting-keyboard-focus.gif
  docs/getting-started/images/timeline-accessiblity-tab-key.gif
  docs/getting-started/images/timeline-accessiblity-tab-keys.gif
  docs/getting-started/images/timeline-ui-accessiblity-drag-n-drop.gif
  docs/getting-started/security-ui.asciidoc
Labels: Team:Docs, v7.15.0, QA:Validated

#1079 [7.x] [DOCS]Old row action showing under timeline for Elastic Security Solution doc (#1061)
  docs/events/images/correlation-tab-eql-query.png
  docs/events/images/timeline-ui-renderer.png
  docs/events/images/timeline-ui-updated.png
  docs/getting-started/images/timeline-accessiblity-directional-arrows.gif
  docs/getting-started/images/timeline-accessiblity-event-renderer.gif
  docs/getting-started/images/timeline-accessiblity-event-renderers.gif
  docs/getting-started/images/timeline-accessiblity-keyboard-focus-hotkeys.gif
  docs/getting-started/images/timeline-accessiblity-keyboard-focus.gif
  docs/getting-started/images/timeline-accessiblity-page-up-n-down.gif
  docs/getting-started/images/timeline-accessiblity-shift-keyboard-focus.gif
  docs/getting-started/images/timeline-accessiblity-shifting-keyboard-focus.gif
  docs/getting-started/images/timeline-accessiblity-tab-key.gif
  docs/getting-started/images/timeline-accessiblity-tab-keys.gif
  docs/getting-started/images/timeline-ui-accessiblity-drag-n-drop.gif
  docs/getting-started/security-ui.asciidoc
Labels: backport

#1080 [7.15] [DOCS]Old row action showing under timeline for Elastic Security Solution doc (#1061)
  docs/events/images/correlation-tab-eql-query.png
  docs/events/images/timeline-ui-renderer.png
  docs/events/images/timeline-ui-updated.png
  docs/getting-started/images/timeline-accessiblity-directional-arrows.gif
  docs/getting-started/images/timeline-accessiblity-event-renderer.gif
  docs/getting-started/images/timeline-accessiblity-event-renderers.gif
  docs/getting-started/images/timeline-accessiblity-keyboard-focus-hotkeys.gif
  docs/getting-started/images/timeline-accessiblity-keyboard-focus.gif
  docs/getting-started/images/timeline-accessiblity-page-up-n-down.gif
  docs/getting-started/images/timeline-accessiblity-shift-keyboard-focus.gif
  docs/getting-started/images/timeline-accessiblity-shifting-keyboard-focus.gif
  docs/getting-started/images/timeline-accessiblity-tab-key.gif
  docs/getting-started/images/timeline-accessiblity-tab-keys.gif
  docs/getting-started/images/timeline-ui-accessiblity-drag-n-drop.gif
  docs/getting-started/security-ui.asciidoc
Labels: backport

#1035 [DOCS] Migrating Enriched CTI Alerts
  docs/post-upgrade-req-cti-alerts
  docs/post-upgrade/post-upgrade-intro.asciidoc
  docs/post-upgrade/post-upgrade-req-cti-alerts.asciidoc
  docs/post-upgrade/post-upgrade-req.asciidoc
  docs/post-upgrade/template-script.asciidoc
Labels: Team:Docs, Team:CTI, v7.15.0, QA:Validated

#1083 [7.x] [DOCS] Migrating Enriched CTI Alerts (#1035)
  docs/post-upgrade-req-cti-alerts
  docs/post-upgrade/post-upgrade-intro.asciidoc
  docs/post-upgrade/post-upgrade-req-cti-alerts.asciidoc
  docs/post-upgrade/post-upgrade-req.asciidoc
  docs/post-upgrade/template-script.asciidoc
Labels: backport

#1082 [BUG] Update description for 1102 in the 7.15 RN
  docs/post-upgrade/post-upgrade-req-cti-alerts.asciidoc
  docs/release-notes/7.15.asciidoc
Labels: bug, Team:Docs, release-notes, Team:CTI, v7.15.0

#1089 [7.x] [BUG] Update description for 1102 in the 7.15 RN (#1082)
  docs/post-upgrade/post-upgrade-req-cti-alerts.asciidoc
  docs/release-notes/7.15.asciidoc
Labels: backport

#1091 [DOCS] Remove [beta] instances in Analyze Event docs
  docs/detections/images/event-details.png
  docs/detections/images/event-type.png
  docs/detections/images/full-screen-analyzer.png
  docs/detections/images/graphical-view.png
  docs/detections/images/node-legend.png
  docs/detections/images/process-details.png
  docs/detections/images/process-list.png
  docs/detections/images/process-schema.png
Labels: Team:Docs, Team:Threat Hunting, v7.15.0

#1092 [7.x] [DOCS] Remove [beta] instances in Analyze Event docs (#1091)
  docs/detections/images/event-details.png
  docs/detections/images/event-type.png
  docs/detections/images/full-screen-analyzer.png
  docs/detections/images/graphical-view.png
  docs/detections/images/node-legend.png
  docs/detections/images/process-details.png
  docs/detections/images/process-list.png
  docs/detections/images/process-schema.png
Labels: backport

#1093 [7.15] [DOCS] Remove [beta] instances in Analyze Event docs (#1091)
  docs/detections/images/event-details.png
  docs/detections/images/event-type.png
  docs/detections/images/full-screen-analyzer.png
  docs/detections/images/graphical-view.png
  docs/detections/images/node-legend.png
  docs/detections/images/process-details.png
  docs/detections/images/process-list.png
  docs/detections/images/process-schema.png
Labels: backport

#1090 Add query for finding outdated alerts with CTI data
  docs/detections/api/signals-migration-api.asciidoc
Labels: Team:Docs, Team:CTI, v7.15.0

#1097 [7.15] Add query for finding outdated alerts with CTI data (#1090)
  docs/detections/api/signals-migration-api.asciidoc
Labels: backport

#1096 [7.x] Add query for finding outdated alerts with CTI data (#1090)
  docs/detections/api/signals-migration-api.asciidoc
Labels: backport

#1028 [DOCS] Alerts table updates (RAC)
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/detection-engine-intro.asciidoc
  docs/detections/images/add-alert-to-case.gif
  docs/detections/images/add-alert-to-existing-case.png
  docs/detections/images/add-alert-to-new-case.png
  docs/detections/images/additional-filters.png
  docs/detections/images/alert-change-status.gif
  docs/detections/images/alert-page.png
  docs/detections/images/alert-table-toolbar-buttons.png
  docs/detections/images/analyze-event-view.png
  docs/detections/images/analyze-event.gif
  docs/detections/images/event-rendered-view.png
  docs/detections/images/kql-agent-type.png
  docs/detections/images/table-view-options.png
  docs/detections/images/timeline-button.png
  docs/detections/machine-learning/images/ml-ui.png
  docs/detections/visual-event-analyzer.asciidoc
  docs/getting-started/security-ui.asciidoc
Labels: Team:Docs, v7.15.0, QA:Validated

#1101 [7.15] [DOCS] Alerts table updates (RAC) (#1028)
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/detection-engine-intro.asciidoc
  docs/detections/images/add-alert-to-case.gif
  docs/detections/images/add-alert-to-existing-case.png
  docs/detections/images/add-alert-to-new-case.png
  docs/detections/images/additional-filters.png
  docs/detections/images/alert-change-status.gif
  docs/detections/images/alert-page.png
  docs/detections/images/alert-table-toolbar-buttons.png
  docs/detections/images/analyze-event-view.png
  docs/detections/images/analyze-event.gif
  docs/detections/images/event-rendered-view.png
  docs/detections/images/kql-agent-type.png
  docs/detections/images/table-view-options.png
  docs/detections/images/timeline-button.png
  docs/detections/machine-learning/images/ml-ui.png
  docs/detections/visual-event-analyzer.asciidoc
  docs/getting-started/security-ui.asciidoc
Labels: backport

#1100 [7.x] [DOCS] Alerts table updates (RAC) (#1028)
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/detection-engine-intro.asciidoc
  docs/detections/images/add-alert-to-case.gif
  docs/detections/images/add-alert-to-existing-case.png
  docs/detections/images/add-alert-to-new-case.png
  docs/detections/images/additional-filters.png
  docs/detections/images/alert-change-status.gif
  docs/detections/images/alert-page.png
  docs/detections/images/alert-table-toolbar-buttons.png
  docs/detections/images/analyze-event-view.png
  docs/detections/images/analyze-event.gif
  docs/detections/images/event-rendered-view.png
  docs/detections/images/kql-agent-type.png
  docs/detections/images/table-view-options.png
  docs/detections/images/timeline-button.png
  docs/detections/machine-learning/images/ml-ui.png
  docs/detections/visual-event-analyzer.asciidoc
  docs/getting-started/security-ui.asciidoc
Labels: backport

#1095 [DOCS] Update screenshots in the Timeline template instructions
  docs/events/images/create-a-timeline-filter.png
  docs/events/images/create-template-ui.png
  docs/events/timeline-templates.asciidoc
Labels: Team:Docs, Team:Threat Hunting, v7.15.0

#1104 [7.x] [DOCS] Update screenshots in the Timeline template instructions (#1095)
  docs/events/images/create-a-timeline-filter.png
  docs/events/images/create-template-ui.png
  docs/events/timeline-templates.asciidoc
Labels: backport

#1105 [7.15] [DOCS] Update screenshots in the Timeline template instructions (#1095)
  docs/events/images/create-a-timeline-filter.png
  docs/events/images/create-template-ui.png
  docs/events/timeline-templates.asciidoc
Labels: backport

#1106 [7.x] Clarify admin access to Trusted Applications page (#1062)
  docs/management/admin/trusted-apps.asciidoc
Labels: backport

#1107 [7.15] Clarify admin access to Trusted Applications page (#1062)
  docs/management/admin/trusted-apps.asciidoc
Labels: backport

#1072 [DOCS] Clarify multi-tenancy behavior of rules being isolated per space
  docs/getting-started/index.asciidoc
  docs/getting-started/security-spaces.asciidoc
Labels: Team:Docs, v7.15.0

#1113 [7.x] [DOCS] Clarify multi-tenancy behavior of rules being isolated per space (#1072)
  docs/getting-started/index.asciidoc
  docs/getting-started/security-spaces.asciidoc
Labels: backport

#1114 [7.15] [DOCS] Clarify multi-tenancy behavior of rules being isolated per space (#1072)
  docs/getting-started/index.asciidoc
  docs/getting-started/security-spaces.asciidoc
Labels: backport

#1117 [7.x] [BUG] Revise 7.15 release notes: host isolation Linux version support (#1116)
  docs/release-notes/7.15.asciidoc
Labels: backport

#1118 [BUG] Old State in-progress mentioned in cell actions for Rule Exception in Elastic Doc
  docs/detections/images/more-action-button.png
Labels: bug, Team:Docs, Team:Detections/Response, v7.15.0

#1121 [7.x] [BUG] Old State in-progress mentioned in cell actions for Rule Exception in Elastic Doc (#1118)
  docs/detections/images/more-action-button.png
Labels: backport

#1122 [7.15] [BUG] Old State in-progress mentioned in cell actions for Rule Exception in Elastic Doc (#1118)
  docs/detections/images/more-action-button.png
Labels: backport
