Repository elastic/security-docs, pull requests merged in 2021-10, with the labels that each got.

#1123 [DOCS] Lens visualization missing in case details page
  docs/cases/images/cases-ui-open.png
Labels: bug, Team:Threat Hunting, v7.15.0, readyforQA

#1129 [7.15] [DOCS] Lens visualization missing in case details page (#1123)
  docs/cases/images/cases-ui-open.png
Labels: backport, v7.15.0

#1128 [7.x] [DOCS] Lens visualization missing in case details page (#1123)
  docs/cases/images/cases-ui-open.png
Labels: backport, v8.0.0

#1127 [BUG]Change "Email or Username" field to "Email address" for JIRA connector docs
  docs/cases/cases-ui-integrations.asciidoc
Labels: bug, Team:Docs, Team:Threat Hunting, v7.15.0

#1130 [7.x] [BUG]Change "Email or Username" field to "Email address" for JIRA connector docs (#1127)
  docs/cases/cases-ui-integrations.asciidoc
Labels: backport

#1131 [7.15] [BUG]Change "Email or Username" field to "Email address" for JIRA connector docs (#1127)
  docs/cases/cases-ui-integrations.asciidoc
Labels: backport

#1124 [DOCS] Clarify usage of field overrides with Threshold Rules
  docs/detections/rules-ui-create.asciidoc
Labels: Team:Docs, Team:Detections/Response, edit, v7.15.0

#1125 [DOCS] Clarify alert de-duplication logic around configured 'additional look-back time'
  docs/detections/rules-ui-create.asciidoc
  docs/detections/rules-ui-monitor.asciidoc
Labels: Team:Docs, Team:Detections/Response, edit, v7.15.0

#1134 [7.15] [DOCS] Clarify usage of field overrides with Threshold Rules (#1124)
  docs/detections/rules-ui-create.asciidoc
Labels: backport

#1133 [7.x] [DOCS] Clarify usage of field overrides with Threshold Rules (#1124)
  docs/detections/rules-ui-create.asciidoc
Labels: backport

#1136 [7.15] [DOCS] Clarify alert de-duplication logic around configured 'additional look-back time' (#1125)
  docs/detections/rules-ui-create.asciidoc
  docs/detections/rules-ui-monitor.asciidoc
Labels: backport

#1135 [7.x] [DOCS] Clarify alert de-duplication logic around configured 'additional look-back time' (#1125)
  docs/detections/rules-ui-create.asciidoc
  docs/detections/rules-ui-monitor.asciidoc
Labels: backport

#1138 [DOCS] Update detection-engine-intro.asciidoc (#1132)
  docs/detections/detection-engine-intro.asciidoc
Labels: backport

#1139 [DOCS] Update detection-engine-intro.asciidoc (#1132)
  docs/detections/detection-engine-intro.asciidoc
Labels: backport

#1143 [7.x] Fix relative links to images (#1141)
  docs/getting-started/security-ui.asciidoc
  docs/troubleshooting/management/ts-management.asciidoc
Labels: backport
