Repository elastic/security-docs, pull requests merged in 2021-05, with the labels that each got.

#667 Add 7.12.1 rules updates
  docs/detections/prebuilt-rules/prebuilt-rules-changelog.asciidoc
  docs/detections/prebuilt-rules/prebuilt-rules-reference.asciidoc
  docs/detections/prebuilt-rules/rule-details/adversary-behavior-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/anomalous-kernel-module-activity.asciidoc
  docs/detections/prebuilt-rules/rule-details/aws-iam-brute-force-of-assume-role-policy.asciidoc
  docs/detections/prebuilt-rules/rule-details/credential-dumping-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/credential-dumping-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/credential-manipulation-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/credential-manipulation-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/exploit-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/exploit-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/malware-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/malware-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/permission-theft-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/permission-theft-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/process-injection-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/process-injection-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/ransomware-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/ransomware-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-linux-network-connection-discovery.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-linux-process-discovery-activity.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-linux-system-information-discovery-activity.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-linux-system-network-configuration-discovery.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-linux-system-owner-or-user-discovery-activity.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-sudo-activity.asciidoc
  prebuilt-rules-scripts/changelog-entries.yml
  prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.12.1.json
  prebuilt-rules-scripts/diff-files/gen-files/json-from-docs-7.12.1.json
  prebuilt-rules-scripts/orig-rules-json-files/7.12.1-prebuilt-rule.json
Labels: TEAM:Docs, v7.12.1

#672 [7.x] Add 7.12.1 rules updates (#667)
  docs/detections/prebuilt-rules/prebuilt-rules-changelog.asciidoc
  docs/detections/prebuilt-rules/prebuilt-rules-reference.asciidoc
  docs/detections/prebuilt-rules/rule-details/adversary-behavior-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/anomalous-kernel-module-activity.asciidoc
  docs/detections/prebuilt-rules/rule-details/aws-iam-brute-force-of-assume-role-policy.asciidoc
  docs/detections/prebuilt-rules/rule-details/credential-dumping-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/credential-dumping-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/credential-manipulation-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/credential-manipulation-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/exploit-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/exploit-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/malware-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/malware-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/permission-theft-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/permission-theft-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/process-injection-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/process-injection-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/ransomware-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/ransomware-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-linux-network-connection-discovery.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-linux-process-discovery-activity.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-linux-system-information-discovery-activity.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-linux-system-network-configuration-discovery.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-linux-system-owner-or-user-discovery-activity.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-sudo-activity.asciidoc
  prebuilt-rules-scripts/changelog-entries.yml
  prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.12.1.json
  prebuilt-rules-scripts/diff-files/gen-files/json-from-docs-7.12.1.json
  prebuilt-rules-scripts/orig-rules-json-files/7.12.1-prebuilt-rule.json
Labels: backport

#673 [7.13] Add 7.12.1 rules updates (#667)
  docs/detections/prebuilt-rules/prebuilt-rules-changelog.asciidoc
  docs/detections/prebuilt-rules/prebuilt-rules-reference.asciidoc
  docs/detections/prebuilt-rules/rule-details/adversary-behavior-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/anomalous-kernel-module-activity.asciidoc
  docs/detections/prebuilt-rules/rule-details/aws-iam-brute-force-of-assume-role-policy.asciidoc
  docs/detections/prebuilt-rules/rule-details/credential-dumping-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/credential-dumping-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/credential-manipulation-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/credential-manipulation-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/exploit-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/exploit-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/malware-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/malware-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/permission-theft-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/permission-theft-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/process-injection-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/process-injection-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/ransomware-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/ransomware-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-linux-network-connection-discovery.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-linux-process-discovery-activity.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-linux-system-information-discovery-activity.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-linux-system-network-configuration-discovery.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-linux-system-owner-or-user-discovery-activity.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-sudo-activity.asciidoc
  prebuilt-rules-scripts/changelog-entries.yml
  prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.12.1.json
  prebuilt-rules-scripts/diff-files/gen-files/json-from-docs-7.12.1.json
  prebuilt-rules-scripts/orig-rules-json-files/7.12.1-prebuilt-rule.json
Labels: backport

#674 [7.12] Add 7.12.1 rules updates (#667)
  docs/detections/prebuilt-rules/prebuilt-rules-changelog.asciidoc
  docs/detections/prebuilt-rules/prebuilt-rules-reference.asciidoc
  docs/detections/prebuilt-rules/rule-details/adversary-behavior-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/anomalous-kernel-module-activity.asciidoc
  docs/detections/prebuilt-rules/rule-details/aws-iam-brute-force-of-assume-role-policy.asciidoc
  docs/detections/prebuilt-rules/rule-details/credential-dumping-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/credential-dumping-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/credential-manipulation-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/credential-manipulation-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/exploit-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/exploit-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/malware-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/malware-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/permission-theft-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/permission-theft-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/process-injection-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/process-injection-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/ransomware-detected-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/ransomware-prevented-elastic-endgame.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-linux-network-connection-discovery.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-linux-process-discovery-activity.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-linux-system-information-discovery-activity.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-linux-system-network-configuration-discovery.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-linux-system-owner-or-user-discovery-activity.asciidoc
  docs/detections/prebuilt-rules/rule-details/unusual-sudo-activity.asciidoc
  prebuilt-rules-scripts/changelog-entries.yml
  prebuilt-rules-scripts/diff-files/final-files/final-rule-file-7.12.1.json
  prebuilt-rules-scripts/diff-files/gen-files/json-from-docs-7.12.1.json
  prebuilt-rules-scripts/orig-rules-json-files/7.12.1-prebuilt-rule.json
Labels: backport

#677 [7.13] [DOCS] Exceptions updates 7.13 (#675)
  docs/detections/detections-ui-exceptions.asciidoc
Labels: backport

#681 [7.13] Add link to ingest data with Splunk (#679)
  docs/getting-started/ingest-data.asciidoc
Labels: backport

#680 [7.x] Add link to ingest data with Splunk (#679)
  docs/getting-started/ingest-data.asciidoc
Labels: backport

#668 [DOCS] Create rule API updates (7.13)
  docs/detections/api/rules/rules-api-create.asciidoc
Labels: API, v7.13.0

#688 [7.x] [DOCS] Create rule API updates (7.13) (#668)
  docs/detections/api/rules/rules-api-create.asciidoc
Labels: backport

#689 [7.13] [DOCS] Create rule API updates (7.13) (#668)
  docs/detections/api/rules/rules-api-create.asciidoc
Labels: backport

#678 Update timeline docs
  docs/events/api/timeline-api-create.asciidoc
  docs/events/api/timeline-api-delete.asciidoc
  docs/events/api/timeline-api-export.asciidoc
  docs/events/api/timeline-api-get.asciidoc
  docs/events/api/timeline-api-index.asciidoc
  docs/events/api/timeline-api-overview.asciidoc
  docs/events/api/timeline-api-update.asciidoc
Labels: v7.13.0

#690 [7.x] Update timeline docs (#678)
  docs/events/api/timeline-api-create.asciidoc
  docs/events/api/timeline-api-delete.asciidoc
  docs/events/api/timeline-api-export.asciidoc
  docs/events/api/timeline-api-get.asciidoc
  docs/events/api/timeline-api-index.asciidoc
  docs/events/api/timeline-api-overview.asciidoc
  docs/events/api/timeline-api-update.asciidoc
Labels: backport

#691 [7.13] Update timeline docs (#678)
  docs/events/api/timeline-api-create.asciidoc
  docs/events/api/timeline-api-delete.asciidoc
  docs/events/api/timeline-api-export.asciidoc
  docs/events/api/timeline-api-get.asciidoc
  docs/events/api/timeline-api-index.asciidoc
  docs/events/api/timeline-api-overview.asciidoc
  docs/events/api/timeline-api-update.asciidoc
Labels: backport

#693 [DOCS] Fleet and Endpoint Security require a Transform, appropriate configuration is needed
  docs/getting-started/sec-app-requirements.asciidoc
Labels: TEAM:Docs, v7.13.0

#699 [7.x] [DOCS] Fleet and Endpoint Security require a Transform, appropriate configuration is needed (#693)
  docs/getting-started/sec-app-requirements.asciidoc
Labels: backport, v8.0.0

#700 [7.13] [DOCS] Fleet and Endpoint Security require a Transform, appropriate configuration is needed (#693)
  docs/getting-started/sec-app-requirements.asciidoc
Labels: backport, v7.13.0

#666 [DOCS] Updating "Manage detection alerts" topic
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/images/additional-filters.png
  docs/detections/images/alert-table-columns-and-size.gif
  docs/detections/images/customize-event-renderer-page.png
  docs/detections/images/customize-event-renderer.png
  docs/detections/images/prebuilt-integration.png
  docs/detections/images/view-alert-details.png
  docs/events/images/test2.gif
  docs/getting-started/security-ui.asciidoc
Labels: TEAM:Docs, v7.13.0

#703 [7.x] [DOCS] Updating "Manage detection alerts" topic (#666)
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/images/additional-filters.png
  docs/detections/images/alert-table-columns-and-size.gif
  docs/detections/images/customize-event-renderer-page.png
  docs/detections/images/customize-event-renderer.png
  docs/detections/images/prebuilt-integration.png
  docs/detections/images/view-alert-details.png
  docs/events/images/test2.gif
  docs/getting-started/security-ui.asciidoc
Labels: TEAM:Docs, backport, v8.0.0

#704 [7.13] [DOCS] Updating "Manage detection alerts" topic (#666)
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/images/additional-filters.png
  docs/detections/images/alert-table-columns-and-size.gif
  docs/detections/images/customize-event-renderer-page.png
  docs/detections/images/customize-event-renderer.png
  docs/detections/images/prebuilt-integration.png
  docs/detections/images/view-alert-details.png
  docs/events/images/test2.gif
  docs/getting-started/security-ui.asciidoc
Labels: TEAM:Docs, backport, v7.13.0

#671 [DOCS] 7.13 release notes
  docs/release-notes.asciidoc
Labels: TEAM:Docs, release-notes, v7.13.0

#705 [7.x] [DOCS] 7.13 release notes (#671)
  docs/release-notes.asciidoc
Labels: TEAM:Docs, backport, v8.0.0

#706 [7.13] [DOCS] 7.13 release notes (#671)
  docs/release-notes.asciidoc
Labels: TEAM:Docs, backport, v7.13.0

#634 [DOCS] Privileges Matrix for Detections Feature
  docs/getting-started/detections-req.asciidoc
  docs/getting-started/images/sec-admin-user.png
Labels: TEAM:Docs, v7.13.0

#708 [7.13] [DOCS] Privileges Matrix for Detections Feature (#634)
  docs/getting-started/detections-req.asciidoc
  docs/getting-started/images/sec-admin-user.png
Labels: TEAM:Docs, backport, v7.13.0

#707 [7.x] [DOCS] Privileges Matrix for Detections Feature (#634)
  docs/getting-started/detections-req.asciidoc
  docs/getting-started/images/sec-admin-user.png
Labels: TEAM:Docs, backport, v7.13.0

#684 [DOCS] Create rule updates
  docs/detections/rules-ui-create.asciidoc
Labels: TEAM:Docs, v7.13.0

#712 [7.13] Endpoint/trusted app updates. (#701)
  docs/management/admin/admin-pg-ov.asciidoc
  docs/management/admin/images/admin-pg.png
  docs/management/admin/images/remove-entry.png
  docs/management/admin/images/trusted-apps-list.png
Labels: backport

#711 [7.x] Endpoint/trusted app updates. (#701)
  docs/management/admin/admin-pg-ov.asciidoc
  docs/management/admin/images/admin-pg.png
  docs/management/admin/images/remove-entry.png
  docs/management/admin/images/trusted-apps-list.png
Labels: backport

#710 [7.13] [DOCS] Fleet updates 7.13 (#695)
  docs/getting-started/install-endpoint.asciidoc
Labels: backport

#709 [7.x] [DOCS] Fleet updates 7.13 (#695)
  docs/getting-started/install-endpoint.asciidoc
Labels: backport

#716 [7.13] [DOCS] Create rule updates (#684)
  docs/detections/rules-ui-create.asciidoc
Labels: backport

#715 [7.x] [DOCS] Create rule updates (#684)
  docs/detections/rules-ui-create.asciidoc
Labels: backport

#714 [7.13] [DOCS] What's new in 7.13? (#702)
  docs/whats-new.asciidoc
Labels: backport

#713 [7.x] [DOCS] What's new in 7.13? (#702)
  docs/whats-new.asciidoc
Labels: backport

#722 [7.13] Moving prebuilt rules update to the correct topic. (#720)
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/rules-ui-manage.asciidoc
Labels: backport

#721 [7.x] Moving prebuilt rules update to the correct topic. (#720)
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/rules-ui-manage.asciidoc
Labels: backport

#723 Remove "Copy as curl" and "View in console" links from examples
  docs/getting-started/install-endpoint.asciidoc
Labels: TEAM:Docs

#725 [7.x] Remove copy as curl and run in console links (#723)
  docs/getting-started/install-endpoint.asciidoc
Labels: backport

#726 [7.13] Remove copy as curl and run in console links (#723)
  docs/getting-started/install-endpoint.asciidoc
Labels: backport
