Repository elastic/security-docs, pull requests merged in 2021-08, with the labels that each got.

#863 [7.14] [DOCS] Event filters (7.14) (#837)
  docs/getting-started/index.asciidoc
  docs/management/admin/event-filters.asciidoc
  docs/management/admin/images/event-filter.png
  docs/management/admin/images/event-filters-list.png
Labels: backport

#862 [7.x] [DOCS] Event filters (7.14) (#837)
  docs/getting-started/index.asciidoc
  docs/management/admin/event-filters.asciidoc
  docs/management/admin/images/event-filter.png
  docs/management/admin/images/event-filters-list.png
Labels: backport

#823 [DOCS] Security Navigation changes
  docs/detections/building-block-rule.asciidoc
  docs/detections/detections-ui-exceptions.asciidoc
  docs/detections/images/actions-exception-list.png
  docs/detections/images/exception-histogram.png
  docs/detections/images/exception-list.png
  docs/detections/machine-learning/images/ml-ui.png
  docs/detections/machine-learning/machine-learning.asciidoc
  docs/detections/prebuilt-rules/images/rule-details-page.png
  docs/detections/prebuilt-rules/tune-rule-signals.asciidoc
  docs/detections/rules-ui-manage.asciidoc
  docs/getting-started/images/install-endpoint/add-agent.png
  docs/getting-started/images/install-endpoint/add-elastic-endpoint-security.png
  docs/getting-started/images/install-endpoint/endpoint-configuration.png
  docs/getting-started/images/install-endpoint/endpoints-enrolling.png
  docs/getting-started/images/install-endpoint/malware-protection.png
  docs/getting-started/images/install-endpoint/security-integration.png
  docs/getting-started/images/network-ui.png
  docs/getting-started/install-endpoint.asciidoc
  docs/getting-started/network-page-overview.asciidoc
  docs/getting-started/sec-app-requirements.asciidoc
Labels: Feature: New Navigation, TEAM:Docs, v7.14.0

#867 [7.14] [DOCS] Security Navigation changes (#823)
  docs/detections/building-block-rule.asciidoc
  docs/detections/detections-ui-exceptions.asciidoc
  docs/detections/images/actions-exception-list.png
  docs/detections/images/exception-histogram.png
  docs/detections/images/exception-list.png
  docs/detections/machine-learning/images/ml-ui.png
  docs/detections/machine-learning/machine-learning.asciidoc
  docs/detections/prebuilt-rules/images/rule-details-page.png
  docs/detections/prebuilt-rules/tune-rule-signals.asciidoc
  docs/detections/rules-ui-manage.asciidoc
  docs/getting-started/images/install-endpoint/add-agent.png
  docs/getting-started/images/install-endpoint/add-elastic-endpoint-security.png
  docs/getting-started/images/install-endpoint/endpoint-configuration.png
  docs/getting-started/images/install-endpoint/endpoints-enrolling.png
  docs/getting-started/images/install-endpoint/malware-protection.png
  docs/getting-started/images/install-endpoint/security-integration.png
  docs/getting-started/images/network-ui.png
  docs/getting-started/install-endpoint.asciidoc
  docs/getting-started/network-page-overview.asciidoc
  docs/getting-started/sec-app-requirements.asciidoc
Labels: backport

#866 [7.x] [DOCS] Security Navigation changes (#823)
  docs/detections/building-block-rule.asciidoc
  docs/detections/detections-ui-exceptions.asciidoc
  docs/detections/images/actions-exception-list.png
  docs/detections/images/exception-histogram.png
  docs/detections/images/exception-list.png
  docs/detections/machine-learning/images/ml-ui.png
  docs/detections/machine-learning/machine-learning.asciidoc
  docs/detections/prebuilt-rules/images/rule-details-page.png
  docs/detections/prebuilt-rules/tune-rule-signals.asciidoc
  docs/detections/rules-ui-manage.asciidoc
  docs/getting-started/images/install-endpoint/add-agent.png
  docs/getting-started/images/install-endpoint/add-elastic-endpoint-security.png
  docs/getting-started/images/install-endpoint/endpoint-configuration.png
  docs/getting-started/images/install-endpoint/endpoints-enrolling.png
  docs/getting-started/images/install-endpoint/malware-protection.png
  docs/getting-started/images/install-endpoint/security-integration.png
  docs/getting-started/images/network-ui.png
  docs/getting-started/install-endpoint.asciidoc
  docs/getting-started/network-page-overview.asciidoc
  docs/getting-started/sec-app-requirements.asciidoc
Labels: backport

#811 [DOCS] 7.14.0 Release Notes
  docs/release-notes.asciidoc
Labels: TEAM:Docs, release-notes, v7.14.0

#868 [7.x] [DOCS] 7.14.0 Release Notes (#811)
  docs/release-notes.asciidoc
Labels: backport

#869 [7.14] [DOCS] 7.14.0 Release Notes (#811)
  docs/release-notes.asciidoc
Labels: backport

#861 [DOCS] Navigation updates
  docs/es-overview.asciidoc
  docs/getting-started/index.asciidoc
  docs/getting-started/sensor-full-disk-access.asciidoc
Labels: Feature: New Navigation, v7.14.0

#871 [7.14] Committing - nav changes. (#861)
  docs/es-overview.asciidoc
  docs/getting-started/index.asciidoc
  docs/getting-started/sensor-full-disk-access.asciidoc
Labels: backport

#870 [7.x] Committing - nav changes. (#861)
  docs/es-overview.asciidoc
  docs/getting-started/index.asciidoc
  docs/getting-started/sensor-full-disk-access.asciidoc
Labels: backport

#836 [DOCS] Update UI Overview
  docs/getting-started/images/cases-ui-home.png
  docs/getting-started/images/collapse-side-nav-button.gif
  docs/getting-started/images/detections-ui.png
  docs/getting-started/images/endpoints-page.png
  docs/getting-started/images/event-filters-page.png
  docs/getting-started/images/events-count.png
  docs/getting-started/images/exceptions-page.png
  docs/getting-started/images/hosts-pg.png
  docs/getting-started/images/live-feed-ov-page.png
  docs/getting-started/images/network-ui.png
  docs/getting-started/images/overview-pg.png
  docs/getting-started/images/rules-page.png
  docs/getting-started/images/search-bar.png
  docs/getting-started/images/timeline-accessiblity-directional-arrows.gif
  docs/getting-started/images/timeline-accessiblity-event-renderer.gif
  docs/getting-started/images/timeline-accessiblity-keyboard-focus-hotkeys.gif
  docs/getting-started/images/timeline-accessiblity-keyboard-focus.gif
  docs/getting-started/images/timeline-accessiblity-page-up-and-down.gif
  docs/getting-started/images/timeline-accessiblity-shift-keyboard-focus.gif
  docs/getting-started/images/timeline-accessiblity-tab-key.gif
  docs/getting-started/images/timeline-ui-accessiblity-drag-and-drop.gif
  docs/getting-started/images/timeline-ui.png
  docs/getting-started/images/trusted-apps-page.png
  docs/getting-started/security-ui.asciidoc
Labels: TEAM:Docs, major, v7.14.0

#874 [7.x] [DOCS] Update UI Overview (#836)
  docs/getting-started/images/cases-ui-home.png
  docs/getting-started/images/collapse-side-nav-button.gif
  docs/getting-started/images/detections-ui.png
  docs/getting-started/images/endpoints-page.png
  docs/getting-started/images/event-filters-page.png
  docs/getting-started/images/events-count.png
  docs/getting-started/images/exceptions-page.png
  docs/getting-started/images/hosts-pg.png
  docs/getting-started/images/live-feed-ov-page.png
  docs/getting-started/images/network-ui.png
  docs/getting-started/images/overview-pg.png
  docs/getting-started/images/rules-page.png
  docs/getting-started/images/search-bar.png
  docs/getting-started/images/timeline-accessiblity-directional-arrows.gif
  docs/getting-started/images/timeline-accessiblity-event-renderer.gif
  docs/getting-started/images/timeline-accessiblity-keyboard-focus-hotkeys.gif
  docs/getting-started/images/timeline-accessiblity-keyboard-focus.gif
  docs/getting-started/images/timeline-accessiblity-page-up-and-down.gif
  docs/getting-started/images/timeline-accessiblity-shift-keyboard-focus.gif
  docs/getting-started/images/timeline-accessiblity-tab-key.gif
  docs/getting-started/images/timeline-ui-accessiblity-drag-and-drop.gif
  docs/getting-started/images/timeline-ui.png
  docs/getting-started/images/trusted-apps-page.png
  docs/getting-started/security-ui.asciidoc
Labels: backport

#875 [7.14] [DOCS] Update UI Overview (#836)
  docs/getting-started/images/cases-ui-home.png
  docs/getting-started/images/collapse-side-nav-button.gif
  docs/getting-started/images/detections-ui.png
  docs/getting-started/images/endpoints-page.png
  docs/getting-started/images/event-filters-page.png
  docs/getting-started/images/events-count.png
  docs/getting-started/images/exceptions-page.png
  docs/getting-started/images/hosts-pg.png
  docs/getting-started/images/live-feed-ov-page.png
  docs/getting-started/images/network-ui.png
  docs/getting-started/images/overview-pg.png
  docs/getting-started/images/rules-page.png
  docs/getting-started/images/search-bar.png
  docs/getting-started/images/timeline-accessiblity-directional-arrows.gif
  docs/getting-started/images/timeline-accessiblity-event-renderer.gif
  docs/getting-started/images/timeline-accessiblity-keyboard-focus-hotkeys.gif
  docs/getting-started/images/timeline-accessiblity-keyboard-focus.gif
  docs/getting-started/images/timeline-accessiblity-page-up-and-down.gif
  docs/getting-started/images/timeline-accessiblity-shift-keyboard-focus.gif
  docs/getting-started/images/timeline-accessiblity-tab-key.gif
  docs/getting-started/images/timeline-ui-accessiblity-drag-and-drop.gif
  docs/getting-started/images/timeline-ui.png
  docs/getting-started/images/trusted-apps-page.png
  docs/getting-started/security-ui.asciidoc
Labels: backport

#877 [7.x] [DOCS] What's new in 7.14 (#873)
  docs/whats-new.asciidoc
Labels: backport

#878 [7.14] [DOCS] What's new in 7.14 (#873)
  docs/whats-new.asciidoc
Labels: backport

#879 [DOCS] Add "Security update" section to 7.14 RN
  docs/release-notes.asciidoc
Labels: TEAM:Docs, release-notes, v7.14.0

#872 Link siem-apis.asciidoc to the new Fleet api docs page
  docs/siem-apis.asciidoc
Labels: v7.14.0, v7.15.0, v8.0.0

#884 [7.14][DOCS] Add links to other versions of Whats New
  docs/whats-new.asciidoc
Labels: v7.14.1

#887 [7.x][DOCS] Add links to other versions of Whats New
  docs/whats-new.asciidoc
Labels: backport

#891 [7.14] [DOCS] TOC revision (7.14) (#876)
  docs/cases/cases-index.asciidoc
  docs/events/index.asciidoc
  docs/getting-started/explore-intro.asciidoc
  docs/getting-started/index.asciidoc
  docs/getting-started/security-ui.asciidoc
  docs/index.asciidoc
  docs/management/admin/admin-pg-ov.asciidoc
  docs/management/manage-intro.asciidoc
Labels: backport

#890 [7.x] [DOCS] TOC revision (7.14) (#876)
  docs/cases/cases-index.asciidoc
  docs/events/index.asciidoc
  docs/getting-started/explore-intro.asciidoc
  docs/getting-started/index.asciidoc
  docs/getting-started/security-ui.asciidoc
  docs/index.asciidoc
  docs/management/admin/admin-pg-ov.asciidoc
  docs/management/manage-intro.asciidoc
Labels: backport

#885 [7.x] Link siem-apis.asciidoc to the new Fleet api docs page (#872)
  docs/siem-apis.asciidoc
Labels: backport

#886 [7.14] Link siem-apis.asciidoc to the new Fleet api docs page (#872)
  docs/siem-apis.asciidoc
Labels: backport

#882 [7.x] Adds security update section. (#879)
  docs/release-notes.asciidoc
Labels: backport, v7.14.0

#883 [7.14] Adds security update section. (#879)
  docs/release-notes.asciidoc
Labels: backport, v7.14.0

#889 [BUG] Detection Rule execution authorization model not outlined in security docs
  docs/detections/rules-ui-create.asciidoc
  docs/getting-started/detections-req.asciidoc
Labels: bug, TEAM:Docs, v7.14.0

#913 [7.14] [BUG] Detection Rule execution authorization model not outlined in security docs (#889)
  docs/detections/rules-ui-create.asciidoc
  docs/getting-started/detections-req.asciidoc
Labels: backport, v7.14.0

#912 [7.x] [BUG] Detection Rule execution authorization model not outlined in security docs (#889)
  docs/detections/rules-ui-create.asciidoc
  docs/getting-started/detections-req.asciidoc
Labels: backport, v8.0

#881 [BUG] Update reported bugs
  docs/detections/rules-ui-create.asciidoc
Labels: bug, TEAM:Docs, v7.14.0

#915 [7.x] [BUG] Update reported bugs (#881)
  docs/detections/rules-ui-create.asciidoc
Labels: backport

#916 [7.14] [BUG] Update reported bugs (#881)
  docs/detections/rules-ui-create.asciidoc
Labels: backport

#914 [BUG] Incorrect reference of Trusted App under Event Filter Section Doc
  docs/getting-started/security-ui.asciidoc
Labels: bug, Team:Docs, v7.14.0

#920 [7.14] Updated section title and incorrect x-ref. (#914)
  docs/getting-started/security-ui.asciidoc
Labels: bug, Team:Docs, backport, v7.14.0

#919 [7.x] Updated section title and incorrect x-ref. (#914)
  docs/getting-started/security-ui.asciidoc
Labels: Team:Docs, backport, v8.0.0

#921 [BUG] Round Closing bracket missing for under Create Case Doc
  docs/cases/api/cases-api/cases-api-create.asciidoc
Labels: bug, Team:Docs, v7.14.0, readyforQA

#928 [7.14] Fixed table issue. (#921)
  docs/cases/api/cases-api/cases-api-create.asciidoc
Labels: bug, Team:Docs, backport, v7.14.0

#927 [7.x] Fixed table issue. (#921)
  docs/cases/api/cases-api/cases-api-create.asciidoc
Labels: bug, Team:Docs, backport, v8.0.0

#929 Remove beta tag from install-endpoint.asciidoc
  docs/getting-started/install-endpoint.asciidoc
Labels: bug, Team:Docs, v7.14.0

#931 [7.14] Remove beta tag from install-endpoint.asciidoc (#929)
  docs/getting-started/install-endpoint.asciidoc
Labels: backport, v7.14.0

#930 [7.x] Remove beta tag from install-endpoint.asciidoc (#929)
  docs/getting-started/install-endpoint.asciidoc
Labels: backport, v8.0.0

#922 [BUG] New Security Navigation not present under Verify Elastic Endpoint Enrollment Doc Section
  docs/getting-started/install-endpoint.asciidoc
Labels: bug, Team:Docs, v7.14.0, readyforQA

#934 [7.14] Remove section for verifying enrollment (#922)
  docs/getting-started/install-endpoint.asciidoc
Labels: backport, v7.14.0

#933 [7.x] Remove section for verifying enrollment (#922)
  docs/getting-started/install-endpoint.asciidoc
Labels: backport, v8.0.0

#923 [BUG] Old screenshot is displaying for Home page
  docs/getting-started/images/add-data.png
  docs/getting-started/ingest-data.asciidoc
Labels: bug, Team:Docs, v7.14.0, readyforQA

#937 [7.14] [BUG] Old screenshot is displaying for Home page (#923)
  docs/getting-started/images/add-data.png
  docs/getting-started/ingest-data.asciidoc
Labels: backport

#936 [7.x] [BUG] Old screenshot is displaying for Home page (#923)
  docs/getting-started/images/add-data.png
  docs/getting-started/ingest-data.asciidoc
Labels: backport

#935 [DOCS] Update release notes for master 8.0
  docs/release-notes.asciidoc
Labels: v8.0.0, release-notes

#917 [BUG] Comment is mentioned to be overwritten however expected it to be append under Swimlane mapping doc
  docs/cases/cases-ui-integrations.asciidoc
Labels: bug, Team:Docs, v7.14.0, readyforQA

#940 [7.14] [BUG] Comment is mentioned to be overwritten however expected it to be append under Swimlane mapping doc (#917)
  docs/cases/cases-ui-integrations.asciidoc
Labels: bug, Team:Docs, backport, v7.14.0

#939 [7.x] [BUG] Comment is mentioned to be overwritten however expected it to be append under Swimlane mapping doc (#917)
  docs/cases/cases-ui-integrations.asciidoc
Labels: bug, Team:Docs, backport, v7.14.0

#938 [BUG] Updates to Manage detection rules
  docs/detections/rules-ui-manage.asciidoc
Labels: Team:Detections/Response, readyforQA

#941 [7.x] Updates to Manage detection rules (#938)
  docs/detections/rules-ui-manage.asciidoc
Labels: backport

#942 [7.14] Updates to Manage detection rules (#938)
  docs/detections/rules-ui-manage.asciidoc
Labels: backport

#925 [BUG] Incorrect Service Now Mapping to Comment Field under ServiceNow mapping doc
  docs/cases/cases-ui-integrations.asciidoc
Labels: bug, Team:Docs, v7.14.0, readyforQA

#945 [7.14] Fixed error for SN field. (#925)
  docs/cases/cases-ui-integrations.asciidoc
Labels: bug, Team:Docs, backport, v7.14.0

#944 [7.x] Fixed error for SN field. (#925)
  docs/cases/cases-ui-integrations.asciidoc
Labels: bug, Team:Docs, backport, v8.0.0

#918 [BUG] Breadcrumb information not matching with the case name under Cases doc
  docs/cases/images/cases-ui-open.png
Labels: bug, Team:Docs, v7.14.0, readyforQA

#946 [7.x] Updating image. (#918)
  docs/cases/images/cases-ui-open.png
Labels: bug, Team:Docs, backport, v7.14.0

#947 [7.14] Updating image. (#918)
  docs/cases/images/cases-ui-open.png
Labels: bug, Team:Docs, backport, v7.14.0

#950 [BUG] Host isolation fix
  docs/management/admin/host-isolation-ov.asciidoc
  docs/management/admin/images/activity-log.png
Labels: Team:OLM, readyforQA

#953 [BUG] Error in step 1 of procedures for configuring basic rule settings
  docs/detections/rules-ui-create.asciidoc
Labels: bug, Team:Docs, v7.14.0

#959 [7.12] [BUG] Error in step 1 of procedures for configuring basic rule settings (#953)
  docs/detections/rules-ui-create.asciidoc
Labels: backport

#958 [7.13] [BUG] Error in step 1 of procedures for configuring basic rule settings (#953)
  docs/detections/rules-ui-create.asciidoc
Labels: backport

#957 [7.14] [BUG] Error in step 1 of procedures for configuring basic rule settings (#953)
  docs/detections/rules-ui-create.asciidoc
Labels: backport

#956 [7.x] [BUG] Error in step 1 of procedures for configuring basic rule settings (#953)
  docs/detections/rules-ui-create.asciidoc
Labels: backport, v8.0.0

#948 [BUG] Update Hosts page for new navigation UI
  docs/management/hosts/hosts-overview.asciidoc
  docs/management/hosts/images/drop-to-timeline.png
  docs/management/hosts/images/hosts-detail-pg.png
  docs/management/hosts/images/hosts-ov-pg.png
  docs/management/hosts/images/inline-actions.png
Labels: bug, Team:Docs, v7.14.0, readyforQA

#955 [7.14] Host isolation fix (#950)
  docs/management/admin/host-isolation-ov.asciidoc
  docs/management/admin/images/activity-log.png
Labels: backport

#954 [7.x] Host isolation fix (#950)
  docs/management/admin/host-isolation-ov.asciidoc
  docs/management/admin/images/activity-log.png
Labels: backport

#943 [BUG]Export option missing for Timeline and Template All action
  docs/events/images/all-actions-timeline-ui.png
  docs/events/timeline-templates.asciidoc
  docs/events/timeline-ui-overview.asciidoc
Labels: bug, Team:Docs, v7.14.0, readyforQA

#960 [7.x] [BUG] Update Hosts page for new navigation UI (#948)
  docs/management/hosts/hosts-overview.asciidoc
  docs/management/hosts/images/drop-to-timeline.png
  docs/management/hosts/images/hosts-detail-pg.png
  docs/management/hosts/images/hosts-ov-pg.png
  docs/management/hosts/images/inline-actions.png
Labels: backport, v8.0.0

#961 [7.14] [BUG] Update Hosts page for new navigation UI (#948)
  docs/management/hosts/hosts-overview.asciidoc
  docs/management/hosts/images/drop-to-timeline.png
  docs/management/hosts/images/hosts-detail-pg.png
  docs/management/hosts/images/hosts-ov-pg.png
  docs/management/hosts/images/inline-actions.png
Labels: backport, v7.14.0

#963 [7.14] [BUG]Export option missing for Timeline and Template All action (#943)
  docs/events/images/all-actions-timeline-ui.png
  docs/events/timeline-templates.asciidoc
  docs/events/timeline-ui-overview.asciidoc
Labels: backport, v7.14.0

#962 [7.x] [BUG]Export option missing for Timeline and Template All action (#943)
  docs/events/images/all-actions-timeline-ui.png
  docs/events/timeline-templates.asciidoc
  docs/events/timeline-ui-overview.asciidoc
Labels: backport, v8.0.0

#926 [BUG] Alert Page under 7.14.0 Doc is showing future changes of 7.15.0 under Elastic Security UI Doc
  docs/getting-started/images/detections-ui.png
Labels: bug, Team:Docs, v7.14.0, readyforQA, QA:Validated

#965 [7.x] Updating detections-ui.png (#926)
  docs/getting-started/images/detections-ui.png
Labels: backport, v7.14.0

#966 [7.14] Updating detections-ui.png (#926)
  docs/getting-started/images/detections-ui.png
Labels: backport, v7.14.0

#880 [BUG] Incorrect Type of value list name are displayed in value list
  docs/detections/detections-ui-exceptions.asciidoc
Labels: bug, Team:Docs, v7.14.0, readyforQA

#968 [7.14] [BUG] Incorrect Type of value list name are displayed in value list (#880)
  docs/detections/detections-ui-exceptions.asciidoc
Labels: backport

#967 [7.x] [BUG] Incorrect Type of value list name are displayed in value list (#880)
  docs/detections/detections-ui-exceptions.asciidoc
Labels: backport, v8.0.0

#952 [DOCS] Add _bulk_action API route documentation
  docs/detections/api/rules/rules-api-bulk-actions.asciidoc
Labels: Team:Docs, v7.15.0

#971 [7.x] [DOCS] Add _bulk_action API route documentation (#952)
  docs/detections/api/rules/rules-api-bulk-actions.asciidoc
Labels: backport

#973 [7.14] [DOCS] Add _bulk_action API route documentation (#952)
  docs/detections/api/rules/rules-api-bulk-actions.asciidoc
Labels: backport

#972 [7.15] [DOCS] Add _bulk_action API route documentation (#952)
  docs/detections/api/rules/rules-api-bulk-actions.asciidoc
Labels: backport

#976 [7.14] [DOCS] Release note cleanup (#974)
  docs/release-notes.asciidoc
Labels: backport

#975 [7.15] [DOCS] Release note cleanup (#974)
  docs/release-notes.asciidoc
Labels: backport

#981 [7.14] bulk_action API update (#978)
  docs/detections/api/rules/rules-api-bulk-actions.asciidoc
Labels: backport

#980 [7.15] bulk_action API update (#978)
  docs/detections/api/rules/rules-api-bulk-actions.asciidoc
Labels: backport

#979 [7.x] bulk_action API update (#978)
  docs/detections/api/rules/rules-api-bulk-actions.asciidoc
Labels: backport

#970 [DOCS] Expand Rule Monitoring docs with links to Alerting Monitoring resources
  docs/detections/images/monitor-table.png
  docs/detections/rules-ui-monitor.asciidoc
Labels: Team:Docs, v7.15.0

#985 [7.14] [DOCS] Expand Rule Monitoring docs with links to Alerting Monitoring resources (#970)
  docs/detections/images/monitor-table.png
  docs/detections/rules-ui-monitor.asciidoc
Labels: backport

#984 [7.15] [DOCS] Expand Rule Monitoring docs with links to Alerting Monitoring resources (#970)
  docs/detections/images/monitor-table.png
  docs/detections/rules-ui-monitor.asciidoc
Labels: backport

#983 [7.x] [DOCS] Expand Rule Monitoring docs with links to Alerting Monitoring resources (#970)
  docs/detections/images/monitor-table.png
  docs/detections/rules-ui-monitor.asciidoc
Labels: backport

#989 [BUG] Update Trusted Applications list screenshot
  docs/management/admin/images/trusted-apps-list.png
Labels: bug, Team:Docs, v7.14.0, readyforQA

#996 [7.x] Update trusted-apps-list.png (#989)
  docs/management/admin/images/trusted-apps-list.png
Labels: backport

#997 [7.15] Update trusted-apps-list.png (#989)
  docs/management/admin/images/trusted-apps-list.png
Labels: backport

#998 [7.14] Update trusted-apps-list.png (#989)
  docs/management/admin/images/trusted-apps-list.png
Labels: backport

#993 [DOCS] Document new securitySolution:defaultThreatIndex advanced setting
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/rules-ui-create.asciidoc
  docs/getting-started/advanced-setting.asciidoc
  docs/getting-started/images/adv-settings.png
  docs/getting-started/security-ui.asciidoc
Labels: Team:Docs, Team:CTI, v7.14.1

#999 [7.x] [DOCS] Document new securitySolution:defaultThreatIndex advanced setting (#993)
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/rules-ui-create.asciidoc
  docs/getting-started/advanced-setting.asciidoc
  docs/getting-started/images/adv-settings.png
  docs/getting-started/security-ui.asciidoc
Labels: backport, v8.0.0

#1000 [7.15] [DOCS] Document new securitySolution:defaultThreatIndex advanced setting (#993)
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/rules-ui-create.asciidoc
  docs/getting-started/advanced-setting.asciidoc
  docs/getting-started/images/adv-settings.png
  docs/getting-started/security-ui.asciidoc
Labels: backport, v7.15.0

#1001 [7.14] [DOCS] Document new securitySolution:defaultThreatIndex advanced setting (#993)
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/rules-ui-create.asciidoc
  docs/getting-started/advanced-setting.asciidoc
  docs/getting-started/images/adv-settings.png
  docs/getting-started/security-ui.asciidoc
Labels: backport, v7.14.0

#1004 [BUG] Remove mention that CSS is supported for the defaultThreatIndex setting and update note about CCS for IM rules
  docs/detections/detection-engine-intro.asciidoc
  docs/getting-started/advanced-setting.asciidoc
Labels: bug, Team:Docs, Team:CTI, v7.14.1

#1005 [7.x] [BUG] Remove mention that CSS is supported for the defaultThreatIndex setting and update note about CCS for IM rules (#1004)
  docs/detections/detection-engine-intro.asciidoc
  docs/getting-started/advanced-setting.asciidoc
Labels: backport, v8.0.0

#1006 [7.15] [BUG] Remove mention that CSS is supported for the defaultThreatIndex setting and update note about CCS for IM rules (#1004)
  docs/detections/detection-engine-intro.asciidoc
  docs/getting-started/advanced-setting.asciidoc
Labels: backport, v7.15.0

#1007 [7.14] [BUG] Remove mention that CSS is supported for the defaultThreatIndex setting and update note about CCS for IM rules (#1004)
  docs/detections/detection-engine-intro.asciidoc
  docs/getting-started/advanced-setting.asciidoc
Labels: backport, v7.14.0
