Repository elastic/security-docs, pull requests merged in 2021-11, with the labels that each got.

#1198 [BUG] Fixes ref to analyze event feature
  docs/post-upgrade-req-cti-alerts
  docs/post-upgrade/post-upgrade-req.asciidoc
Labels: v8.0.0, v7.14.0, v7.15.0, v7.16.0

#1205 [7.14] Small formatting and internal ref fixes. (#1198)
  docs/post-upgrade-req.asciidoc
Labels: backport

#1206 [DOCS] Alerts table updates (7.15.2)
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/images/additional-filters.png
  docs/detections/images/alert-table-toolbar-buttons.png
Labels: v8.0.0, v7.15.0, v7.16.0, v7.15.2

#1187 [DOCS]7.15.2 Release Notes
  docs/release-notes/7.15.asciidoc
Labels: release-notes, v7.15.0, v7.16.0

#1214 [BUG] Update to "Duplicate all prebuilt rules" section
  docs/detections/rules-ui-manage.asciidoc
Labels: bug, v8.0.0, v7.15.0, v7.16.0

#1160 Provide more details on how to start ML job to avoid ML detection rule execution failure
  docs/detections/images/rule-start-ml-job.png
  docs/detections/rules-ui-create.asciidoc
  docs/troubleshooting/detections/detection-rules.asciidoc
  docs/troubleshooting/images/rules-ts-ml-job-stopped.png
  docs/troubleshooting/images/rules-ts-start-ml-job.png
Labels: Team:Docs, v8.0.0, Team:Detections/Response, v7.14.0, edit, v7.15.0, v7.16.0

#1222 [7.14] Provide more details on how to start ML job to avoid ML detection rule execution failure (#1160)
  docs/detections/images/rule-start-ml-job.png
  docs/detections/rules-ui-create.asciidoc
  docs/index.asciidoc
  docs/troubleshooting/detections/detection-rules.asciidoc
  docs/troubleshooting/images/rules-ts-ml-job-stopped.png
  docs/troubleshooting/images/rules-ts-start-ml-job.png
  docs/troubleshooting/troubleshooting-intro.asciidoc
Labels: backport

#1227 [DOCS] Add new endpoint management APIs
  docs/management/api/get-endpoint-api.asciidoc
  docs/management/api/host-isolation-api.asciidoc
  docs/management/api/list-endpoints-api.asciidoc
  docs/management/api/management-api-index.asciidoc
  docs/management/api/remove-isolated-host-api.asciidoc
  docs/siem-apis.asciidoc
Labels: v8.0.0, v7.15.0, v7.16.0

#1244 Update link to docs about adding a Fleet Server
  docs/getting-started/install-endpoint.asciidoc
Labels: v8.0.0, v7.16.0, v7.x

#1199 [DOCS] Doc steps to exporting and importing cases
  docs/cases/cases-overview.asciidoc
  docs/cases/images/cases-export-button.png
  docs/cases/images/cases-open-vis.png
Labels: Team:Docs, v8.0.0, Team:Threat Hunting, readyforQA, v7.16.0

#1190 [DOCS] Host Isolation Exceptions - IP Allowlist
  docs/getting-started/security-ui.asciidoc
  docs/management/admin/host-isolation-exceptions.asciidoc
  docs/management/admin/host-isolation-ov.asciidoc
  docs/management/admin/images/host-isolation-exceptions-ui.png
  docs/management/manage-intro.asciidoc
Labels: Team:Docs, v8.0.0, Team:OLM, QA:Validated, v7.16.0
