Repository elastic/security-docs, pull requests merged in 2021-07, with the labels that each got.

#782 [DOCS] Fixes links to anomaly detection overview
  docs/detections/machine-learning/machine-learning.asciidoc
Labels: v8.0.0

#784 [DOCS] 7.13.3 Release Notes
  docs/release-notes.asciidoc
Labels: 7.13.3, TEAM:Docs, release-notes

#789 [7.14] [DOCS] 7.13.3 Release Notes (#784)
  docs/release-notes.asciidoc
Labels: TEAM:Docs, backport, release-notes, v7.14.0

#788 [7.x] [DOCS] 7.13.3 Release Notes (#784)
  docs/release-notes.asciidoc
Labels: TEAM:Docs, backport, release-notes, v8.0.0

#790 [7.13] [DOCS] 7.13.3 Release Notes (#784)
  docs/release-notes.asciidoc
Labels: 7.13.3, TEAM:Docs, backport, release-notes

#793 Add docs for 0.13.2 rules integration package
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-attempts-to-brute-force-a-microsoft-365-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-ec2-full-network-packet-capture-detected.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-ec2-vm-export-failure.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-rds-instance-creation.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-rds-security-group-creation.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-rds-security-group-deletion.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-rds-snapshot-export.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-route-53-domain-transfer-lock-disabled.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-route-53-domain-transferred-to-another-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-azure-service-principal-credentials-added.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-disabling-windows-defender-security-settings-via-powershell.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-enable-host-network-discovery-via-netsh.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-persistence-via-folder-action-script.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-potential-dll-side-loading-via-microsoft-antimalware-service-executable.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-potential-password-spraying-of-microsoft-365-user-accounts.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-potential-printnightmare-exploit-registry-modification.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-potential-printnightmare-file-modification.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-shell-execution-via-apple-scripting.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-smb-windows-file-sharing-activity-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-suspicious-print-spooler-file-deletion.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-unusual-print-spooler-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rules-0-13-2-appendix.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rules-0-13-2-summary.asciidoc
  docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
  docs/index.asciidoc
Labels: v7.13.0

#794 [7.13] Add docs for 0.13.2 rules integration package (#793)
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-attempts-to-brute-force-a-microsoft-365-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-ec2-full-network-packet-capture-detected.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-ec2-vm-export-failure.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-rds-instance-creation.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-rds-security-group-creation.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-rds-security-group-deletion.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-rds-snapshot-export.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-route-53-domain-transfer-lock-disabled.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-route-53-domain-transferred-to-another-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-azure-service-principal-credentials-added.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-disabling-windows-defender-security-settings-via-powershell.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-enable-host-network-discovery-via-netsh.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-persistence-via-folder-action-script.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-potential-dll-side-loading-via-microsoft-antimalware-service-executable.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-potential-password-spraying-of-microsoft-365-user-accounts.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-potential-printnightmare-exploit-registry-modification.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-potential-printnightmare-file-modification.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-shell-execution-via-apple-scripting.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-smb-windows-file-sharing-activity-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-suspicious-print-spooler-file-deletion.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-unusual-print-spooler-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rules-0-13-2-appendix.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rules-0-13-2-summary.asciidoc
  docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
  docs/index.asciidoc
Labels: backport

#799 [Detection rules] Add release note to 0.13.2 summary
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rules-0-13-2-summary.asciidoc
Labels: TEAM:Docs, v7.13.0

#800 [7.13] Update prebuilt-rules-0-13-2-summary.asciidoc (#799)
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rules-0-13-2-summary.asciidoc
Labels: backport

#801 [DOCS] Fixes link to ML custom rules
  docs/detections/machine-learning/tune-anomaly-results.asciidoc
Labels: v8.0.0

#803 [7.x] Add docs for 0.13.1 fleet rules package (#769)
  docs/detections/detections-index.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-anomalous-process-for-a-linux-population.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-anomalous-process-for-a-windows-population.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-anomalous-windows-process-creation.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-apple-script-execution-followed-by-network-connection.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-attempts-to-brute-force-a-microsoft-365-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-attempts-to-brute-force-an-okta-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-aws-ec2-vm-export-failure.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-command-prompt-network-connection.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-component-object-model-hijacking.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-connection-to-external-network-via-telnet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-connection-to-internal-network-via-telnet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-dns-activity-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-high-number-of-okta-user-password-reset-or-unlock-attempts.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-macos-installer-spawns-network-event.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-modification-of-amsienable-registry-key.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-network-connection-via-certutil.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-network-connection-via-compiled-html-file.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-network-connection-via-msxsl.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-network-connection-via-registration-utility.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-network-connection-via-signed-binary.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-network-traffic-to-rare-destination-country.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-rdp-remote-desktop-protocol-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-roshal-archive-rar-or-powershell-file-downloaded-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-rpc-remote-procedure-call-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-rpc-remote-procedure-call-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-spike-in-firewall-denies.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-spike-in-network-traffic-to-a-country.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-spike-in-network-traffic.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-suspicious-dll-loaded-for-persistence-or-privilege-escalation.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-suspicious-execution-from-a-mounted-device.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-linux-network-port-activity.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-linux-process-calling-the-metadata-service.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-linux-user-calling-the-metadata-service.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-linux-username.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-network-connection-via-dllhost.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-network-connection-via-rundll32.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-process-for-a-linux-host.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-process-for-a-windows-host.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-windows-network-activity.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-windows-path-activity.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-windows-process-calling-the-metadata-service.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-windows-user-calling-the-metadata-service.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-windows-username.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-vnc-virtual-network-computing-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-vnc-virtual-network-computing-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rules-0-13-1-appendix.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rules-0-13-1-summary.asciidoc
  docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
  docs/index.asciidoc
Labels: backport

#804 [7.14] Add docs for 0.13.1 fleet rules package (#769)
  docs/detections/detections-index.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-anomalous-process-for-a-linux-population.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-anomalous-process-for-a-windows-population.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-anomalous-windows-process-creation.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-apple-script-execution-followed-by-network-connection.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-attempts-to-brute-force-a-microsoft-365-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-attempts-to-brute-force-an-okta-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-aws-ec2-vm-export-failure.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-command-prompt-network-connection.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-component-object-model-hijacking.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-connection-to-external-network-via-telnet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-connection-to-internal-network-via-telnet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-dns-activity-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-high-number-of-okta-user-password-reset-or-unlock-attempts.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-macos-installer-spawns-network-event.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-modification-of-amsienable-registry-key.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-network-connection-via-certutil.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-network-connection-via-compiled-html-file.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-network-connection-via-msxsl.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-network-connection-via-registration-utility.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-network-connection-via-signed-binary.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-network-traffic-to-rare-destination-country.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-rdp-remote-desktop-protocol-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-roshal-archive-rar-or-powershell-file-downloaded-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-rpc-remote-procedure-call-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-rpc-remote-procedure-call-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-spike-in-firewall-denies.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-spike-in-network-traffic-to-a-country.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-spike-in-network-traffic.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-suspicious-dll-loaded-for-persistence-or-privilege-escalation.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-suspicious-execution-from-a-mounted-device.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-linux-network-port-activity.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-linux-process-calling-the-metadata-service.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-linux-user-calling-the-metadata-service.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-linux-username.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-network-connection-via-dllhost.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-network-connection-via-rundll32.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-process-for-a-linux-host.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-process-for-a-windows-host.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-windows-network-activity.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-windows-path-activity.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-windows-process-calling-the-metadata-service.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-windows-user-calling-the-metadata-service.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-unusual-windows-username.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-vnc-virtual-network-computing-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rule-0-13-1-vnc-virtual-network-computing-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rules-0-13-1-appendix.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-1/prebuilt-rules-0-13-1-summary.asciidoc
  docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
  docs/index.asciidoc
Labels: backport

#805 [7.x] Update prebuilt-rules-0-13-2-summary.asciidoc (#799)
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rules-0-13-2-summary.asciidoc
Labels: backport

#806 [7.14] Update prebuilt-rules-0-13-2-summary.asciidoc (#799)
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rules-0-13-2-summary.asciidoc
Labels: backport

#796 [7.14] Add docs for 0.13.2 rules integration package (#793)
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-attempts-to-brute-force-a-microsoft-365-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-ec2-full-network-packet-capture-detected.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-ec2-vm-export-failure.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-rds-instance-creation.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-rds-security-group-creation.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-rds-security-group-deletion.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-rds-snapshot-export.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-route-53-domain-transfer-lock-disabled.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-route-53-domain-transferred-to-another-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-azure-service-principal-credentials-added.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-disabling-windows-defender-security-settings-via-powershell.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-enable-host-network-discovery-via-netsh.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-persistence-via-folder-action-script.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-potential-dll-side-loading-via-microsoft-antimalware-service-executable.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-potential-password-spraying-of-microsoft-365-user-accounts.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-potential-printnightmare-exploit-registry-modification.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-potential-printnightmare-file-modification.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-shell-execution-via-apple-scripting.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-smb-windows-file-sharing-activity-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-suspicious-print-spooler-file-deletion.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-unusual-print-spooler-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rules-0-13-2-appendix.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rules-0-13-2-summary.asciidoc
  docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
  docs/index.asciidoc
Labels: backport

#807 [7.x] Add docs for 0.13.2 rules integration package (#793)
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-attempts-to-brute-force-a-microsoft-365-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-ec2-full-network-packet-capture-detected.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-ec2-vm-export-failure.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-rds-instance-creation.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-rds-security-group-creation.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-rds-security-group-deletion.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-rds-snapshot-export.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-route-53-domain-transfer-lock-disabled.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-aws-route-53-domain-transferred-to-another-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-azure-service-principal-credentials-added.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-disabling-windows-defender-security-settings-via-powershell.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-enable-host-network-discovery-via-netsh.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-persistence-via-folder-action-script.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-potential-dll-side-loading-via-microsoft-antimalware-service-executable.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-potential-password-spraying-of-microsoft-365-user-accounts.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-potential-printnightmare-exploit-registry-modification.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-potential-printnightmare-file-modification.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-shell-execution-via-apple-scripting.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-smb-windows-file-sharing-activity-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-suspicious-print-spooler-file-deletion.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rule-0-13-2-unusual-print-spooler-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rules-0-13-2-appendix.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-2/prebuilt-rules-0-13-2-summary.asciidoc
  docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
  docs/index.asciidoc
Labels: backport

#817 [DOCS] Correct typos in Investigate events page (index.asciidoc)
  docs/events/index.asciidoc
Labels: bug

#820 [7.13] Correct typos in index.asciidoc (#817)
  docs/events/index.asciidoc
Labels: backport

#819 [7.14] Correct typos in index.asciidoc (#817)
  docs/events/index.asciidoc
Labels: backport

#818 [7.x] Correct typos in index.asciidoc (#817)
  docs/events/index.asciidoc
Labels: backport

#841 [7.x] Endpoints/Trusted Applications updates (#810)
  docs/getting-started/index.asciidoc
  docs/management/admin/admin-pg-ov.asciidoc
  docs/management/admin/images/endpoints-pg.png
  docs/management/admin/images/filter-endpoints.png
  docs/management/admin/images/host-flyout.png
  docs/management/admin/images/integration-pg.png
  docs/management/admin/images/trusted-apps-list.png
  docs/management/admin/trusted-apps.asciidoc
Labels: backport

#842 [7.14] Endpoints/Trusted Applications updates (#810)
  docs/getting-started/index.asciidoc
  docs/management/admin/admin-pg-ov.asciidoc
  docs/management/admin/images/endpoints-pg.png
  docs/management/admin/images/filter-endpoints.png
  docs/management/admin/images/host-flyout.png
  docs/management/admin/images/integration-pg.png
  docs/management/admin/images/trusted-apps-list.png
  docs/management/admin/trusted-apps.asciidoc
Labels: backport

#824 [Security solution] [Endpoint] Adds documentation for exceptions container summary
  docs/detections/api/exceptions-api-index.asciidoc
  docs/detections/api/exceptions/api-summary-exception-container.asciidoc
Labels: v7.14.0

#843 [7.x] [Security solution] [Endpoint] Adds documentation for exceptions container summary (#824)
  docs/detections/api/exceptions-api-index.asciidoc
  docs/detections/api/exceptions/api-summary-exception-container.asciidoc
Labels: backport

#844 [7.14] [Security solution] [Endpoint] Adds documentation for exceptions container summary (#824)
  docs/detections/api/exceptions-api-index.asciidoc
  docs/detections/api/exceptions/api-summary-exception-container.asciidoc
Labels: backport

#833 [Detection Rules] Add rule updates for 0.13.3 package
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-cobalt-strike-command-and-control-beacon.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-default-cobalt-strike-team-server-certificate.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-disable-windows-event-and-security-logs-using-built-in-tools.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-dns-activity-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-execution-of-file-written-or-modified-by-microsoft-office.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-execution-of-file-written-or-modified-by-pdf-reader.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-external-alerts.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-external-ip-lookup-fron-non-browser-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-mfa-enforcement-disabled.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-password-policy-modified.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-halfbaked-command-and-control-beacon.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-inbound-connection-to-an-unsecure-elasticsearch-node.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-ipsec-nat-traversal-port-activity.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-mfa-disabled-for-google-workspace-organization.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-mshta-making-network-connections.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-o365-excessive-single-sign-on-logon-errors.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-parent-process-pid-spoofing.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-possible-fin7-dga-command-and-control-behavior.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-rare-aws-error-code.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-rdp-remote-desktop-protocol-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-roshal-archive-rar-or-powershell-file-downloaded-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-rpc-remote-procedure-call-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-rpc-remote-procedure-call-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-smb-windows-file-sharing-activity-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-smtp-on-port-26-tcp.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-spike-in-aws-error-messages.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-suspicious-certutil-commands.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-telnet-port-activity.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-unusual-aws-command-for-a-user.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-unusual-child-processes-of-rundll32.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-unusual-city-for-an-aws-command.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-unusual-country-for-an-aws-command.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-unusual-print-spooler-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-vnc-virtual-network-computing-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-vnc-virtual-network-computing-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-web-application-suspicious-activity-no-user-agent.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-web-application-suspicious-activity-post-request-declined.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-web-application-suspicious-activity-sqlmap-user-agent.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-web-application-suspicious-activity-unauthorized-method.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-windows-defender-exclusions-added-via-powershell.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rules-0-13-3-appendix.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rules-0-13-3-summary.asciidoc
  docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
  docs/index.asciidoc
Labels: TEAM:Docs, Team:Detections/Response

#848 [7.13] [Detection Rules] Add rule updates for 0.13.3 package (#833)
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-cobalt-strike-command-and-control-beacon.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-default-cobalt-strike-team-server-certificate.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-disable-windows-event-and-security-logs-using-built-in-tools.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-dns-activity-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-execution-of-file-written-or-modified-by-microsoft-office.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-execution-of-file-written-or-modified-by-pdf-reader.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-external-alerts.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-external-ip-lookup-fron-non-browser-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-mfa-enforcement-disabled.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-password-policy-modified.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-halfbaked-command-and-control-beacon.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-inbound-connection-to-an-unsecure-elasticsearch-node.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-ipsec-nat-traversal-port-activity.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-mfa-disabled-for-google-workspace-organization.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-mshta-making-network-connections.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-o365-excessive-single-sign-on-logon-errors.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-parent-process-pid-spoofing.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-possible-fin7-dga-command-and-control-behavior.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-rare-aws-error-code.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-rdp-remote-desktop-protocol-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-roshal-archive-rar-or-powershell-file-downloaded-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-rpc-remote-procedure-call-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-rpc-remote-procedure-call-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-smb-windows-file-sharing-activity-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-smtp-on-port-26-tcp.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-spike-in-aws-error-messages.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-suspicious-certutil-commands.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-telnet-port-activity.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-unusual-aws-command-for-a-user.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-unusual-child-processes-of-rundll32.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-unusual-city-for-an-aws-command.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-unusual-country-for-an-aws-command.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-unusual-print-spooler-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-vnc-virtual-network-computing-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-vnc-virtual-network-computing-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-web-application-suspicious-activity-no-user-agent.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-web-application-suspicious-activity-post-request-declined.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-web-application-suspicious-activity-sqlmap-user-agent.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-web-application-suspicious-activity-unauthorized-method.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-windows-defender-exclusions-added-via-powershell.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rules-0-13-3-appendix.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rules-0-13-3-summary.asciidoc
  docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
  docs/index.asciidoc
Labels: backport

#847 [7.14] [Detection Rules] Add rule updates for 0.13.3 package (#833)
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-cobalt-strike-command-and-control-beacon.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-default-cobalt-strike-team-server-certificate.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-disable-windows-event-and-security-logs-using-built-in-tools.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-dns-activity-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-execution-of-file-written-or-modified-by-microsoft-office.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-execution-of-file-written-or-modified-by-pdf-reader.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-external-alerts.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-external-ip-lookup-fron-non-browser-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-mfa-enforcement-disabled.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-password-policy-modified.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-halfbaked-command-and-control-beacon.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-inbound-connection-to-an-unsecure-elasticsearch-node.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-ipsec-nat-traversal-port-activity.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-mfa-disabled-for-google-workspace-organization.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-mshta-making-network-connections.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-o365-excessive-single-sign-on-logon-errors.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-parent-process-pid-spoofing.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-possible-fin7-dga-command-and-control-behavior.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-rare-aws-error-code.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-rdp-remote-desktop-protocol-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-roshal-archive-rar-or-powershell-file-downloaded-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-rpc-remote-procedure-call-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-rpc-remote-procedure-call-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-smb-windows-file-sharing-activity-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-smtp-on-port-26-tcp.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-spike-in-aws-error-messages.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-suspicious-certutil-commands.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-telnet-port-activity.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-unusual-aws-command-for-a-user.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-unusual-child-processes-of-rundll32.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-unusual-city-for-an-aws-command.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-unusual-country-for-an-aws-command.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-unusual-print-spooler-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-vnc-virtual-network-computing-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-vnc-virtual-network-computing-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-web-application-suspicious-activity-no-user-agent.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-web-application-suspicious-activity-post-request-declined.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-web-application-suspicious-activity-sqlmap-user-agent.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-web-application-suspicious-activity-unauthorized-method.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-windows-defender-exclusions-added-via-powershell.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rules-0-13-3-appendix.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rules-0-13-3-summary.asciidoc
  docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
  docs/index.asciidoc
Labels: backport

#846 [7.x] [Detection Rules] Add rule updates for 0.13.3 package (#833)
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-cobalt-strike-command-and-control-beacon.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-default-cobalt-strike-team-server-certificate.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-disable-windows-event-and-security-logs-using-built-in-tools.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-dns-activity-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-execution-of-file-written-or-modified-by-microsoft-office.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-execution-of-file-written-or-modified-by-pdf-reader.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-external-alerts.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-external-ip-lookup-fron-non-browser-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-mfa-enforcement-disabled.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-password-policy-modified.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-halfbaked-command-and-control-beacon.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-inbound-connection-to-an-unsecure-elasticsearch-node.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-ipsec-nat-traversal-port-activity.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-mfa-disabled-for-google-workspace-organization.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-mshta-making-network-connections.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-o365-excessive-single-sign-on-logon-errors.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-parent-process-pid-spoofing.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-possible-fin7-dga-command-and-control-behavior.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-rare-aws-error-code.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-rdp-remote-desktop-protocol-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-roshal-archive-rar-or-powershell-file-downloaded-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-rpc-remote-procedure-call-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-rpc-remote-procedure-call-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-smb-windows-file-sharing-activity-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-smtp-on-port-26-tcp.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-spike-in-aws-error-messages.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-suspicious-certutil-commands.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-telnet-port-activity.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-unusual-aws-command-for-a-user.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-unusual-child-processes-of-rundll32.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-unusual-city-for-an-aws-command.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-unusual-country-for-an-aws-command.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-unusual-print-spooler-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-vnc-virtual-network-computing-from-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-vnc-virtual-network-computing-to-the-internet.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-web-application-suspicious-activity-no-user-agent.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-web-application-suspicious-activity-post-request-declined.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-web-application-suspicious-activity-sqlmap-user-agent.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-web-application-suspicious-activity-unauthorized-method.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-windows-defender-exclusions-added-via-powershell.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rules-0-13-3-appendix.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rules-0-13-3-summary.asciidoc
  docs/detections/prebuilt-rules/prebuilt-rules-downloadable-updates.asciidoc
  docs/index.asciidoc
Labels: backport

#808 [DOCS] CTI enhancements to the Overview page and Alert details pane
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/images/add-alert-to-existing-case.png
  docs/detections/images/add-alert-to-new-case.png
  docs/detections/images/additional-filters.png
  docs/detections/images/customize-event-renderer-page.png
  docs/detections/images/customize-event-renderer.png
  docs/detections/images/threat-intel-fields.png
  docs/getting-started/images/threat-intelligence-card.png
  docs/getting-started/security-ui.asciidoc
Labels: TEAM:Docs, Team: CTI, v7.14.0

#850 [7.14] [DOCS] CTI enhancements to the Overview page and Alert details pane (#808)
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/images/add-alert-to-existing-case.png
  docs/detections/images/add-alert-to-new-case.png
  docs/detections/images/additional-filters.png
  docs/detections/images/customize-event-renderer-page.png
  docs/detections/images/customize-event-renderer.png
  docs/detections/images/threat-intel-fields.png
  docs/getting-started/images/threat-intelligence-card.png
  docs/getting-started/security-ui.asciidoc
Labels: backport, v7.14.0

#849 [7.x] [DOCS] CTI enhancements to the Overview page and Alert details pane (#808)
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/images/add-alert-to-existing-case.png
  docs/detections/images/add-alert-to-new-case.png
  docs/detections/images/additional-filters.png
  docs/detections/images/customize-event-renderer-page.png
  docs/detections/images/customize-event-renderer.png
  docs/detections/images/threat-intel-fields.png
  docs/getting-started/images/threat-intelligence-card.png
  docs/getting-started/security-ui.asciidoc
Labels: backport, v8.0.0

#814 [DOCS] Document the new sub-feature privs for Cases
  docs/getting-started/cases-req.asciidoc
  docs/getting-started/images/cases-privs.png
Labels: Feature: Cases, TEAM:Docs, v7.14.0

#851 [7.x] [DOCS] Document the new sub-feature privs for Cases (#814)
  docs/getting-started/cases-req.asciidoc
  docs/getting-started/images/cases-privs.png
Labels: backport, v8.0.0

#852 [7.14] [DOCS] Document the new sub-feature privs for Cases (#814)
  docs/getting-started/cases-req.asciidoc
  docs/getting-started/images/cases-privs.png
Labels: backport, v7.14.0

#795 [DOCS] Document new Swimlane connector and additional Cases enhancements
  docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
  docs/cases/cases-overview.asciidoc
  docs/cases/cases-ui-integrations.asciidoc
  docs/cases/images/cases-home-page.png
  docs/cases/images/cases-ui-connector.png
  docs/cases/images/cases-ui-open.png
  docs/detections/images/all-rules.png
  docs/detections/images/available-action-types.png
  docs/detections/images/create-new-rule.png
  docs/detections/images/preview-rule.png
  docs/detections/images/rule-actions.png
  docs/detections/images/schedule-rule.png
  docs/detections/images/selected-action-type.png
  docs/detections/rules-ui-create.asciidoc
  docs/getting-started/detections-req.asciidoc
Labels: TEAM:Docs, Team:Threat Hunting, v7.14.0

#854 [7.14] [DOCS] Document new Swimlane connector and additional Cases enhancements (#795)
  docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
  docs/cases/cases-overview.asciidoc
  docs/cases/cases-ui-integrations.asciidoc
  docs/cases/images/cases-home-page.png
  docs/cases/images/cases-ui-connector.png
  docs/cases/images/cases-ui-open.png
  docs/detections/images/all-rules.png
  docs/detections/images/available-action-types.png
  docs/detections/images/create-new-rule.png
  docs/detections/images/preview-rule.png
  docs/detections/images/rule-actions.png
  docs/detections/images/schedule-rule.png
  docs/detections/images/selected-action-type.png
  docs/detections/rules-ui-create.asciidoc
  docs/getting-started/detections-req.asciidoc
Labels: backport

#853 [7.x] [DOCS] Document new Swimlane connector and additional Cases enhancements (#795)
  docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
  docs/cases/cases-overview.asciidoc
  docs/cases/cases-ui-integrations.asciidoc
  docs/cases/images/cases-home-page.png
  docs/cases/images/cases-ui-connector.png
  docs/cases/images/cases-ui-open.png
  docs/detections/images/all-rules.png
  docs/detections/images/available-action-types.png
  docs/detections/images/create-new-rule.png
  docs/detections/images/preview-rule.png
  docs/detections/images/rule-actions.png
  docs/detections/images/schedule-rule.png
  docs/detections/images/selected-action-type.png
  docs/detections/rules-ui-create.asciidoc
  docs/getting-started/detections-req.asciidoc
Labels: backport

#845 Host Isolation
  docs/management/admin/host-isolation-ov.asciidoc
  docs/management/admin/images/activity-log.png
  docs/management/admin/images/isolated-host.png
Labels: TEAM:Docs, Team:OLM, v7.14.0

#858 [7.x] Host Isolation (#845)
  docs/management/admin/host-isolation-ov.asciidoc
  docs/management/admin/images/activity-log.png
  docs/management/admin/images/isolated-host.png
Labels: backport, v8.0.0

#859 [7.14] Host Isolation (#845)
  docs/management/admin/host-isolation-ov.asciidoc
  docs/management/admin/images/activity-log.png
  docs/management/admin/images/isolated-host.png
Labels: backport, v7.14.0
