Repository elastic/security-docs, pull requests merged in 2021-02, with the labels that each got.

#485 [7.x] Updates for 7.11. (#484)
  docs/management/admin/admin-pg-ov.asciidoc
Labels: backport

#486 [7.11] Updates for 7.11. (#484)
  docs/management/admin/admin-pg-ov.asciidoc
Labels: backport

#491 [7.11] Issue #408: Event analyzer updates (#466)
  docs/detections/images/analyze-event.png
  docs/detections/images/incompatible-field-mappings.png
  docs/detections/images/node-legend.png
  docs/detections/images/process-schema.png
  docs/detections/visual-event-analyzer.asciidoc
Labels: backport

#490 [7.x] Issue #408: Event analyzer updates (#466)
  docs/detections/images/analyze-event.png
  docs/detections/images/incompatible-field-mappings.png
  docs/detections/images/node-legend.png
  docs/detections/images/process-schema.png
  docs/detections/visual-event-analyzer.asciidoc
Labels: backport

#494 [7.x] Issue #412 - Add warning about Kibana Dev Console (#489)
  docs/siem-apis.asciidoc
Labels: backport

#495 [7.11] Issue #412 - Add warning about Kibana Dev Console (#489)
  docs/siem-apis.asciidoc
Labels: backport

#500 [7.11] [DOCS] Create detection rules (7.11) (#450)
  docs/detections/images/all-rules.png
  docs/detections/images/indicator_value_list.png
  docs/detections/rules-ui-create.asciidoc
Labels: backport

#499 [7.x] [DOCS] Create detection rules (7.11) (#450)
  docs/detections/images/all-rules.png
  docs/detections/images/indicator_value_list.png
  docs/detections/rules-ui-create.asciidoc
Labels: backport

#504 [7.11] Issue #403: Malware notifications (#465)
  docs/detections/detection-engine-intro.asciidoc
  docs/getting-started/images/install-endpoint/malware-protection.png
  docs/getting-started/install-endpoint.asciidoc
Labels: backport

#503 [7.x] Issue #403: Malware notifications (#465)
  docs/detections/detection-engine-intro.asciidoc
  docs/getting-started/images/install-endpoint/malware-protection.png
  docs/getting-started/install-endpoint.asciidoc
Labels: backport

#502 [7.11] [DOCS] Exception lists - 7.11 (#467)
  docs/detections/detections-ui-exceptions.asciidoc
  docs/detections/images/actions-exception-list.png
  docs/detections/images/delete-list.png
  docs/detections/images/exception-list.png
  docs/detections/images/export-list.png
  docs/detections/images/manage-value-list.png
  docs/detections/images/monitor-table.png
  docs/detections/rules-ui-monitor.asciidoc
Labels: backport

#501 [7.x] [DOCS] Exception lists - 7.11 (#467)
  docs/detections/detections-ui-exceptions.asciidoc
  docs/detections/images/actions-exception-list.png
  docs/detections/images/delete-list.png
  docs/detections/images/exception-list.png
  docs/detections/images/export-list.png
  docs/detections/images/manage-value-list.png
  docs/detections/images/monitor-table.png
  docs/detections/rules-ui-monitor.asciidoc
Labels: backport

#509 [7.x] [DOCS] Troubleshoot missing alerts (7.11) (#507)
  docs/detections/images/timestamp-override.png
  docs/detections/rules-ui-monitor.asciidoc
Labels: backport

#510 [7.11] [DOCS] Troubleshoot missing alerts (7.11) (#507)
  docs/detections/images/timestamp-override.png
  docs/detections/rules-ui-monitor.asciidoc
Labels: backport

#505 [7.x] [DOCS] Detection engine/cold tier data - 7.11 (#487)
  docs/detections/detection-engine-intro.asciidoc
  docs/es-overview.asciidoc
Labels: backport

#506 [7.11] [DOCS] Detection engine/cold tier data - 7.11 (#487)
  docs/detections/detection-engine-intro.asciidoc
  docs/es-overview.asciidoc
Labels: backport

#513 [7.11] Issue #429: 7.11 release notes (#458)
  docs/release-notes.asciidoc
Labels: backport

#512 [7.x] Issue #429: 7.11 release notes (#458)
  docs/release-notes.asciidoc
Labels: backport

#483 [DOCS] Removes redundant intro to prebuilt ML modules
  docs/detections/machine-learning/machine-learning.asciidoc
Labels: v7.11.0, v8.0.0

#514 [7.x][DOCS] Removes redundant intro to prebuilt ML modules (#483)
  docs/detections/machine-learning/machine-learning.asciidoc
Labels: backport

#515 [7.11][DOCS] Removes redundant intro to prebuilt ML modules (#483)
  docs/detections/machine-learning/machine-learning.asciidoc
Labels: backport

#516 [7.x] [DOCS] What's new in 7.11 (#511)
  docs/whats-new.asciidoc
Labels: backport

#517 [7.11] [DOCS] What's new in 7.11 (#511)
  docs/whats-new.asciidoc
Labels: backport

#508 [Docs][Cases] Fix docs for 7.10: Connector
  docs/cases/api/cases-api/case-api-update-connector.asciidoc
  docs/cases/api/cases-api/cases-api-assign-connector.asciidoc
  docs/cases/api/cases-api/cases-api-associate-sn.asciidoc
  docs/cases/api/cases-api/cases-api-create.asciidoc
  docs/cases/api/cases-api/cases-api-find-cases.asciidoc
  docs/cases/api/cases-api/cases-api-get-case-activity.asciidoc
  docs/cases/api/cases-api/cases-api-get-case.asciidoc
  docs/cases/api/cases-api/cases-api-get-connector.asciidoc
  docs/cases/api/cases-api/cases-api-update.asciidoc
Labels: v7.10.0

#521 Issue #518: Remove beta tag from detections
  docs/detections/detection-engine-intro.asciidoc
Labels: Team:Detections/Response, v7.11.0

#526 [7.x] Issue #518: Remove beta tag from detections (#521)
  docs/detections/detection-engine-intro.asciidoc
Labels: backport

#527 [7.12] Issue #518: Remove beta tag from detections (#521)
  docs/detections/detection-engine-intro.asciidoc
Labels: backport

#528 [7.11] Issue #518: Remove beta tag from detections (#521)
  docs/detections/detection-engine-intro.asciidoc
Labels: backport

#531 [7.11] Issue 437: Maintenance permission (#492)
  docs/getting-started/detections-req.asciidoc
Labels: backport

#530 [7.12] Issue 437: Maintenance permission (#492)
  docs/getting-started/detections-req.asciidoc
Labels: backport

#529 [7.x] Issue 437: Maintenance permission (#492)
  docs/getting-started/detections-req.asciidoc
Labels: backport
