Repository elastic/security-docs, pull requests merged in 2021-01, with the labels that each got.

#424 Issue #389: Update out of date cases screenshot
  docs/cases/images/cases-ui-open.png
Labels: 7.10.1, v7.11.0

#441 [7.x] Committing updates. (#438)
  docs/detections/api/rules/rules-api-create.asciidoc
  docs/detections/detections-ui-exceptions.asciidoc
  docs/detections/images/endpoint-add-exp.png
  docs/detections/images/exceptions-ui-list.png
Labels: backport

#442 [7.10] Committing updates. (#438)
  docs/detections/api/rules/rules-api-create.asciidoc
  docs/detections/detections-ui-exceptions.asciidoc
  docs/detections/images/endpoint-add-exp.png
  docs/detections/images/exceptions-ui-list.png
Labels: backport

#443 DOCS: Clarification for using filters array (#426)
  docs/detections/rules-ui-create.asciidoc
Labels: backport

#444 DOCS: Clarification for using filters array (#426)
  docs/detections/rules-ui-create.asciidoc
Labels: backport

#435 Document Signals Migration APIs
  docs/detections/api/signals-migration-api.asciidoc
  docs/post-upgrade-req.asciidoc
  docs/siem-apis.asciidoc
Labels: v7.11.0

#454 [7.x] Correct source/destination.as field listings (#447)
  docs/reference/field-ref.asciidoc
Labels: backport

#455 [7.10] Correct source/destination.as field listings (#447)
  docs/reference/field-ref.asciidoc
Labels: backport

#456 [7.x] Document Signals Migration APIs (#435)
  docs/detections/api/signals-migration-api.asciidoc
  docs/post-upgrade-req.asciidoc
  docs/siem-apis.asciidoc
Labels: backport

#457 [7.10] Document Signals Migration APIs (#435)
  docs/detections/api/signals-migration-api.asciidoc
  docs/post-upgrade-req.asciidoc
  docs/siem-apis.asciidoc
Labels: backport

#460 [7.11] Committing updates. (#438)
  docs/detections/api/rules/rules-api-create.asciidoc
  docs/detections/detections-ui-exceptions.asciidoc
  docs/detections/images/endpoint-add-exp.png
  docs/detections/images/exceptions-ui-list.png
Labels: backport

#461 [7.11] Correct source/destination.as field listings (#447)
  docs/reference/field-ref.asciidoc
Labels: backport

#462 [7.11] Document Signals Migration APIs (#435)
  docs/detections/api/signals-migration-api.asciidoc
  docs/post-upgrade-req.asciidoc
  docs/siem-apis.asciidoc
Labels: backport

#452 Issue #419: Add advanced policy settings description to detail page
  docs/management/admin/admin-pg-ov.asciidoc
  docs/management/admin/images/advanced-settings.png
Labels: v7.11.0

#470 [7.11] Issue #419: Add advanced policy settings description to detail page (#452)
  docs/management/admin/admin-pg-ov.asciidoc
  docs/management/admin/images/advanced-settings.png
Labels: backport

#469 [7.x] Issue #419: Add advanced policy settings description to detail page (#452)
  docs/management/admin/admin-pg-ov.asciidoc
  docs/management/admin/images/advanced-settings.png
Labels: backport

#451 Issue #407: Register Endpoint as Windows AV
  docs/getting-started/images/register-as-antivirus.png
  docs/getting-started/install-endpoint.asciidoc
Labels: v7.11.0

#472 [7.x] Issue #407: Register Endpoint as Windows AV (#451)
  docs/getting-started/images/register-as-antivirus.png
  docs/getting-started/install-endpoint.asciidoc
Labels: backport

#473 [7.11] Issue #407: Register Endpoint as Windows AV (#451)
  docs/getting-started/images/register-as-antivirus.png
  docs/getting-started/install-endpoint.asciidoc
Labels: backport

#480 [7.10] [DOCS] Updates to Elastic Security Overview (#476)
  docs/es-overview.asciidoc
Labels: backport

#479 [7.11] [DOCS] Updates to Elastic Security Overview (#476)
  docs/es-overview.asciidoc
Labels: backport

#478 [7.x] [DOCS] Updates to Elastic Security Overview (#476)
  docs/es-overview.asciidoc
Labels: backport

#445 [Docs] 7.11 Cases API updates
  docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
  docs/cases/api/cases-api/case-api-update-connector.asciidoc
  docs/cases/api/cases-api/cases-api-add-comment.asciidoc
  docs/cases/api/cases-api/cases-api-assign-connector.asciidoc
  docs/cases/api/cases-api/cases-api-associate-sn.asciidoc
  docs/cases/api/cases-api/cases-api-create.asciidoc
  docs/cases/api/cases-api/cases-api-find-cases.asciidoc
  docs/cases/api/cases-api/cases-api-find-connectors.asciidoc
  docs/cases/api/cases-api/cases-api-get-case-activity.asciidoc
  docs/cases/api/cases-api/cases-api-get-case-comments.asciidoc
  docs/cases/api/cases-api/cases-api-get-case.asciidoc
  docs/cases/api/cases-api/cases-api-get-comment.asciidoc
  docs/cases/api/cases-api/cases-api-get-connector.asciidoc
  docs/cases/api/cases-api/cases-api-get-status.asciidoc
  docs/cases/api/cases-api/cases-api-index.asciidoc
  docs/cases/api/cases-api/cases-api-push.asciidoc
  docs/cases/api/cases-api/cases-api-update-comment.asciidoc
  docs/cases/api/cases-api/cases-api-update.asciidoc
  docs/cases/cases-overview.asciidoc
  docs/cases/cases-ui-integrations.asciidoc
  docs/index.asciidoc
Labels: documentation, v7.11.0, v8.0.0

#481 [7.x] [Docs] 7.11 Cases API updates (#445)
  docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
  docs/cases/api/cases-api/case-api-update-connector.asciidoc
  docs/cases/api/cases-api/cases-api-add-comment.asciidoc
  docs/cases/api/cases-api/cases-api-assign-connector.asciidoc
  docs/cases/api/cases-api/cases-api-associate-sn.asciidoc
  docs/cases/api/cases-api/cases-api-create.asciidoc
  docs/cases/api/cases-api/cases-api-find-cases.asciidoc
  docs/cases/api/cases-api/cases-api-find-connectors.asciidoc
  docs/cases/api/cases-api/cases-api-get-case-activity.asciidoc
  docs/cases/api/cases-api/cases-api-get-case-comments.asciidoc
  docs/cases/api/cases-api/cases-api-get-case.asciidoc
  docs/cases/api/cases-api/cases-api-get-comment.asciidoc
  docs/cases/api/cases-api/cases-api-get-connector.asciidoc
  docs/cases/api/cases-api/cases-api-get-status.asciidoc
  docs/cases/api/cases-api/cases-api-index.asciidoc
  docs/cases/api/cases-api/cases-api-push.asciidoc
  docs/cases/api/cases-api/cases-api-update-comment.asciidoc
  docs/cases/api/cases-api/cases-api-update.asciidoc
  docs/cases/cases-overview.asciidoc
  docs/cases/cases-ui-integrations.asciidoc
  docs/index.asciidoc
Labels: backport

#482 [7.11] [Docs] 7.11 Cases API updates (#445)
  docs/cases/api/actions-api/cases-actions-api-intro.asciidoc
  docs/cases/api/cases-api/case-api-update-connector.asciidoc
  docs/cases/api/cases-api/cases-api-add-comment.asciidoc
  docs/cases/api/cases-api/cases-api-assign-connector.asciidoc
  docs/cases/api/cases-api/cases-api-associate-sn.asciidoc
  docs/cases/api/cases-api/cases-api-create.asciidoc
  docs/cases/api/cases-api/cases-api-find-cases.asciidoc
  docs/cases/api/cases-api/cases-api-find-connectors.asciidoc
  docs/cases/api/cases-api/cases-api-get-case-activity.asciidoc
  docs/cases/api/cases-api/cases-api-get-case-comments.asciidoc
  docs/cases/api/cases-api/cases-api-get-case.asciidoc
  docs/cases/api/cases-api/cases-api-get-comment.asciidoc
  docs/cases/api/cases-api/cases-api-get-connector.asciidoc
  docs/cases/api/cases-api/cases-api-get-status.asciidoc
  docs/cases/api/cases-api/cases-api-index.asciidoc
  docs/cases/api/cases-api/cases-api-push.asciidoc
  docs/cases/api/cases-api/cases-api-update-comment.asciidoc
  docs/cases/api/cases-api/cases-api-update.asciidoc
  docs/cases/cases-overview.asciidoc
  docs/cases/cases-ui-integrations.asciidoc
  docs/index.asciidoc
Labels: backport
