Repository elastic/security-docs, pull requests merged in 2021-03, with the labels that each got.

#522 [DOCS] Updates Create Rule API docs for Threshold and Indicator Match Rules
  docs/detections/api/rules/rules-api-create.asciidoc
Labels: Team:Detections/Response, v7.12.0

#540 [7.12] [DOCS] Updates Create Rule API docs for Threshold and Indicator Match Rules (#522)
  docs/detections/api/rules/rules-api-create.asciidoc
Labels: backport

#539 [7.x] [DOCS] Updates Create Rule API docs for Threshold and Indicator Match Rules (#522)
  docs/detections/api/rules/rules-api-create.asciidoc
Labels: backport

#544 [7.12] Issue #538: 7.11.2 release notes (#542)
  docs/release-notes.asciidoc
Labels: backport

#547 Updates Update Rule docs for Threshold + Indicator Match rules
  docs/detections/api/rules/rules-api-update.asciidoc
Labels: Team:Detections/Response, v7.12.0

#556 [DOCS] Update 7.11 RNs
  docs/release-notes.asciidoc
Labels: v7.11.0

#561 [DOCS] Small Exception list updates (7.12)
  docs/detections/detections-ui-exceptions.asciidoc
  docs/detections/images/exception-list.png
Labels: v7.12.0

#554 EQL Docs for Timeline
  docs/events/images/correlation-tab-eql-query.png
  docs/events/timeline-ui-overview.asciidoc
Labels: TEAM:Docs, Team:Threat Hunting, v7.12.0

#537 Issue #525: timeline accessibility improvements
  docs/events/images/test2.gif
  docs/events/images/timeline-ui-renderer.png
  docs/events/images/timeline-ui.png
  docs/events/timeline-ui-overview.asciidoc
  docs/getting-started/images/timeline-ui-accessiblity-directional-arrows.gif
  docs/getting-started/images/timeline-ui-accessiblity-display-menu.gif
  docs/getting-started/images/timeline-ui-accessiblity-drag-and-drop.gif
  docs/getting-started/images/timeline-ui-accessiblity-event-renderer.gif
  docs/getting-started/images/timeline-ui-accessiblity-keyboard-focus-hotkeys.gif
  docs/getting-started/images/timeline-ui-accessiblity-keyboard-focus.gif
  docs/getting-started/images/timeline-ui-accessiblity-page-up-and-down.gif
  docs/getting-started/images/timeline-ui-accessiblity-shift-keyboard-focus.gif
  docs/getting-started/images/timeline-ui-accessiblity-tab-key.gif
  docs/getting-started/security-ui.asciidoc
Labels: Team:Detections/Response, v7.12.0

#568 [7.x] [DOCS] Small Exception list updates (7.12) (#561)
  docs/detections/detections-ui-exceptions.asciidoc
  docs/detections/images/exception-list.png
Labels: backport

#569 [7.12] [DOCS] Small Exception list updates (7.12) (#561)
  docs/detections/detections-ui-exceptions.asciidoc
  docs/detections/images/exception-list.png
Labels: backport

#550 [DOCS] 7.12.0 release notes
  docs/release-notes.asciidoc
Labels: TEAM:Docs, release-notes, v7.12.0

#570 [7.x] [DOCS] Ransomware additions (7.12) (#559)
  docs/detections/detection-engine-intro.asciidoc
  docs/getting-started/images/install-endpoint/event-collection.png
  docs/getting-started/images/install-endpoint/malware-protection.png
  docs/getting-started/images/install-endpoint/ransomware-protection.png
  docs/getting-started/install-endpoint.asciidoc
Labels: backport

#571 [7.12] [DOCS] Ransomware additions (7.12) (#559)
  docs/detections/detection-engine-intro.asciidoc
  docs/getting-started/images/install-endpoint/event-collection.png
  docs/getting-started/images/install-endpoint/malware-protection.png
  docs/getting-started/images/install-endpoint/ransomware-protection.png
  docs/getting-started/install-endpoint.asciidoc
Labels: backport

#572 [7.x] Issue #525: timeline accessibility improvements (#537)
  docs/events/images/test2.gif
  docs/events/images/timeline-ui-renderer.png
  docs/events/images/timeline-ui.png
  docs/events/timeline-ui-overview.asciidoc
  docs/getting-started/images/timeline-ui-accessiblity-directional-arrows.gif
  docs/getting-started/images/timeline-ui-accessiblity-display-menu.gif
  docs/getting-started/images/timeline-ui-accessiblity-drag-and-drop.gif
  docs/getting-started/images/timeline-ui-accessiblity-event-renderer.gif
  docs/getting-started/images/timeline-ui-accessiblity-keyboard-focus-hotkeys.gif
  docs/getting-started/images/timeline-ui-accessiblity-keyboard-focus.gif
  docs/getting-started/images/timeline-ui-accessiblity-page-up-and-down.gif
  docs/getting-started/images/timeline-ui-accessiblity-shift-keyboard-focus.gif
  docs/getting-started/images/timeline-ui-accessiblity-tab-key.gif
  docs/getting-started/security-ui.asciidoc
Labels: backport

#574 [7.x] EQL Docs for Timeline (#554)
  docs/events/images/correlation-tab-eql-query.png
  docs/events/timeline-ui-overview.asciidoc
Labels: backport

#576 [7.x] [DOCS] 7.12.0 release notes (#550)
  docs/release-notes.asciidoc
Labels: backport

#578 [7.12] [DOCS] 7.12.0 release notes (#550)
  docs/release-notes.asciidoc
Labels: backport

#579 [7.12] [DOCS] UPDATED - Ransomware (7.12) (#567)
  docs/getting-started/install-endpoint.asciidoc
Labels: backport

#577 [7.x] [DOCS] UPDATED - Ransomware (7.12) (#567)
  docs/getting-started/install-endpoint.asciidoc
Labels: backport

#585 [7.x] Update whats-new.asciidoc (#583)
  docs/whats-new.asciidoc
Labels: backport

#586 [7.12] Update whats-new.asciidoc (#583)
  docs/whats-new.asciidoc
Labels: backport

#587 [7.x] Adding #91718 to 7.12 RNs. (#584)
  docs/release-notes.asciidoc
Labels: backport

#588 [7.12] Adding #91718 to 7.12 RNs. (#584)
  docs/release-notes.asciidoc
Labels: backport

#591 [7.12] [DOCS] Rules updates (7.12) (#582)
  docs/detections/detection-engine-intro.asciidoc
  docs/detections/prebuilt-rules/tune-rule-signals.asciidoc
  docs/detections/rules-ui-create.asciidoc
  docs/detections/rules-ui-monitor.asciidoc
  docs/es-overview.asciidoc
Labels: backport

#590 [7.x] [DOCS] Rules updates (7.12) (#582)
  docs/detections/detection-engine-intro.asciidoc
  docs/detections/prebuilt-rules/tune-rule-signals.asciidoc
  docs/detections/rules-ui-create.asciidoc
  docs/detections/rules-ui-monitor.asciidoc
  docs/es-overview.asciidoc
Labels: backport

#553 [DOCS] Add section for troubleshooting ML compatibility
  docs/detections/rules-ui-monitor.asciidoc
Labels: TEAM:Docs, v7.11.3, v7.12.0

#597 [7.11][DOCS] Add section for troubleshooting ML compatibility (#553)
  docs/detections/rules-ui-monitor.asciidoc
Labels: backport

#598 [7.x][DOCS] Add section for troubleshooting ML compatibility (#553)
  docs/detections/rules-ui-monitor.asciidoc
Labels: backport

#599 [DOCS] Add section for troubleshooting ML compatibility (#553)
  docs/detections/rules-ui-monitor.asciidoc
Labels: backport
