Repository elastic/security-docs, pull requests merged in 2022-01, with the labels that each got.

#1368 [7.17] [DOCS] Add 7.16.2 release notes (#1362)
  docs/release-notes.asciidoc
  docs/release-notes/7.16.asciidoc
Labels: backport

#1361 [DOCS] Add 'host isolation exceptions' to topic list
  docs/management/manage-intro.asciidoc
Labels: v8.0.0, v7.16.0, v7.17.0

#1367 [Cases] Change user actions response
  docs/cases/api/cases-api/cases-api-get-case-activity.asciidoc
Labels: Team:Threat Hunting, v8.1.0

#1375 [DOCS] Updates create case API
  docs/cases/api/cases-api/cases-api-create.asciidoc
Labels: v8.0.0, API, v7.16.0, v7.17.0

#1376 [DOCS] update list endpoints documentation
  docs/management/api/list-endpoints-api.asciidoc
Labels: v8.0.0, Team:OLM

#1359 [BUG] Fix spelling errors
  docs/events/timeline-templates.asciidoc
  docs/getting-started/siem-ui.asciidoc
  docs/management/admin/host-isolation-exceptions.asciidoc
  docs/management/hosts/hosts-overview.asciidoc
Labels: bug, Team:Docs, v8.0.0, v7.16.0, v7.17.0

#1391 [DOCS] EQL updates
  docs/detections/detections-ui-exceptions.asciidoc
  docs/detections/rules-ui-create.asciidoc
Labels: v8.0.0, Feature: EQL, v7.16.0, v7.17.0

#1381 [DOCS] 7.16.3 Release Notes
  docs/release-notes.asciidoc
  docs/release-notes/7.16.asciidoc
Labels: Team:Docs, release-notes, v7.16.0, v7.17.0, v7.16.3

#1349 [DOCS] Create Beaconing Detections page (experimental features)
  docs/experimental-features/beaconing-detection.asciidoc
  docs/experimental-features/experimental-features-intro.asciidoc
  docs/experimental-features/images/beaconing-detection-1.png
  docs/experimental-features/images/beaconing-detection-2.png
Labels: v8.0.0, v7.16.0, v7.17.0

#1414 [7.17] [DOCS] 7.16.3 Release Notes (#1381)
  docs/release-notes.asciidoc
  docs/release-notes/7.16.asciidoc
Labels: backport

#1397 [DOCS] UI changes: Alerts and Exceptions pages
  docs/detections/alerts-ui-manage.asciidoc
  docs/detections/detection-engine-intro.asciidoc
  docs/detections/detections-ui-exceptions.asciidoc
  docs/detections/images/actions-exception-list.png
  docs/detections/images/additional-filters.png
  docs/detections/images/alert-page.png
  docs/detections/images/exceptions-page.png
  docs/getting-started/images/collapse-side-nav-button.gif
  docs/getting-started/images/live-feed-ov-page.png
  docs/getting-started/images/overview-pg.png
  docs/getting-started/security-ui.asciidoc
Labels: Team:Docs, v8.0.0, Team:Detections/Response

#1408 [DOCS] Endpoint flyout UI updates
  docs/management/admin/images/config-status.png
  docs/management/admin/images/endpoints-pg.png
  docs/management/admin/images/host-flyout.png
Labels: Team:Docs, v8.0.0, Team:OLM

#1422 [DOCS] Setup for 8.0 RNs
  docs/release-notes.asciidoc
  docs/release-notes/8.0.asciidoc
Labels: v8.0.0, release-notes

#1400 [DOCS] Update incorrect references to "Index pattern" to "Data view" for 8.0.0
  docs/detections/machine-learning/machine-learning.asciidoc
  docs/detections/prebuilt-rules/tune-rule-signals.asciidoc
  docs/events/images/correlation-tab-eql-query.png
  docs/events/images/timeline-ui-renderer.png
  docs/events/images/timeline-ui-updated.png
  docs/events/timeline-ui-overview.asciidoc
  docs/getting-started/net-map-req.asciidoc
  docs/getting-started/siem-ui.asciidoc
Labels: v8.0.0, Feature: Data Views

#1426 [DOCS] Update Host and Network page images to match version 8.0.0
  docs/getting-started/images/network-ui.png
  docs/management/hosts/images/drop-to-timeline.png
  docs/management/hosts/images/hosts-detail-pg.png
  docs/management/hosts/images/hosts-ov-pg.png
Labels: v8.0.0

#1441 [DOCS] Fix links to the Filebeat Google Workspace module
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-mfa-enforcement-disabled.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-password-policy-modified.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-mfa-disabled-for-google-workspace-organization.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-application-added-to-google-workspace-domain.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-domain-added-to-google-workspace-trusted-domains.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-admin-role-assigned-to-a-user.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-admin-role-deletion.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-api-access-granted-via-domain-wide-delegation-of-authority.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-custom-admin-role-created.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-mfa-enforcement-disabled.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-password-policy-modified.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-role-modified.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-mfa-disabled-for-google-workspace-organization.asciidoc
  docs/detections/prebuilt-rules/rule-details/application-added-to-google-workspace-domain.asciidoc
  docs/detections/prebuilt-rules/rule-details/domain-added-to-google-workspace-trusted-domains.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-admin-role-assigned-to-a-user.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-admin-role-deletion.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-api-access-granted-via-domain-wide-delegation-of-authority.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-custom-admin-role-created.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-mfa-enforcement-disabled.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-password-policy-modified.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-role-modified.asciidoc
  docs/detections/prebuilt-rules/rule-details/mfa-disabled-for-google-workspace-organization.asciidoc
Labels: Team:Docs, v8.0.0, v7.11.0, v7.12.0, v7.11.3, v7.13.0, v7.12.2, v7.14.0, v7.13.3, v7.15.0, v7.14.2, v7.15.2, v7.17.0, v8.1.0, v7.16.3, v8.2.0

#1428 [DOCS] Explain requirement to create Endpoint exception
  docs/detections/detections-ui-exceptions.asciidoc
Labels: Team:Docs, v8.0.0, Team:Endpoint, Team:OLM, v7.16.0, v7.17.0, v8.1.0

#1439 Update exception list summary api doc
  docs/detections/api/exceptions/api-summary-exception-container.asciidoc
Labels: v8.1.0

#1459 [7.14] [DOCS] Fix links to filebeat Google Workspace module (#1441)
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-mfa-enforcement-disabled.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-password-policy-modified.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-mfa-disabled-for-google-workspace-organization.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-application-added-to-google-workspace-domain.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-domain-added-to-google-workspace-trusted-domains.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-admin-role-assigned-to-a-user.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-admin-role-deletion.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-api-access-granted-via-domain-wide-delegation-of-authority.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-custom-admin-role-created.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-mfa-enforcement-disabled.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-password-policy-modified.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-role-modified.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-mfa-disabled-for-google-workspace-organization.asciidoc
  docs/detections/prebuilt-rules/rule-details/application-added-to-google-workspace-domain.asciidoc
  docs/detections/prebuilt-rules/rule-details/domain-added-to-google-workspace-trusted-domains.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-admin-role-assigned-to-a-user.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-admin-role-deletion.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-api-access-granted-via-domain-wide-delegation-of-authority.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-custom-admin-role-created.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-mfa-enforcement-disabled.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-password-policy-modified.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-role-modified.asciidoc
  docs/detections/prebuilt-rules/rule-details/mfa-disabled-for-google-workspace-organization.asciidoc
Labels: backport

#1458 [7.16] [DOCS] Fix links to filebeat Google Workspace module (#1441)
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-mfa-enforcement-disabled.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-google-workspace-password-policy-modified.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-13-3/prebuilt-rule-0-13-3-mfa-disabled-for-google-workspace-organization.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-application-added-to-google-workspace-domain.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-domain-added-to-google-workspace-trusted-domains.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-admin-role-assigned-to-a-user.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-admin-role-deletion.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-api-access-granted-via-domain-wide-delegation-of-authority.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-custom-admin-role-created.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-mfa-enforcement-disabled.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-password-policy-modified.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-google-workspace-role-modified.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-1/prebuilt-rule-0-14-1-mfa-disabled-for-google-workspace-organization.asciidoc
  docs/detections/prebuilt-rules/rule-details/application-added-to-google-workspace-domain.asciidoc
  docs/detections/prebuilt-rules/rule-details/domain-added-to-google-workspace-trusted-domains.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-admin-role-assigned-to-a-user.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-admin-role-deletion.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-api-access-granted-via-domain-wide-delegation-of-authority.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-custom-admin-role-created.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-mfa-enforcement-disabled.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-password-policy-modified.asciidoc
  docs/detections/prebuilt-rules/rule-details/google-workspace-role-modified.asciidoc
  docs/detections/prebuilt-rules/rule-details/mfa-disabled-for-google-workspace-organization.asciidoc
Labels: backport

#1469 [DOCS] Improve Trusted Apps "wildcard"/"matches" field documentation
  docs/management/admin/trusted-apps.asciidoc
Labels: Team:Docs, v8.0.0, Team:OLM, v7.16.0, v7.17.0

#1434 [DOCS] Update detection rule exceptions export and import
  docs/detections/api/rules/rules-api-export.asciidoc
  docs/detections/api/rules/rules-api-import.asciidoc
  docs/detections/detections-ui-exceptions.asciidoc
  docs/detections/rules-ui-manage.asciidoc
Labels: Team:Docs, Team:SIEM, v8.0.0, Team:Detections/Response
