Repository elastic/security-docs, pull requests merged in 2023-12, with the labels that each got.

#4362 Remove enableGroupedNav advanced setting
  docs/getting-started/advanced-setting.asciidoc
Labels: bug, v8.9.0, v8.10.0, v8.11.0, Docset: ESS, v8.12.0

#4361 Updates Entity Risk Scoring requirements
  docs/getting-started/ers-req.asciidoc
Labels: Team: Security Solution, Feature: Entity Analytics, Priority: High, Effort: Small, v8.11.0, Docset: ESS, Team: Entity Analytics, v8.12.0

#4360 Adds `include_expired_exceptions` to Export exception list API
  docs/detections/api/exceptions/api-export-exception-list.asciidoc
Labels: API, Team: Security Platform, Feature: Exceptions, v8.7.0, v8.8.0, v8.9.0, Priority: Medium, v8.10.0, Effort: Small, v8.11.0, v8.12.0

#4296 Adds new Advanced Behavioral Detections section
  docs/advanced-entity-analytics/advanced-behavioral-detections.asciidoc
  docs/advanced-entity-analytics/advanced-entity-analytics-overview.asciidoc
  docs/advanced-entity-analytics/analyze-risk-score-data.asciidoc
  docs/advanced-entity-analytics/behavioral-detection-use-cases.asciidoc
  docs/advanced-entity-analytics/entity-risk-scoring.asciidoc
  docs/advanced-entity-analytics/images/cloned-job-details.png
  docs/advanced-entity-analytics/images/filter-add-item.png
  docs/advanced-entity-analytics/images/ml-rule-threshold.png
  docs/advanced-entity-analytics/images/ml-ui.png
  docs/advanced-entity-analytics/images/rule-scope.png
  docs/advanced-entity-analytics/images/rules-table-error-icon.png
  docs/advanced-entity-analytics/images/rules-table-ml-job-error.png
  docs/advanced-entity-analytics/images/start-job-window.png
  docs/advanced-entity-analytics/machine-learning.asciidoc
  docs/advanced-entity-analytics/prebuilt-ml-jobs.asciidoc
  docs/advanced-entity-analytics/tune-anomaly-results.asciidoc
  docs/advanced-entity-analytics/turn-on-risk-engine.asciidoc
  docs/detections/detections-index.asciidoc
  docs/getting-started/ers-req.asciidoc
Labels: Feature: Entity Analytics, Priority: High, Effort: Large, v8.11.0, Docset: ESS, Team: Entity Analytics, v8.12.0

#4390 Add Buildkite preview links to PRs
  .github/workflows/docs-preview.yml
Labels: Team:Docs, backport-skip

#4326 Document the behavior of IM rules and multi-value indicator documents
  docs/detections/rules-ui-create.asciidoc
Labels: v8.2.0, v8.3.0, v8.4.0, v8.5.0, v8.6.0, v8.7.0, v8.8.0, v8.9.0, Team: Detection Engine, Priority: Low, v8.10.0, Effort: Medium, v8.11.0

#4345 Updates to Entity Analytics Dashboard
  docs/dashboards/entity-dashboard.asciidoc
  docs/dashboards/images/run-job.png
Labels: Feature: Entity Analytics, Priority: High, Effort: Small, v8.11.0, Docset: ESS, Team: Entity Analytics, v8.12.0

#4406 Remove old PR preview GitHub action
  .github/workflows/docs-preview-links.yml
Labels: backport-skip

#4378 7.17.16 Release notes
  docs/release-notes.asciidoc
  docs/release-notes/7.17.asciidoc
Labels: release-notes, v7.17.16

#4376 8.11.2 Release notes
  docs/release-notes.asciidoc
  docs/release-notes/8.11.asciidoc
Labels: release-notes, v8.11.0, v8.12.0, v8.11.2

#4394 EA updates
  docs/advanced-entity-analytics/images/preview-risky-entities.png
  docs/advanced-entity-analytics/images/turn-on-risk-engine.png
  docs/advanced-entity-analytics/turn-on-risk-engine.asciidoc
  docs/getting-started/images/manage-pg.png
  docs/getting-started/security-ui.asciidoc
Labels: Feature: Entity Analytics, Priority: High, Effort: Small, v8.11.0, Team: Entity Analytics, v8.12.0, v8.11.2

#4419 [8.10] Add Buildkite preview links to PRs (#4390) | Delete docs-preview-links.yml (#4406)
  .github/workflows/docs-preview-links.yml
  .github/workflows/docs-preview.yml
Labels: backport

#4420 [8.9] Add Buildkite preview links to PRs (#4390) | Delete docs-preview-links.yml (#4406)
  .github/workflows/docs-preview-links.yml
  .github/workflows/docs-preview.yml
Labels: backport

#4421 [7.17] Add Buildkite preview links to PRs (#4390) | Delete docs-preview-links.yml (#4406)
  .github/workflows/docs-preview-links.yml
  .github/workflows/docs-preview.yml
Labels: backport

#4422 [8.8] Add Buildkite preview links to PRs (#4390) | Delete docs-preview-links.yml (#4406)
  .github/workflows/docs-preview-links.yml
  .github/workflows/docs-preview.yml
Labels: backport

#4423 [8.7] Add Buildkite preview links to PRs (#4390) | Delete docs-preview-links.yml (#4406)
  .github/workflows/docs-preview-links.yml
  .github/workflows/docs-preview.yml
Labels: backport

#4424 [8.6] Add Buildkite preview links to PRs (#4390) | Delete docs-preview-links.yml (#4406)
  .github/workflows/docs-preview-links.yml
  .github/workflows/docs-preview.yml
Labels: backport

#4426 [8.4] Add Buildkite preview links to PRs (#4390) | Delete docs-preview-links.yml (#4406)
  .github/workflows/docs-preview-links.yml
  .github/workflows/docs-preview.yml
Labels: backport

#4428 [8.2] Add Buildkite preview links to PRs (#4390) | Delete docs-preview-links.yml (#4406)
  .github/workflows/docs-preview-links.yml
  .github/workflows/docs-preview.yml
Labels: backport

#4430 [8.0] Add Buildkite preview links to PRs (#4390) | Delete docs-preview-links.yml (#4406)
  .github/workflows/docs-preview-links.yml
  .github/workflows/docs-preview.yml
Labels: backport

#4298 Timeline opens as a modal
  docs/getting-started/security-ui.asciidoc
Labels: Team: Threat Hunting, Feature: Timeline, Priority: High, Effort: Small, v8.12.0

#4413 D4C minor fixes
  docs/cloud-native-security/cloud-native-security-index.asciidoc
  docs/cloud-native-security/d4c-overview.asciidoc
Labels: enhancement, v8.11.0, v8.12.0

#4367 new .yaml version of known issue template
  .github/ISSUE_TEMPLATE/known-issue.md
  .github/ISSUE_TEMPLATE/known-issue.yaml
Labels: backport-skip

#4299 Timeline autosave removed in favor of manual save
  docs/events/timeline-templates.asciidoc
  docs/events/timeline-ui-overview.asciidoc
Labels: Team: Threat Hunting, Feature: Timeline, Priority: Medium, Effort: Small, v8.12.0

#4437 Save timeline as new
  docs/events/timeline-ui-overview.asciidoc
Labels: Team: Threat Hunting, Feature: Timeline, Priority: Medium, Effort: Small, Docset: ESS, v8.12.0

#4441 Fix duplicate images
  docs/getting-started/images/live-feed-ov-page.png
  docs/getting-started/images/overview-pg.png
  docs/whats-new/images/8.3/overview-pg.png
Labels: backport, v8.7.0, v8.8.0, v8.9.0, v8.10.0, v8.11.0, v8.12.0

#4442 [7.15] Fix dupe images
  docs/getting-started/images/cases-ui-home.png
Labels: backport, v7.13.0, v7.14.0, v7.15.0

#4443 [7.13] Fix dupe images
  docs/getting-started/images/cases-ui-home.png
  docs/getting-started/images/detections-ui.png
  docs/getting-started/security-ui.asciidoc
  docs/getting-started/siem-ui.asciidoc
Labels: backport, v7.9.0, v7.10.0, v7.11.0, v7.12.0

#4368 new .yaml bug report template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: backport-skip

#4462 Renames internal doc request template to change ToC order
  .github/ISSUE_TEMPLATE/docs-request-internal.yaml
Labels: backport-skip

#4463 Prebuilt rule customization — JSON diff [Classic]
  docs/detections/images/prebuilt-rules-update-diff.png
  docs/detections/prebuilt-rules-management.asciidoc
Labels: Team: Detections/Response, Feature: Rules, Feature: Prebuilt rules, Docset: ESS, v8.12.0

#4492 [ESS] Default ES|QL query updated
  docs/events/images/esql-tab.png
Labels: Feature: Timeline, Priority: High, Effort: Small, v8.12.0

#4494 Match phrasing with serverless docs
  docs/advanced-entity-analytics/behavioral-detection-use-cases.asciidoc
Labels: Feature: Entity Analytics, v8.11.0, Docset: ESS, v8.12.0

#4470 Fixes requirement statement on Behavioral detection use cases page
  docs/advanced-entity-analytics/behavioral-detection-use-cases.asciidoc
Labels: Feature: Entity Analytics, Priority: Medium, Effort: Small, v8.11.0, Team: Entity Analytics, v8.12.0

#4439 New page about allowlisting Elastic Endpoint in 3rd-party AV software
  docs/management/admin/allowlist-endpoint-3rd-party-av.asciidoc
  docs/management/manage-intro.asciidoc
Labels: enhancement, v8.0.0, v8.1.0, v8.2.0, v8.3.0, v8.4.0, v8.5.0, v8.6.0, v8.7.0, v8.8.0, v8.9.0, v8.10.0, v8.11.0, v8.12.0

#4412 Alert status auditing updates
  docs/detections/alerts-view-details.asciidoc
  docs/detections/images/about-section-rp.png
  docs/detections/images/alert-details-flyout-right-panel.png
  docs/reference/alert-schema.asciidoc
Labels: v8.12.0

#4484 Exclude cold and frozen tiers advanced setting
  docs/detections/visual-event-analyzer.asciidoc
  docs/getting-started/advanced-setting.asciidoc
Labels: Team: Threat Hunting, Priority: High, Effort: Medium, v8.12.0

#4499 [Bug][ESS][8.12] Screenshot needs to be updated for the missing ES|QL tab in timeline
  docs/cases/images/indicator-in-timeline.png
  docs/cases/images/indicator-query-timeline.png
  docs/cases/indicators-of-compromise.asciidoc
Labels: Team: Threat Hunting, Feature: Timeline, Priority: Low, Effort: Small, v8.12.0

#4497 [Bug][ESS][8.11 & 8.12]Missing ES|QL query rule type in the screenshot
  docs/detections/images/preview-rule.png
Labels: bug, Feature: Rules, Priority: Low, Effort: Small, v8.11.0, v8.12.0

#4498 [Bug][ESS][8.11] Screenshot needs to be updated for the missing ES|QL tab in timeline
  docs/cases/images/indicator-in-timeline.png
  docs/cases/images/indicator-query-timeline.png
  docs/events/images/timeline-ui-updated.png
Labels: bug, Team: Threat Hunting, Feature: Timeline, Priority: Low, Effort: Small, v8.11.0
