Repository elastic/security-docs, pull requests merged in 2023-11, with the labels that each got.

#4110 Updates warning about editing rules using API authentication
  docs/detections/api/rules/rules-api-bulk-actions.asciidoc
  docs/detections/api/rules/rules-api-create.asciidoc
  docs/detections/api/rules/rules-api-import.asciidoc
  docs/detections/api/rules/rules-api-overview.asciidoc
  docs/detections/api/rules/rules-api-update.asciidoc
Labels: v8.0.0, Team: Detections/Response, API, v8.1.0, v8.2.0, v8.3.0, Feature: Rules, v8.4.0, v8.5.0, v8.6.0, v8.7.0, v8.8.0, v8.9.0, Priority: Medium, v8.10.0, Effort: Small, v8.11.0

#4120 [BUG] Screenshot fixes needed for rule docs
  docs/detections/prebuilt-rules/images/process-exception.png
  docs/detections/prebuilt-rules/images/process-specific-exception.png
Labels: bug, v8.7.0, v8.8.0, v8.9.0, v8.10.0, v8.11.0

#4122 Prevalence enhancements
  docs/detections/alerts-view-details.asciidoc
  docs/detections/images/expanded-prevalence-view.png
Labels: Team: Threat Hunting, Feature: Alerts, v8.11.0

#4084 [8.11]Findings page EUI updates
  docs/cloud-native-security/cspm-findings.asciidoc
  docs/cloud-native-security/cspm-get-started-gcp.asciidoc
  docs/cloud-native-security/images/cnvm-findings-grouped.png
  docs/cloud-native-security/images/cnvm-findings-page.png
  docs/cloud-native-security/images/findings-page.png
  docs/cloud-native-security/kspm-findings.asciidoc
  docs/cloud-native-security/vuln-management-findings.asciidoc
  docs/getting-started/security-ui.asciidoc
Labels: Team: Cloud Security, v8.11.0

#4108 [8.11] CSPM dashboard product-led-growth update
  docs/cloud-native-security/cspm-cloud-posture-dashboard.asciidoc
  docs/cloud-native-security/kspm-cloud-posture-dashboard.asciidoc
  docs/dashboards/cloud-posture.asciidoc
  docs/dashboards/images/cloud-sec-dash-aws-version-row.png
  docs/dashboards/images/cloud-sec-dash-aws-version.png
  docs/dashboards/images/cloud-sec-dashboard-individual-row.png
  docs/dashboards/images/cloud-sec-dashboard.png
Labels: Team: Cloud Security, v8.11.0

#4067 [Detection Engine] update lists API
  docs/detections/api/exceptions/exceptions-api-overview.asciidoc
  docs/detections/api/exceptions/lists-index-api-overview.asciidoc
  docs/detections/api/lists/lists-api-overview.asciidoc
  docs/getting-started/detections-req.asciidoc
Labels: Team: Detection Engine, v8.11.0

#4137 Updates Network Beaconing installation link
  docs/experimental-features/beaconing-detection.asciidoc
Labels: Feature: Entity Analytics, Priority: High, Effort: Small, v8.11.0, ESS/Classic, Team: Entity Analytics

#4062 ES|QL rule docs
  docs/detections/about-rules.asciidoc
  docs/detections/api/rules/rules-api-create.asciidoc
  docs/detections/api/rules/rules-api-update.asciidoc
  docs/detections/images/esql-ref-button.png
  docs/detections/rules-ui-create.asciidoc
Labels: Feature: Rules, Team: Detection Engine, v8.11.0

#4197 Remove note that's in progress
  docs/detections/rules-ui-create.asciidoc
Labels: Feature: Rules, Team: Detection Engine, v8.11.0

#4199 [8.11] Remove note that's in progress
  docs/detections/rules-ui-create.asciidoc
Labels: v8.11.0

#4065 ES|QL tab added to Timeline
  docs/events/images/esql-tab.png
  docs/events/timeline-ui-overview.asciidoc
  docs/images/esql-ref-button.png
Labels: Team: Threat Hunting, Feature: Timeline, v8.11.0

#4149 [8.11] Adds knowledge base and Amazon Bedrock to AI Assistant docs
  docs/assistant/security-assistant.asciidoc
Labels: Feature:Elastic AI Assistant, v8.11.0

#4111 [8.11] CSPM onboarding for Azure (subscription-level) and for GCP (organization-level)
  docs/cloud-native-security/cloud-native-security-index.asciidoc
  docs/cloud-native-security/cspm-get-started-azure.asciidoc
  docs/cloud-native-security/cspm-get-started-gcp.asciidoc
Labels: Team: Cloud Security, v8.11.0

#4095 8.11 release notes
  docs/release-notes.asciidoc
  docs/release-notes/8.10.asciidoc
  docs/release-notes/8.11.asciidoc
Labels: release-notes, v8.11.0

#4205 What's new 8.11
  docs/whats-new.asciidoc
  docs/whats-new/images/8.11/cases-add-custom-field.png
  docs/whats-new/images/8.11/cases-settings.png
  docs/whats-new/images/8.11/entity-risk-score.png
  docs/whats-new/images/8.11/esql-rule.png
  docs/whats-new/images/8.11/esql-tab.png
Labels: highlights, v8.11.0

#4162 Entity Analytics: Requirements and limitations
  docs/getting-started/ers-req.asciidoc
  docs/getting-started/index.asciidoc
  docs/getting-started/sec-app-requirements.asciidoc
Labels: Feature: Entity Analytics, Priority: High, Effort: Medium, v8.11.0, ESS/Classic, Team: Entity Analytics

#4167 Entity Analytics: New Advanced Entity Analytics section
  docs/advanced-entity-analytics/advanced-entity-analytics-overview.asciidoc
  docs/advanced-entity-analytics/analyze-risk-score-data.asciidoc
  docs/advanced-entity-analytics/images/alerts-flyout-rs.png
  docs/advanced-entity-analytics/images/alerts-table-rs.png
  docs/advanced-entity-analytics/images/ea-dashboard.png
  docs/advanced-entity-analytics/images/filter-by-host-risk-level.png
  docs/advanced-entity-analytics/images/host-details-hr-tab.png
  docs/advanced-entity-analytics/images/host-details-overview.png
  docs/advanced-entity-analytics/images/hosts-hr-data.png
  docs/advanced-entity-analytics/images/hosts-hr-level.png
  docs/advanced-entity-analytics/images/preview-risky-entities.png
  docs/advanced-entity-analytics/images/risk-engine-upgrade-prompt.png
  docs/advanced-entity-analytics/images/risk-score-start-update.png
  docs/advanced-entity-analytics/images/turn-on-risk-engine.png
  docs/advanced-entity-analytics/turn-on-risk-engine.asciidoc
  docs/index.asciidoc
Labels: Feature: Entity Analytics, Priority: High, Effort: Large, v8.11.0, Team: Entity Analytics

#4193 Updates legacy EA docs
  docs/experimental-features/host-risk-score.asciidoc
  docs/experimental-features/user-risk-score.asciidoc
Labels: Feature: Entity Analytics, Priority: Medium, Effort: Small, v8.11.0, Team: Entity Analytics

#4211 Add beta tag for AI Assistant knowledge base
  docs/release-notes/8.11.asciidoc
  docs/whats-new.asciidoc
Labels: Feature: GenAI, Feature:Elastic AI Assistant, v8.11.0, ESS/Classic

#4228 [Security Solution] Add known issue for date selection in Protection Updates
  docs/release-notes/8.11.asciidoc
Labels: release-notes, known-issue, v8.11.0

#4232 Agent tamper protection
  docs/getting-started/agent-tamper-protection.asciidoc
  docs/getting-started/images/agent-tamper-protection.png
  docs/getting-started/index.asciidoc
  docs/getting-started/uninstall-agent.asciidoc
  docs/getting-started/uninstall-endpoint.asciidoc
  docs/release-notes/8.11.asciidoc
  docs/whats-new.asciidoc
  docs/whats-new/images/8.11/agent-tamper-protection.png
Labels: Team: Endpoint, Feature: Policy, Feature: Elastic Defend, v8.11.0

#4242 8.11.1 Release notes
  docs/release-notes.asciidoc
  docs/release-notes/8.11.asciidoc
Labels: release-notes, v8.11.0, v8.11.1

#4244 7.17.15 Release notes
  docs/release-notes.asciidoc
  docs/release-notes/7.17.asciidoc
Labels: release-notes, v7.17.0, v7.17.15

#4248 [BUG] 8.11.0 release notes include links to private repository
  docs/release-notes/8.11.asciidoc
Labels: Team: Endpoint, release-notes, v8.11.0

#4142 Add .vscode to .gitignore file
  .gitignore
Labels: Team:Docs, v7.17.0, v8.11.0

#4240 Add CODEOWNER
  .github/CODEOWNERS
Labels: backport-skip

#4253 Fix typo in agent-tamper-protection.asciidoc
  docs/getting-started/agent-tamper-protection.asciidoc
Labels: bug, Feature: Elastic Defend, v8.11.0, ESS

#4246 Updates to risk score tables
  docs/advanced-entity-analytics/analyze-risk-score-data.asciidoc
  docs/advanced-entity-analytics/images/ea-dashboard.png
  docs/advanced-entity-analytics/images/hosts-hr-data.png
  docs/dashboards/entity-dashboard.asciidoc
  docs/dashboards/images/entity-dashboard.png
  docs/dashboards/images/host-score-data.png
  docs/dashboards/images/user-score-data.png
  docs/experimental-features/host-risk-score.asciidoc
  docs/experimental-features/images/hosts-by-risk-tab.png
  docs/experimental-features/images/users-by-risk-details-page.png
Labels: Feature: Entity Analytics, Priority: High, Effort: Medium, v8.11.0, Team: Entity Analytics

#4263 Updates integration policy screenshot
  docs/management/admin/images/integration-pg.png
Labels: Team: Defend Workflows, Feature: Elastic Defend, Priority: Medium, Effort: Small, v8.11.0, ESS

#4234 Updates policies screenshot
  docs/management/admin/images/policy-list.png
Labels: bug, Team: Defend Workflows, Feature: Elastic Defend, Priority: Medium, Effort: Small, v8.11.0, ESS

#4286 Update Prebuilt Rule Links for Malicious Site in 8.10
  docs/detections/prebuilt-rules/downloadable-packages/0-14-2/prebuilt-rule-0-14-2-creation-of-a-hidden-local-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-2/prebuilt-rule-0-14-2-remote-file-copy-via-teamviewer.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/1-0-2/prebuilt-rule-1-0-2-account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/1-0-2/prebuilt-rule-1-0-2-creation-of-a-hidden-local-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/1-0-2/prebuilt-rule-1-0-2-remote-file-copy-via-teamviewer.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/1-0-2/prebuilt-rule-1-0-2-suspicious-managed-code-hosting-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/1-0-2/prebuilt-rule-1-0-2-suspicious-werfault-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-1-1/prebuilt-rule-8-1-1-account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-1-1/prebuilt-rule-8-1-1-creation-of-a-hidden-local-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-1-1/prebuilt-rule-8-1-1-remote-file-copy-via-teamviewer.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-10-2/prebuilt-rule-8-10-2-creation-of-a-hidden-local-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-10-2/prebuilt-rule-8-10-2-remote-execution-via-file-shares.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-10-2/prebuilt-rule-8-10-2-remote-file-copy-via-teamviewer.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-10-2/prebuilt-rule-8-10-2-suspicious-managed-code-hosting-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-10-2/prebuilt-rule-8-10-2-suspicious-werfault-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-2-1/prebuilt-rule-8-2-1-creation-of-a-hidden-local-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-2-1/prebuilt-rule-8-2-1-remote-file-copy-via-teamviewer.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-2-1/prebuilt-rule-8-2-1-suspicious-werfault-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-1/prebuilt-rule-8-3-1-suspicious-managed-code-hosting-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-2/prebuilt-rule-8-3-2-account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-2/prebuilt-rule-8-3-2-creation-of-a-hidden-local-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-2/prebuilt-rule-8-3-2-remote-execution-via-file-shares.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-2/prebuilt-rule-8-3-2-remote-file-copy-via-teamviewer.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-2/prebuilt-rule-8-3-2-suspicious-werfault-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-3/prebuilt-rule-8-3-3-account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-3/prebuilt-rule-8-3-3-creation-of-a-hidden-local-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-3/prebuilt-rule-8-3-3-remote-execution-via-file-shares.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-3/prebuilt-rule-8-3-3-remote-file-copy-via-teamviewer.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-3/prebuilt-rule-8-3-3-suspicious-managed-code-hosting-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-3/prebuilt-rule-8-3-3-suspicious-werfault-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-4/prebuilt-rule-8-3-4-suspicious-werfault-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-1/prebuilt-rule-8-4-1-account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-1/prebuilt-rule-8-4-1-creation-of-a-hidden-local-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-1/prebuilt-rule-8-4-1-remote-execution-via-file-shares.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-1/prebuilt-rule-8-4-1-remote-file-copy-via-teamviewer.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-1/prebuilt-rule-8-4-1-suspicious-werfault-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-2/prebuilt-rule-8-4-2-account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-2/prebuilt-rule-8-4-2-creation-of-a-hidden-local-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-2/prebuilt-rule-8-4-2-remote-execution-via-file-shares.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-2/prebuilt-rule-8-4-2-remote-file-copy-via-teamviewer.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-2/prebuilt-rule-8-4-2-suspicious-managed-code-hosting-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-2/prebuilt-rule-8-4-2-suspicious-werfault-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-3/prebuilt-rule-8-4-3-account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-5-1/prebuilt-rule-8-5-1-account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-6-1/prebuilt-rule-8-6-1-account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-7-1/prebuilt-rule-8-7-1-account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/rule-details/account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/rule-details/creation-of-a-hidden-local-user-account.asciidoc
  docs/detections/prebuilt-rules/rule-details/remote-execution-via-file-shares.asciidoc
  docs/detections/prebuilt-rules/rule-details/remote-file-copy-via-teamviewer.asciidoc
  docs/detections/prebuilt-rules/rule-details/suspicious-managed-code-hosting-process.asciidoc
  docs/detections/prebuilt-rules/rule-details/suspicious-werfault-child-process.asciidoc
Labels: backport-skip

#4288 Update Prebuilt Rule Links for Malicious Site in Main
  docs/detections/prebuilt-rules/downloadable-packages/0-14-2/prebuilt-rule-0-14-2-creation-of-a-hidden-local-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/0-14-2/prebuilt-rule-0-14-2-remote-file-copy-via-teamviewer.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/1-0-2/prebuilt-rule-1-0-2-account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/1-0-2/prebuilt-rule-1-0-2-creation-of-a-hidden-local-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/1-0-2/prebuilt-rule-1-0-2-remote-file-copy-via-teamviewer.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/1-0-2/prebuilt-rule-1-0-2-suspicious-managed-code-hosting-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/1-0-2/prebuilt-rule-1-0-2-suspicious-werfault-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-1-1/prebuilt-rule-8-1-1-account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-1-1/prebuilt-rule-8-1-1-creation-of-a-hidden-local-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-1-1/prebuilt-rule-8-1-1-remote-file-copy-via-teamviewer.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-2-1/prebuilt-rule-8-2-1-creation-of-a-hidden-local-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-2-1/prebuilt-rule-8-2-1-remote-file-copy-via-teamviewer.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-2-1/prebuilt-rule-8-2-1-suspicious-werfault-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-1/prebuilt-rule-8-3-1-suspicious-managed-code-hosting-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-2/prebuilt-rule-8-3-2-account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-2/prebuilt-rule-8-3-2-creation-of-a-hidden-local-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-2/prebuilt-rule-8-3-2-remote-execution-via-file-shares.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-2/prebuilt-rule-8-3-2-remote-file-copy-via-teamviewer.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-2/prebuilt-rule-8-3-2-suspicious-werfault-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-3/prebuilt-rule-8-3-3-account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-3/prebuilt-rule-8-3-3-creation-of-a-hidden-local-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-3/prebuilt-rule-8-3-3-remote-execution-via-file-shares.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-3/prebuilt-rule-8-3-3-remote-file-copy-via-teamviewer.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-3/prebuilt-rule-8-3-3-suspicious-managed-code-hosting-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-3/prebuilt-rule-8-3-3-suspicious-werfault-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-3-4/prebuilt-rule-8-3-4-suspicious-werfault-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-1/prebuilt-rule-8-4-1-account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-1/prebuilt-rule-8-4-1-creation-of-a-hidden-local-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-1/prebuilt-rule-8-4-1-remote-execution-via-file-shares.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-1/prebuilt-rule-8-4-1-remote-file-copy-via-teamviewer.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-1/prebuilt-rule-8-4-1-suspicious-werfault-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-2/prebuilt-rule-8-4-2-account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-2/prebuilt-rule-8-4-2-creation-of-a-hidden-local-user-account.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-2/prebuilt-rule-8-4-2-remote-execution-via-file-shares.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-2/prebuilt-rule-8-4-2-remote-file-copy-via-teamviewer.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-2/prebuilt-rule-8-4-2-suspicious-managed-code-hosting-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-2/prebuilt-rule-8-4-2-suspicious-werfault-child-process.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-4-3/prebuilt-rule-8-4-3-account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-5-1/prebuilt-rule-8-5-1-account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-6-1/prebuilt-rule-8-6-1-account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/downloadable-packages/8-7-1/prebuilt-rule-8-7-1-account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/rule-details/account-configured-with-never-expiring-password.asciidoc
  docs/detections/prebuilt-rules/rule-details/creation-of-a-hidden-local-user-account.asciidoc
  docs/detections/prebuilt-rules/rule-details/remote-execution-via-file-shares.asciidoc
  docs/detections/prebuilt-rules/rule-details/remote-file-copy-via-teamviewer.asciidoc
  docs/detections/prebuilt-rules/rule-details/suspicious-managed-code-hosting-process.asciidoc
  docs/detections/prebuilt-rules/rule-details/suspicious-werfault-child-process.asciidoc
Labels: backport-skip

#4261 Protection artifact update control
  docs/getting-started/artifact-control.asciidoc
  docs/getting-started/configure-integration-policy.asciidoc
Labels: Team: Defend Workflows, Feature: Elastic Defend, v8.11.0, Docset: ESS

#4252 Updates Name field in Add event filter flyout
  docs/management/admin/event-filters.asciidoc
  docs/management/admin/images/event-filter.png
Labels: bug, Team: Defend Workflows, Priority: Medium, Effort: Small, v8.11.0, Docset: ESS

#4192 Replaces Network Beaconing docs
  docs/detections/machine-learning/machine-learning.asciidoc
  docs/experimental-features/experimental-features-intro.asciidoc
Labels: Feature: Entity Analytics, Priority: Medium, Effort: Small, v8.11.0, Team: Entity Analytics

#4235 Expand on ES|QL rule docs
  docs/detections/rules-ui-create.asciidoc
Labels: Team: Detection Engine, v8.11.0

#4317 Create stub page for bi-directional integration response actions (SentinelOne)
  docs/management/admin/response-actions-config.asciidoc
  docs/management/manage-intro.asciidoc
Labels: Team: Defend Workflows, Feature: Response actions, Docset: ESS, v8.12.0

#4308 Issue template form — alternate take
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/documentation-issue.md
  .github/ISSUE_TEMPLATE/internal-docs-request.yaml
Labels: backport-skip

#4316 Adds Export exception list API docs
  docs/detections/api/exceptions-api-index.asciidoc
  docs/detections/api/exceptions/api-export-exception-list.asciidoc
Labels: v8.0.0, v7.11.0, API, v7.12.0, v7.13.0, v7.14.0, Team: Security Platform, v7.15.0, v7.16.0, v7.17.0, v8.1.0, v8.2.0, v8.3.0, v8.4.0, v8.5.0, Feature: Exceptions, v8.6.0, v8.7.0, v8.8.0, v8.9.0, Priority: Medium, v8.10.0, Effort: Medium, v8.11.0, v8.12.0

#4346 [7.13] Adds Export exception list API docs (#4316)
  docs/detections/api/exceptions-api-index.asciidoc
  docs/detections/api/exceptions/api-export-exception-list.asciidoc
Labels: backport

#4347 [7.12] Adds Export exception list API docs (#4316)
  docs/detections/api/exceptions-api-index.asciidoc
  docs/detections/api/exceptions/api-export-exception-list.asciidoc
Labels: backport

#4348 [7.11] Adds Export exception list API docs (#4316)
  docs/detections/api/exceptions-api-index.asciidoc
  docs/detections/api/exceptions/api-export-exception-list.asciidoc
Labels: backport

#4262 Adds new github issue template
  .github/ISSUE_TEMPLATE/ui-copy-request.yaml
Labels: backport-skip
