Repository elastic/security-docs, pull requests merged in 2024-06, with the labels that each got.

#5286 Adds LLM performance matrix doc to ESS & serverless
  docs/assistant/llm-performance-matrix.asciidoc
  docs/assistant/security-assistant.asciidoc
  docs/serverless/assistant/llm-performance-matrix.mdx
  docs/serverless/serverless-security.docnav.json
Labels: Team: GenAI, v8.13.0, v8.14.0, ci:doc-build

#5298 Delete serverless folder & its contents
  docs/serverless/assistant/llm-performance-matrix.mdx
  docs/serverless/serverless-security.docnav.json
Labels: v8.13.0

#5155 8.14.0 Release notes
  docs/release-notes.asciidoc
  docs/release-notes/8.14.asciidoc
Labels: release-notes, Priority: High, Effort: Large, Docset: ESS, v8.14.0

#5300 Create delete-serverless-dir-in-backports.yml
  .github/workflows/delete-serverless-dir-in-backports.yml
Labels: v8.0.0, v7.17.0, v8.1.0, v8.2.0, v8.3.0, v8.4.0, v8.5.0, v8.6.0, v8.7.0, v8.8.0, v8.9.0, v8.10.0, v8.11.0, v8.12.0, v8.13.0, v8.14.0, v8.15.0

#5333 [BUG] Updates attack discovery screenshot in highlights
  docs/whats-new/images/8.14/attack-discovery-full-card.png
Labels: bug, highlights, Priority: Low, Effort: Small, Docset: ESS, v8.14.0

#5344 [BUG] Fix screenshot of Defend integration policy
  docs/management/admin/images/integration-pg.png
  docs/serverless/images/endpoints-page/-management-admin-integration-pg.png
Labels: bug, Team: EDR Workflows, Feature: Policy, Feature: Elastic Defend, Docset: Serverless, Docset: ESS, v8.14.0, v8.15.0, ci:doc-build

#5268 [Request][Serverless] Users can access Discover from Security
  docs/serverless/investigate/timelines-ui.mdx
  docs/serverless/security-ui.mdx
Labels: backport-skip, Docset: Serverless, ci:doc-build

#5338 Update tip for finding TH integrations
  docs/getting-started/threat-intel-integrations.asciidoc
  docs/serverless/ingest/threat-intelligence.mdx
Labels: sdh-linked, Feature: Threat intel, Priority: High, Effort: Small, Docset: Serverless, Docset: ESS, v8.13.0, v8.14.0, ci:doc-build

#5346 [BUG] Update screenshot of trusted application example
  docs/management/admin/images/trusted-apps-list.png
  docs/serverless/images/trusted-apps-ov/-management-admin-trusted-apps-list.png
Labels: bug, Feature: Policy, Feature: Elastic Defend, Docset: Serverless, Docset: ESS, v8.14.0, v8.15.0, ci:doc-build

#5303 Creates AI Assistant use cases section
  docs/assistant/ai-alert-triage.asciidoc
  docs/assistant/ai-esql-queries.asciidoc
  docs/assistant/assistant-use-cases.asciidoc
  docs/assistant/images/attck-disc-11-alerts-disc.png
  docs/assistant/images/attck-disc-esql-query-gen-example.png
  docs/assistant/llm-connector-guides.asciidoc
  docs/assistant/security-assistant.asciidoc
  docs/assistant/use-attack-discovery-ai-assistant-incident-reporting.asciidoc
Labels: Team: GenAI, v8.14.0

#5271 Endpoint system requirements
  docs/getting-started/elastic-endpoint-reqs.asciidoc
  docs/serverless/edr-install-config/deploy-endpoint-reqs.mdx
Labels: Team: Endpoint, Priority: High, Effort: Small, Docset: Serverless, Docset: ESS, v8.13.0, v8.14.0, v8.15.0, ci:doc-build

#5362 Adds a video demo to the AD docs
  docs/attack-discovery/attack-discovery.asciidoc
  docs/serverless/attack-discovery/attack-discovery.mdx
Labels: Team: GenAI, v8.14.0, ci:doc-build

#5358 Update OpenAI and Azure OpenAI connector setup guides
  docs/assistant/azure-openai-setup.asciidoc
  docs/assistant/connect-to-openai.asciidoc
  docs/serverless/assistant/connect-to-azure-openai.mdx
  docs/serverless/assistant/connect-to-openai.mdx
Labels: v8.14.0, ci:doc-build

#5352 [DO NOT MERGE] Update publish_docs_co.yml to point to elastic.co/docs
  .github/workflows/co-docs-builder.yml
Labels: backport-skip

#5377 Update what-is-security-serverless.mdx to force a build
  docs/serverless/what-is-security-serverless.mdx
Labels: backport-skip

#5400 [7.10] fix: remove ndjson.org (#5376)
  docs/events/timeline-templates.asciidoc
  docs/events/timeline-ui-overview.asciidoc
  docs/getting-started/siem-ui.asciidoc
Labels: backport

#5399 [7.11] fix: remove ndjson.org (#5376)
  docs/events/timeline-templates.asciidoc
  docs/events/timeline-ui-overview.asciidoc
  docs/getting-started/siem-ui.asciidoc
Labels: backport

#5398 [7.12] fix: remove ndjson.org (#5376)
  docs/events/timeline-templates.asciidoc
  docs/events/timeline-ui-overview.asciidoc
  docs/getting-started/siem-ui.asciidoc
Labels: backport

#5397 [7.13] fix: remove ndjson.org (#5376)
  docs/events/timeline-templates.asciidoc
  docs/events/timeline-ui-overview.asciidoc
  docs/getting-started/siem-ui.asciidoc
Labels: backport

#5372 8.14.1 Release notes
  docs/release-notes.asciidoc
  docs/release-notes/8.14.asciidoc
Labels: release-notes, Priority: High, Effort: Small, v8.14.0, v8.14.1

#5279 7.17.22 Release notes
  docs/release-notes.asciidoc
  docs/release-notes/7.17.asciidoc
Labels: release-notes, Priority: High, Effort: Small, v7.17.22

#5292 [Request][Serverless & 8.15]: Expandable flyout setting being removed from advanced settings
  docs/detections/alerts-view-details.asciidoc
  docs/getting-started/advanced-setting.asciidoc
  docs/serverless/alerts/view-alert-details.mdx
  docs/serverless/settings/advanced-settings.mdx
Labels: Team: Threat Hunting, Priority: High, Effort: Small, Docset: Serverless, Docset: ESS, v8.15.0, ci:doc-build

#5405 Fix backport config file in 7.17 branch
  .backportrc.json
  docs/es-overview.asciidoc
Labels: bug

#5356 [BUG] Updates asset criticality gif in highlights
  docs/whats-new/images/8.14/asset-criticality-file-upload.gif
Labels: bug, highlights, Priority: Low, Effort: Small, Docset: ESS, v8.14.0

#5365 Fixes `comments` description in Update exception item API
  docs/detections/api/exceptions/api-update-exception-item.asciidoc
Labels: bug, v8.0.0, v7.9.0, v7.10.0, v7.11.0, API, v7.12.0, v7.13.0, v7.14.0, v7.15.0, v7.16.0, v7.17.0, v8.1.0, v8.2.0, v8.3.0, v8.4.0, v8.5.0, Feature: Exceptions, v8.6.0, v8.7.0, v8.8.0, v8.9.0, Team: Detection Engine, Priority: Medium, v8.10.0, Effort: Small, v8.11.0, Docset: ESS, v8.12.0, v8.13.0, v8.14.0, v8.15.0

#5436 Update .gitignore file for `7.9` branch
  .gitignore
Labels: v7.9.0

#5435 Update .gitignore file for `7.10` branch
  .gitignore
Labels: v7.10.0

#5406 Update .gitignore file for `7.17` branch
  .gitignore
Labels: v7.17.0

#5407 Updates .gitignore for `7.16` branch
  .gitignore
Labels: v7.16.0

#5408 Update .gitignore file for `7.15` branch
  .gitignore
Labels: v7.15.0

#5409 Update .gitignore file for `7.14` branch
  .gitignore
Labels: v7.14.0

#5431 Update .gitignore file for `7.13` branch
  .gitignore
Labels: v7.13.0

#5432 Update .gitignore file for `7.12` branch
  .gitignore
Labels: v7.12.0

#5434 Update .gitignore file for `7.11` branch
  .gitignore
Labels: v7.11.0

#5430 [7.12] Fixes `comments` description in Update exception item API (#5365)
  docs/detections/api/exceptions/api-update-exception-item.asciidoc
Labels: backport

#5433 [7.13] Fixes `comments` description in Update exception item API (#5365)
  docs/detections/api/exceptions/api-update-exception-item.asciidoc
Labels: backport

#5438 [7.11] Fixes `comments` description in Update exception item API (#5365)
  docs/detections/api/exceptions/api-update-exception-item.asciidoc
Labels: backport

#5439 [7.10] Fixes comments description in Update exception item API (#5365)
  docs/detections/api/exceptions/api-update-exception-item.asciidoc
Labels: backport

#5440 [7.9] Fixes comments description in Update exception item API (#5365)
  docs/detections/api/exceptions/api-update-exception-item.asciidoc
Labels: backport

#5360 Add license
  LICENSE
  README.md
Labels: v7.17.0, v8.14.0, v7.17.22

#5463 Update link in 8.8 release notes
  docs/release-notes/8.8.asciidoc
Labels: v8.8.0, v8.9.0, v8.8.2, v8.10.0, v8.9.2, v8.11.0, v8.10.4, v8.12.0, v8.13.0, v8.11.4, v8.14.0, v8.12.2, v8.15.0, v8.13.4, v8.14.2

#5444 SentinelOne `get-file` response action [serverless]
  docs/serverless/endpoint-response-actions/response-actions.mdx
  docs/serverless/endpoint-response-actions/third-party-actions.mdx
Labels: Team: EDR Workflows, backport-skip, Feature: Response actions, Docset: Serverless, ci:doc-build

#5471 [Serverless] Twin PR, AI use cases
  docs/serverless/assistant/ai-assistant-alert-triage.mdx
  docs/serverless/assistant/ai-assistant-esql-queries.mdx
  docs/serverless/assistant/ai-assistant.mdx
  docs/serverless/assistant/ai-use-cases.mdx
  docs/serverless/assistant/images/attck-disc-11-alerts-disc.png
  docs/serverless/assistant/images/attck-disc-esql-query-gen-example.png
  docs/serverless/assistant/llm-connector-guides.mdx
  docs/serverless/assistant/usecase-attack-disc-ai-assistant-incident-reporting.mdx
  docs/serverless/serverless-security.docnav.json
Labels: backport-skip, ci:doc-build

#5475 Creates "Connect to Google vertex" llm connector guide
  docs/serverless/assistant/connect-to-openai.mdx
  docs/serverless/assistant/connect-to-vertex.mdx
  docs/serverless/assistant/llm-connector-guides.mdx
  docs/serverless/assistant/usecase-attack-disc-ai-assistant-incident-reporting.mdx
  docs/serverless/serverless-security.docnav.json
Labels: backport-skip, Team: GenAI, ci:doc-build
