Repository elastic/security-docs, pull requests merged in 2025-02, with the labels that each got.

#6510 Update .backportrc.json
  .backportrc.json
Labels: backport-skip

#6509 [Main] Update .mergify.yml
  .mergify.yml
Labels: backport-skip

#6507 Adds `8.18` backport option to mergify
  .mergify.yml
Labels: backport-skip

#6512 [Known Issue][8.17.0 & 8.17.1]: Elastic Security crashes in ECH on Kibana instances with 1 GB of RAM
  docs/release-notes/8.17.asciidoc
Labels: release-notes, known-issue, Effort: Small, Priority: Urgent, v8.17.0, v8.18.0, v8.17.1

#6505 8.17.2 release notes
  docs/release-notes.asciidoc
  docs/release-notes/8.17.asciidoc
Labels: release-notes, Priority: High, Effort: Small, Docset: ESS, v8.17.0, v8.18.0, v8.17.2

#6504 8.16.4 release notes
  docs/release-notes.asciidoc
  docs/release-notes/8.16.asciidoc
Labels: release-notes, Priority: High, Effort: Small, Docset: ESS, v8.16.0, v8.17.0, v8.18.0, v8.16.4, v8.17.2

#6540 7.17.28 release notes
  docs/release-notes.asciidoc
  docs/release-notes/7.17.asciidoc
Labels: release-notes, Priority: High, Effort: Small, v7.17.28

#6544 fixes list formatting on CSPM Findings page
  docs/cloud-native-security/cspm-findings.asciidoc
Labels: v8.13.0, v8.14.0, v8.15.0, v8.16.0, v8.17.0

#6549 Doc incompatibility between agentless integration and traffic filtering
  docs/cloud-native-security/cspm-get-started-aws.asciidoc
  docs/cloud-native-security/cspm-get-started-azure.asciidoc
  docs/cloud-native-security/cspm-get-started-gcp.asciidoc
  docs/getting-started/agentless-troubleshooting.asciidoc
  docs/getting-started/index.asciidoc
Labels: v8.16.0, v8.17.0

#6553 [docs] Add the new docs CI checks
  .github/workflows/comment-on-asciidoc-changes.yml
  .github/workflows/docs-build.yml
  .github/workflows/docs-cleanup.yml
Labels: backport-skip

#6555 Fix broken svg links in prebuilt jobs page
  docs/reference/images/link.svg
  docs/reference/prebuilt-jobs.md
Labels: backport-skip

#6556 Fix links to Elastic Defend content
  docs/reference/endpoint-command-reference.md
Labels: backport-skip
