Repository elastic/security-docs, pull requests merged in 2025-04, with the labels that each got.

#6693 8.18 Automatic import updates
  docs/getting-started/automatic-import.asciidoc
Labels: v8.18.0

#6690 738 llm matrix
  docs/AI-for-security/llm-performance-matrix.asciidoc
Labels: v8.17.0, v8.18.0

#6692 Updates connect to Bedrock guide
  docs/AI-for-security/connect-to-bedrock.asciidoc
Labels: v8.15.0, v8.16.0, v8.17.0, v8.18.0

#6655 [8.18] Logged ES queries now provided for new terms, machine learning, custom query, threshold rule types
  docs/detections/rules-ui-create.asciidoc
Labels: Team: Detection Engine, Priority: High, Effort: Small, Docset: ESS, v8.18.0

#6691 [8.18]AI for Security updates
  docs/AI-for-security/ai-security-assistant.asciidoc
  docs/AI-for-security/attack-discovery.asciidoc
  docs/AI-for-security/connector-guides-landing-pg.asciidoc
  docs/AI-for-security/images/security-attack-discovery-more-popover.png
  docs/AI-for-security/images/security-attack-discovery-settings.png
  docs/AI-for-security/usecase-attack-discovery-ai-assistant-incident-reporting.asciidoc
  docs/AI-for-security/usecase-landing-pg.asciidoc
Labels: v8.18.0

#6694 Fixed header level for DaC docs
  docs/detections/detection-engine-intro.asciidoc
Labels: v8.18.0

#6695 [REQUEST][8.18]: Visualizations in the alert details flyout are enabled by default
  docs/detections/alerts-view-details.asciidoc
  docs/detections/visual-event-analyzer.asciidoc
  docs/getting-started/advanced-setting.asciidoc
Labels: Team: Threat Hunting, Priority: High, Effort: Small, v8.18.0

#6696 [REQUEST][8.18]: Show flyout history for alerts/host/user/events
  docs/detections/alerts-view-details.asciidoc
  docs/detections/images/history-icon.png
Labels: Team: Threat Hunting, Feature: Alerts, Priority: High, Effort: Small, v8.18.0

#6713 Removes elastic LLM
  docs/AI-for-security/connector-guides-landing-pg.asciidoc
Labels: v8.18.0

#6519 8.18.0 Release notes
  docs/release-notes.asciidoc
  docs/release-notes/8.18.asciidoc
Labels: release-notes, Priority: High, Effort: Large, Docset: ESS, v8.18.0, v8.19.0

#6710 What's new in 8.18
  docs/whats-new.asciidoc
  docs/whats-new/images/8.18/engine-status.png
  docs/whats-new/images/8.18/gaps-table.png
  docs/whats-new/images/8.18/include-closed-alerts.png
  docs/whats-new/images/8.18/security-attack-discovery-settings.png
  docs/whats-new/images/8.18/security-siem-migration-1.png
  docs/whats-new/images/8.18/service-risk-scores.png
Labels: highlights, Priority: High, Effort: Medium, Docset: ESS, v8.18.0, v8.19.0

#6659 [Detection Engine][Docs][8.18] New wording for frozen tier support
  docs/detections/detection-engine-intro.asciidoc
Labels: Team: Detection Engine, Priority: High, Effort: Small, v8.18.0

#6725 Fixed typo in DaC docs
  docs/detections/detection-engine-intro.asciidoc
Labels: Feature: Rules, Priority: High, Effort: Small, v8.18.0

#6727 Additional known issue for 8.17.4 RNs
  docs/release-notes/8.17.asciidoc
Labels: release-notes, Priority: High, Effort: Small, v8.17.0, v8.18.0, v8.19.0

#6729 Additional known issue for 8.18.0 RNs
  docs/release-notes/8.18.asciidoc
Labels: release-notes, Priority: High, Effort: Small, v8.18.0, v8.19.0

#6731 Deletes Timeline API
  docs/events/api/timeline-api-create.asciidoc
  docs/events/api/timeline-api-delete.asciidoc
  docs/events/api/timeline-api-export.asciidoc
  docs/events/api/timeline-api-get.asciidoc
  docs/events/api/timeline-api-import.asciidoc
  docs/events/api/timeline-api-index.asciidoc
  docs/events/api/timeline-api-overview.asciidoc
  docs/events/api/timeline-api-update.asciidoc
  docs/events/api/timeline-template-api-update.asciidoc
  docs/siem-apis.asciidoc
Labels: API, v8.16.0, v8.17.0, v8.18.0, v8.19.0

#6730 Deletes Exceptions API
  docs/detections/api/exceptions-api-index.asciidoc
  docs/detections/api/exceptions/api-create-exception-container.asciidoc
  docs/detections/api/exceptions/api-create-exception-item.asciidoc
  docs/detections/api/exceptions/api-create-shared-exception-list.asciidoc
  docs/detections/api/exceptions/api-delete-exception-container.asciidoc
  docs/detections/api/exceptions/api-delete-exception-item.asciidoc
  docs/detections/api/exceptions/api-export-exception-list.asciidoc
  docs/detections/api/exceptions/api-find-exception-containers.asciidoc
  docs/detections/api/exceptions/api-find-exception-items.asciidoc
  docs/detections/api/exceptions/api-get-exception-containers.asciidoc
  docs/detections/api/exceptions/api-get-exception-items.asciidoc
  docs/detections/api/exceptions/api-import-exception-list.asciidoc
  docs/detections/api/exceptions/api-summary-exception-container.asciidoc
  docs/detections/api/exceptions/api-update-exception-container.asciidoc
  docs/detections/api/exceptions/api-update-exception-item.asciidoc
  docs/detections/api/exceptions/exceptions-api-overview.asciidoc
  docs/detections/api/exceptions/images/exceptions-logic.png
  docs/detections/api/exceptions/lists-index-api-overview.asciidoc
  docs/detections/api/lists/api-create-list-item.asciidoc
  docs/detections/api/lists/api-delete-list-item.asciidoc
  docs/detections/api/lists/api-update-list-item.asciidoc
  docs/detections/api/lists/lists-api-overview.asciidoc
  docs/detections/api/rules/rules-api-create-single-rule-exception-item.asciidoc
  docs/detections/api/rules/rules-api-create.asciidoc
  docs/detections/api/rules/rules-api-update.asciidoc
  docs/release-notes/8.7.asciidoc
  docs/release-notes/8.8.asciidoc
  docs/siem-apis.asciidoc
Labels: API, v8.16.0, v8.17.0, v8.18.0, v8.19.0

#6745 8.17.5 release notes
  docs/release-notes.asciidoc
  docs/release-notes/8.17.asciidoc
Labels: release-notes, Priority: High, Effort: Small, v8.17.0, v8.18.0, v8.17.5

#6744 Adds note about max file size for get-file command
  docs/management/admin/response-actions.asciidoc
Labels: v8.7.0, v8.8.0, v8.9.0, v8.10.0, v8.11.0, v8.12.0, v8.13.0, v8.14.0, v8.15.0, v8.16.0, v8.17.0, v8.18.0

#6751 [bug][8.x] Adds Automatic Troubleshooting guide
  docs/management/admin/identify-antivirus-software-on-hosts.asciidoc
  docs/management/manage-intro.asciidoc
Labels: v8.18.0

#6639 [8.17-8.18] More changes to the LogsDB page
  docs/detections/detections-logsdb-impact.asciidoc
Labels: Team: Detection Engine, Priority: High, Effort: Small, v8.17.0, v8.18.0

#6787 Update llm-performance-matrix.asciidoc
  docs/AI-for-security/llm-performance-matrix.asciidoc
Labels: v8.15.0, v8.16.0, v8.17.0, v8.18.0

#6786 [8.18] expands AI use cases page
  docs/AI-for-security/usecase-landing-pg.asciidoc
Labels: v8.18.0
